// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <active_auth.h>
#include <chip_auth.h>
#include <pace.h>
#include <passive_auth.h>
#include <data_group.h>
#include <emrtd_card.h>
#include <emrtd_types.h>
#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/Plugin/SecurityCheck.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <apdu.h>
#include <smartcard/pcsc_connection.h>

#include <algorithm>
#include <compare>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <map>
#include <mutex>
#include <optional>
#include <string>
#include <variant>

#include "manifest.h" // generated by librescrs_add_plugin (A5)

namespace {

// A5 (4.0 hardening): pluginId / displayName / capabilities / kAtrs come
// from the per-plugin manifest.json via the generated manifest.h header.
// eMRTD passports never advertise via ATR — the applet is detected by
// SELECT FILE on a live session, so kAtrs is intentionally empty.

// Format MRZ date YYMMDD → DD.MM.YYYY.
// For DOB: 2-digit year mapped to past (20xx if ≤ current year, else 19xx).
// For DOE: 2-digit year mapped to future (19xx only if > current year + 20).
std::string formatMRZDate(const std::string& yymmdd, bool isExpiry = false)
{
    if (yymmdd.size() != 6)
        return yymmdd;
    std::string yy = yymmdd.substr(0, 2);
    std::string mm = yymmdd.substr(2, 2);
    std::string dd = yymmdd.substr(4, 2);
    int y = std::stoi(yy);
    int fullYear;
    if (isExpiry) {
        // Expiry dates are in the near future — use 20xx unless obviously wrong
        fullYear = (y + 2000 > 2080) ? 1900 + y : 2000 + y;
    } else {
        // Birth dates are in the past — use 19xx if 20xx would be in the future
        auto now = std::time(nullptr);
        struct tm tmBuf{};
        localtime_r(&now, &tmBuf);
        int currentYY = (tmBuf.tm_year + 1900) % 100;
        fullYear = (y > currentYY) ? 1900 + y : 2000 + y; // NOLINT(readability-magic-numbers)
    }
    return dd + "." + mm + "." + std::to_string(fullYear);
}

struct SessionContext
{
    std::optional<std::variant<emrtd::MRZData, std::string>> credentials;
    std::string pendingDocNum, pendingDob, pendingExpiry;
    std::unique_ptr<emrtd::EMRTDCard> emrTDCard;
};

/// @brief Per-session state map key.
///
/// Combining reader name with the CardSession's monotonic generation
/// counter yields a key that is stable for the lifetime of the session
/// and definitively distinct from any successor session — even when the
/// OS reissues the same PCSCConnection address to a freshly opened
/// reader. Raw-pointer keying used to silently leak credentials in that
/// scenario.
struct SessionKey
{
    std::string readerName;
    std::uint64_t generation{0};

    auto operator<=>(const SessionKey&) const = default;
};

SessionKey makeSessionKey(LibreSCRS::SmartCard::CardSession& session)
{
    return SessionKey{session.readerName(), LibreSCRS::SmartCard::detail::sessionGeneration(session)};
}

class EMRTDCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    EMRTDCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::emrtd::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::emrtd::kDisplayName},
                    /*priority=*/800);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::emrtd::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::emrtd::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            const auto key = makeSessionKey(session);
            // Reset session for this key (new card insert = new session)
            std::lock_guard lock(mtx);
            sessions.erase(key);
            conn.clearTransmitFilter();

            // SELECT eMRTD applet by AID (P2=0x0C: no FCI response)
            auto response = conn.transmit(
                smartcard::selectByAID({emrtd::EMRTD_AID, emrtd::EMRTD_AID + emrtd::EMRTD_AID_LEN}, 0x0C));
            return response.isSuccess();
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        // Delegate to the CardData-returning body, then classify the
        // outcome: a group with groupKey "error" indicates authentication
        // failure; "auth_required" indicates credentials are needed
        // (AuthenticationFailed per the 4.0 ABI v6 taxonomy); everything else
        // is Ok. This keeps the existing control flow intact while still
        // honouring the no-exceptions-across-ABI contract.
        try {
            auto data = readCardImpl(cardSession, std::move(onGroup));
            for (const auto& g : data.groups) {
                if (g.groupKey == "error")
                    return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                            std::string{"eMRTD authentication failed"});
            }
            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eMRTD readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eMRTD readCard failed (unknown error)"});
        }
    }

private:
    LibreSCRS::Plugin::CardData readCardImpl(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        const auto key = makeSessionKey(cardSession);
        LibreSCRS::Plugin::CardData data;
        data.cardType = "emrtd";

        auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
            if (onGroup)
                onGroup(data.cardType, group);
            data.groups.push_back(std::move(group));
        };

        std::unique_lock lock(mtx);

        auto& session = sessions[key];

        if (!session.credentials) {
            // Phase 1: no credentials — return auth_required (no streaming needed)
            LibreSCRS::Plugin::CardFieldGroup authGroup;
            authGroup.groupKey = "auth_required";
            authGroup.groupLabel = "Authentication Required";

            auto addText = [&](const std::string& key, const std::string& label, const std::string& val) {
                authGroup.fields.push_back({key, label, LibreSCRS::Plugin::FieldType::Text, {val.begin(), val.end()}});
            };

            addText("status", "Status", "MRZ or CAN required");

            bool paceSupported = false;
            std::vector<std::string> paceOids;
            try {
                smartcard::APDUCommand selectCmd{
                    0x00, 0xA4, 0x04, 0x0C, {emrtd::EMRTD_AID, emrtd::EMRTD_AID + emrtd::EMRTD_AID_LEN}, 0, false};
                conn.transmit(selectCmd);

                smartcard::APDUCommand readCA{
                    0x00, 0xB0, static_cast<uint8_t>(0x80 | emrtd::SFID_CARD_ACCESS), 0x00, {}, 0x00, true};
                auto caResp = conn.transmit(readCA);
                if (caResp.isSuccess() && !caResp.data.empty()) {
                    paceOids = emrtd::crypto::parseCardAccess(caResp.data);
                    paceSupported = !paceOids.empty();
                }
            } catch (...) {
            }

            addText("pace_supported", "PACE Supported", paceSupported ? "true" : "false");
            if (!paceOids.empty()) {
                std::string oids;
                for (const auto& oid : paceOids) {
                    if (!oids.empty())
                        oids += ", ";
                    oids += oid;
                }
                addText("pace_oids", "PACE Algorithms", oids);
            }

            data.groups.push_back(std::move(authGroup));
            return data;
        }

        // Phase 2: credentials set — authenticate and read
        auto creds = *session.credentials;
        lock.unlock();

        std::unique_ptr<emrtd::EMRTDCard> localCard;
        if (auto* mrz = std::get_if<emrtd::MRZData>(&creds)) {
            localCard = std::make_unique<emrtd::EMRTDCard>(conn, *mrz);
        } else if (auto* can = std::get_if<std::string>(&creds)) {
            localCard = std::make_unique<emrtd::EMRTDCard>(conn, *can);
        }
        emrtd::EMRTDCard* card = nullptr;
        {
            std::lock_guard lk(mtx);
            sessions[key].emrTDCard = std::move(localCard);
            card = sessions[key].emrTDCard.get();
        }

        auto authResult = card->authenticate();
        if (!authResult.success) {
            LibreSCRS::Plugin::CardFieldGroup errorGroup;
            errorGroup.groupKey = "error";
            errorGroup.groupLabel = "Authentication Failed";
            std::string err = authResult.error;
            errorGroup.fields.push_back(
                {"error", "Error", LibreSCRS::Plugin::FieldType::Text, {err.begin(), err.end()}});
            data.groups.push_back(std::move(errorGroup));
            return data;
        }

        // --- ICAO-compliant reading flow ---

        auto addTextField = [](LibreSCRS::Plugin::CardFieldGroup& g, std::string_view key, std::string_view label,
                               std::string_view val) {
            if (!val.empty())
                g.fields.push_back({std::string{key}, std::string{label}, LibreSCRS::Plugin::FieldType::Text,
                                    std::vector<uint8_t>{val.begin(), val.end()}});
        };

        // 1. Read COM → emit presence group
        auto dgList = card->readCOM();
        {
            LibreSCRS::Plugin::CardFieldGroup g;
            g.groupKey = "presence";
            g.groupLabel = "Data Groups Present";
            std::string dgListStr;
            for (int dg : dgList) {
                if (!dgListStr.empty())
                    dgListStr += ", ";
                dgListStr += "DG" + std::to_string(dg);
            }
            addTextField(g, "data_groups", "Data Groups", dgListStr);
            addTextField(g, "auth_method", "Authentication Method",
                         authResult.method == emrtd::AuthMethod::BAC        ? "BAC"
                         : authResult.method == emrtd::AuthMethod::PACE_MRZ ? "PACE (MRZ)"
                                                                            : "PACE (CAN)");
            emitGroup(std::move(g));
        }

        // 2. Read SOD → store raw bytes
        auto sodRaw = card->readSOD();

        // 3. Parse SOD → get authoritative DG list from hash entries
        std::vector<int> authoritativeDGs;
        std::optional<emrtd::crypto::SODContent> sodContent;
        if (sodRaw) {
            sodContent = emrtd::crypto::parseSOD(*sodRaw);
            if (sodContent) {
                for (const auto& [dgNum, hash] : sodContent->dgHashes)
                    authoritativeDGs.push_back(dgNum);
                std::sort(authoritativeDGs.begin(), authoritativeDGs.end());
            }
        }
        // Fall back to COM list if SOD parsing failed
        if (authoritativeDGs.empty())
            authoritativeDGs = dgList;

        bool hasDG14 = std::find(authoritativeDGs.begin(), authoritativeDGs.end(), 14) != authoritativeDGs.end();
        bool hasDG15 = std::find(authoritativeDGs.begin(), authoritativeDGs.end(), 15) != authoritativeDGs.end();

        // Storage for raw DG bytes (for passive auth)
        std::map<int, std::vector<uint8_t>> dgRawData;

        // 4. If DG14 present → Chip Authentication → upgrade SM
        emrtd::crypto::ChipAuthResult caResult;
        caResult.chipAuthentication = emrtd::crypto::ChipAuthResult::NOT_PERFORMED;
        caResult.activeAuthentication = emrtd::crypto::ChipAuthResult::NOT_PERFORMED;

        if (hasDG14) {
            auto dg14Result = card->readDataGroupSafe(14);
            if (dg14Result.status == emrtd::DGReadStatus::OK && !dg14Result.data.empty()) {
                dgRawData[14] = dg14Result.data;
                if (card->hasSecureMessaging()) {
                    caResult =
                        emrtd::crypto::performChipAuth(card->connection(), dg14Result.data, card->secureMessaging());
                    if (caResult.newSessionKeys) {
                        card->replaceSM(*caResult.newSessionKeys, caResult.newAlgorithm);
                    }
                }
            }
        }

        // 5. If no DG14 but DG15 present → Active Authentication
        if (caResult.chipAuthentication != emrtd::crypto::ChipAuthResult::PASSED && hasDG15) {
            auto dg15Result = card->readDataGroupSafe(15);
            if (dg15Result.status == emrtd::DGReadStatus::OK && !dg15Result.data.empty()) {
                dgRawData[15] = dg15Result.data;
                if (card->hasSecureMessaging()) {
                    auto aaResult =
                        emrtd::crypto::performActiveAuth(card->connection(), dg15Result.data, card->secureMessaging());
                    caResult.activeAuthentication = aaResult.activeAuthentication;
                    if (aaResult.errorDetail.size() > caResult.errorDetail.size())
                        caResult.errorDetail = aaResult.errorDetail;
                }
            }
        }

        // 6. Read remaining DGs and emit groups
        for (int dg : authoritativeDGs) {
            // Skip DG14/DG15 — already read above
            if (dg == 14 || dg == 15)
                continue;

            auto dgResult = card->readDataGroupSafe(dg);
            if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                dgRawData[dg] = dgResult.data;
            }

            // Parse and emit based on DG number
            switch (dg) {
            case 1: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[1] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg1) {
                    {
                        LibreSCRS::Plugin::CardFieldGroup g;
                        g.groupKey = "personal";
                        g.groupLabel = "Personal Data (DG1)";
                        addTextField(g, "surname", "Surname", parsed.dg1->surname);
                        addTextField(g, "given_names", "Given Names", parsed.dg1->givenNames);
                        addTextField(g, "nationality", "Nationality", parsed.dg1->nationality);
                        addTextField(g, "date_of_birth", "Date of Birth", formatMRZDate(parsed.dg1->dateOfBirth));
                        addTextField(g, "sex", "Sex", parsed.dg1->sex);
                        emitGroup(std::move(g));
                    }
                    {
                        LibreSCRS::Plugin::CardFieldGroup g;
                        g.groupKey = "document";
                        g.groupLabel = "Document Data (DG1)";
                        addTextField(g, "document_number", "Document Number", parsed.dg1->documentNumber);
                        addTextField(g, "document_code", "Document Code", parsed.dg1->documentCode);
                        addTextField(g, "issuing_state", "Issuing State", parsed.dg1->issuingState);
                        addTextField(g, "date_of_expiry", "Date of Expiry",
                                     formatMRZDate(parsed.dg1->dateOfExpiry, true));
                        addTextField(g, "personal_number", "Personal Number", parsed.dg1->optionalData);
                        emitGroup(std::move(g));
                    }
                }
                break;
            }
            case 2: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[2] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg2) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "photo";
                    g.groupLabel = "Photo";
                    g.fields.push_back({"photo", "Photo", LibreSCRS::Plugin::FieldType::Photo, parsed.dg2->imageData});
                    emitGroup(std::move(g));
                }
                break;
            }
            case 3: {
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "biometric_fingerprint";
                g.groupLabel = "Fingerprint (DG3)";
                if (dgResult.status == emrtd::DGReadStatus::ACCESS_DENIED) {
                    addTextField(g, "access", "Access", "EAC required");
                } else if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                    g.fields.push_back(
                        {"fingerprint", "Fingerprint", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                } else {
                    break; // NOT_PRESENT or ERROR — skip
                }
                emitGroup(std::move(g));
                break;
            }
            case 4: {
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "biometric_iris";
                g.groupLabel = "Iris (DG4)";
                if (dgResult.status == emrtd::DGReadStatus::ACCESS_DENIED) {
                    addTextField(g, "access", "Access", "EAC required");
                } else if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                    g.fields.push_back({"iris", "Iris", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                } else {
                    break; // NOT_PRESENT or ERROR — skip
                }
                emitGroup(std::move(g));
                break;
            }
            case 5: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                // DG5 contains a portrait image — emit raw as photo
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "portrait";
                g.groupLabel = "Portrait (DG5)";
                g.fields.push_back({"portrait", "Portrait", LibreSCRS::Plugin::FieldType::Photo, dgResult.data});
                emitGroup(std::move(g));
                break;
            }
            case 7: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[7] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg7) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "signature";
                    g.groupLabel = "Signature / Mark (DG7)";
                    g.fields.push_back(
                        {"signature", "Signature", LibreSCRS::Plugin::FieldType::Photo, parsed.dg7->imageData});
                    emitGroup(std::move(g));
                }
                break;
            }
            case 11: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[11] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg11) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "additional";
                    g.groupLabel = "Additional Personal Data (DG11)";
                    addTextField(g, "full_name", "Full Name", parsed.dg11->fullName);
                    addTextField(g, "other_names", "Other Names", parsed.dg11->otherNames);
                    addTextField(g, "personal_number", "Personal Number", parsed.dg11->personalNumber);
                    addTextField(g, "place_of_birth", "Place of Birth", parsed.dg11->placeOfBirth);
                    addTextField(g, "address", "Address", parsed.dg11->address);
                    addTextField(g, "telephone", "Telephone", parsed.dg11->telephone);
                    addTextField(g, "profession", "Profession", parsed.dg11->profession);
                    addTextField(g, "title", "Title", parsed.dg11->title);
                    addTextField(g, "custody_info", "Custody Information", parsed.dg11->custodyInfo);
                    if (!g.fields.empty())
                        emitGroup(std::move(g));
                }
                break;
            }
            case 12: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[12] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg12) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "document_extra";
                    g.groupLabel = "Issuing Information (DG12)";
                    addTextField(g, "issuing_authority", "Issuing Authority", parsed.dg12->issuingAuthority);
                    std::string doi = parsed.dg12->dateOfIssue;
                    if (doi.size() == 8)
                        doi = doi.substr(6, 2) + "." + doi.substr(4, 2) + "." + doi.substr(0, 4);
                    else if (doi.size() == 6)
                        doi = formatMRZDate(doi, true);
                    addTextField(g, "date_of_issue", "Date of Issue", doi);
                    addTextField(g, "endorsements", "Endorsements", parsed.dg12->endorsements);
                    addTextField(g, "tax_exit", "Tax/Exit Requirements", parsed.dg12->taxExitRequirements);
                    if (!g.fields.empty())
                        emitGroup(std::move(g));
                }
                break;
            }
            case 13: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "national";
                g.groupLabel = "National Data (DG13)";
                g.fields.push_back(
                    {"national_data", "National Data", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                emitGroup(std::move(g));
                break;
            }
            case 16: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                auto contacts = emrtd::EMRTDCard::parseDG16(dgResult.data);
                if (!contacts.empty()) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "contacts";
                    g.groupLabel = "Persons to Notify (DG16)";
                    int idx = 0;
                    for (const auto& contact : contacts) {
                        std::string prefix = (contacts.size() > 1) ? "contact_" + std::to_string(idx) + "_" : "";
                        addTextField(g, prefix + "name", "Name", contact.name);
                        addTextField(g, prefix + "telephone", "Telephone", contact.telephone);
                        addTextField(g, prefix + "address", "Address", contact.address);
                        ++idx;
                    }
                    emitGroup(std::move(g));
                }
                break;
            }
            default:
                break;
            }
        }

        // 7. Passive Authentication
        LibreSCRS::Plugin::SecurityStatus secStatus;

        if (sodRaw && !dgRawData.empty()) {
            // CSCA trust store path from env var
            std::string trustStorePath;
            if (const char* envPath = std::getenv("LIBRESCRS_CSCA_STORE"))
                trustStorePath = envPath;

            auto paResult = emrtd::crypto::performPassiveAuth(*sodRaw, dgRawData, trustStorePath);

            // SOD signature check
            {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_sod_signature";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "SOD Digital Signature";
                check.status = (paResult.sodSignature == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (paResult.sodSignature == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                if (!paResult.dscSubject.empty())
                    check.detail = "DSC: " + paResult.dscSubject;
                secStatus.checks.push_back(std::move(check));
            }

            // CSCA chain check
            {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_csca_chain";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "CSCA Certificate Chain";
                check.status = (paResult.cscaChain == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (paResult.cscaChain == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                if (trustStorePath.empty())
                    check.detail = "No CSCA trust store configured";
                secStatus.checks.push_back(std::move(check));
            }

            // Per-DG hash checks
            for (const auto& [dgNum, status] : paResult.dgHashes) {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_dg" + std::to_string(dgNum) + "_hash";
                check.category = LibreSCRS::Plugin::SecurityCategory::DataIntegrity;
                check.label = "DG" + std::to_string(dgNum) + " Hash (" + paResult.hashAlgorithm + ")";
                check.status = (status == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (status == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                secStatus.checks.push_back(std::move(check));
            }

            if (!paResult.errorDetail.empty()) {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_error";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "Passive Authentication";
                check.status = LibreSCRS::Plugin::SecurityCheck::Status::Failed;
                check.errorDetail = paResult.errorDetail;
                secStatus.checks.push_back(std::move(check));
            }
        }

        // Chip Authentication check
        {
            LibreSCRS::Plugin::SecurityCheck check;
            check.checkId = "chip_auth";
            check.category = LibreSCRS::Plugin::SecurityCategory::Genuineness;
            check.label = "Chip Authentication";
            check.status = (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::PASSED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                           : (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::FAILED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                           : (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::NOT_SUPPORTED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::NotSupported
                               : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
            if (!caResult.protocol.empty())
                check.detail = caResult.protocol;
            secStatus.checks.push_back(std::move(check));
        }

        // Active Authentication check
        {
            LibreSCRS::Plugin::SecurityCheck check;
            check.checkId = "active_auth";
            check.category = LibreSCRS::Plugin::SecurityCategory::Genuineness;
            check.label = "Active Authentication";
            check.status = (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::PASSED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                           : (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::FAILED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                           : (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::NOT_SUPPORTED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::NotSupported
                               : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
            if (!caResult.errorDetail.empty())
                check.errorDetail = caResult.errorDetail;
            secStatus.checks.push_back(std::move(check));
        }

        secStatus.computeOverall();

        // 8. Emit security_status group
        {
            LibreSCRS::Plugin::CardFieldGroup g;
            g.groupKey = "security_status";
            g.groupLabel = "Security Verification";

            addTextField(g, "overall_integrity", "Data Integrity",
                         LibreSCRS::Plugin::statusToString(secStatus.overallIntegrity));
            addTextField(g, "overall_authenticity", "Data Authenticity",
                         LibreSCRS::Plugin::statusToString(secStatus.overallAuthenticity));
            addTextField(g, "overall_genuineness", "Chip Genuineness",
                         LibreSCRS::Plugin::statusToString(secStatus.overallGenuineness));

            for (const auto& check : secStatus.checks) {
                std::string val{LibreSCRS::Plugin::statusToString(check.status)};
                if (!check.detail.empty())
                    val += " (" + check.detail + ")";
                if (!check.errorDetail.empty())
                    val += " [" + check.errorDetail + "]";
                addTextField(g, check.checkId, check.label, val);
            }

            emitGroup(std::move(g));
        }

        // Install SM filter so PKI fallback plugins get SM wrapping transparently
        conn.setTransmitFilter([this, filterKey = key](const smartcard::APDUCommand& cmd) {
            std::lock_guard lock(mtx);
            auto it = sessions.find(filterKey);
            if (it == sessions.end() || !it->second.emrTDCard)
                return smartcard::APDUResponse{{}, 0x69, 0x82};
            return it->second.emrTDCard->transmitSecureAPDU(cmd);
        });

        return data;
    }

public:
    void clearCredentials(LibreSCRS::SmartCard::CardSession& cardSession) noexcept override
    {
        try {
            const auto mapKey = makeSessionKey(cardSession);
            std::lock_guard lock(mtx);
            sessions.erase(mapKey);
        } catch (...) {
            // clearCredentials is noexcept — swallow any failure while
            // computing the session key or taking the mutex. The lock_guard
            // destructor itself cannot throw, so the map stays consistent.
        }
    }

    void setCredentials(LibreSCRS::SmartCard::CardSession& cardSession, std::string_view key,
                        const LibreSCRS::Secure::String& value) override
    {
        const auto mapKey = makeSessionKey(cardSession);
        std::lock_guard lock(mtx);
        auto& session = sessions[mapKey];
        // Materialise the secret string_view into a local std::string; the
        // EMRTD crypto paths below consume std::string for doc-number / DOB /
        // expiry / CAN. These buffers live on SessionContext and are cleared
        // via clearCredentials() on card removal.
        std::string valueStr{value.view()};
        if (key == "can") {
            session.credentials = std::move(valueStr);
            session.pendingDocNum.clear();
            session.pendingDob.clear();
            session.pendingExpiry.clear();
        } else if (key == "mrz_doc_number") {
            session.pendingDocNum = std::move(valueStr);
            trySetMRZ(session);
        } else if (key == "mrz_dob") {
            session.pendingDob = std::move(valueStr);
            trySetMRZ(session);
        } else if (key == "mrz_expiry") {
            session.pendingExpiry = std::move(valueStr);
            trySetMRZ(session);
        }
    }

private:
    static void trySetMRZ(SessionContext& session)
    {
        if (!session.pendingDocNum.empty() && !session.pendingDob.empty() && !session.pendingExpiry.empty()) {
            session.credentials = emrtd::MRZData{session.pendingDocNum, session.pendingDob, session.pendingExpiry};
        }
    }

    mutable std::mutex mtx;
    mutable std::map<SessionKey, SessionContext> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(EMRTDCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
