// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Auth/PaceSecretKind.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/Plugin/SecurityCheck.h>
#include <LibreSCRS/Plugin/SessionKey.h>
#include <LibreSCRS/Secure/Buffer.h>
#include <LibreSCRS/Secure/String.h>
#include <LibreSCRS/SecureChannel/BacParams.h>
#include <LibreSCRS_internal/SecureChannel/ISecureChannel.h>
#include <LibreSCRS_internal/SecureChannel/PlainChannel.h>
#include <LibreSCRS_internal/SecureChannel/SessionKeys.h>
#include <LibreSCRS_internal/SecureChannel/detail/ChannelStateMutator.h>
#include <LibreSCRS/SmartCard/AppletAid.h>
#include <LibreSCRS_internal/SmartCard/ActiveChannelHolderInternal.h>
#include <LibreSCRS/SmartCard/CardSession.h>
#include <LibreSCRS/SmartCard/SmProtocolRequest.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>

#include <active_auth.h>
#include <apdu.h>
#include <chip_auth.h>
#include <crypto_utils.h>
#include <data_group.h>
#include <date_format.h>
#include <emrtd_card.h>
#include <emrtd_types.h>
#include <pace.h>
#include <passive_auth.h>
#include <pcsc_connection.h>
#include <smartcard/secure_buffer.h>

#include <algorithm>
#include <compare>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <map>
#include <mutex>
#include <optional>
#include <span>
#include <string>
#include <variant>

#include "manifest.h" // generated by librescrs_add_plugin

namespace {

// 4.0 hardening: pluginId / displayName / capabilities / kAtrs come
// from the per-plugin manifest.json via the generated manifest.h header.
// eMRTD passports never advertise via ATR — the applet is detected by
// SELECT FILE on a live session, so kAtrs is intentionally empty.

// Format MRZ date YYMMDD → DD.MM.YYYY.
// For DOB: 2-digit year mapped to past (20xx if ≤ current year, else 19xx).
// For DOE: 2-digit year mapped to future (19xx only if > current year + 20).
std::string formatMRZDate(const std::string& yymmdd, bool isExpiry = false)
{
    if (yymmdd.size() != 6)
        return yymmdd;
    std::string yy = yymmdd.substr(0, 2);
    std::string mm = yymmdd.substr(2, 2);
    std::string dd = yymmdd.substr(4, 2);
    int y = std::stoi(yy);
    int fullYear;
    if (isExpiry) {
        // Expiry dates are in the near future — use 20xx unless obviously wrong
        fullYear = (y + 2000 > 2080) ? 1900 + y : 2000 + y;
    } else {
        // Birth dates are in the past — use 19xx if 20xx would be in the future
        auto now = std::time(nullptr);
        struct tm tmBuf{};
        localtime_r(&now, &tmBuf);
        int currentYY = (tmBuf.tm_year + 1900) % 100;
        fullYear = (y > currentYY) ? 1900 + y : 2000 + y; // NOLINT(readability-magic-numbers)
    }
    return dd + "." + mm + "." + std::to_string(fullYear);
}

// Plugin-local cleansing MRZ aggregate. F2: SessionContext must not retain
// raw secret bytes in plain std::string fields; wrap the three MRZ inputs
// in Secure::String so erase/overwrite paths zeroise the storage. The
// upstream emrtd::MRZData (lib/emrtd/src/emrtd_types.h) keeps its
// std::string fields for compatibility with the pre-4.0 BAC/PACE crypto
// callers — this struct is the only plugin-side carrier.
struct SecureMRZData
{
    LibreSCRS::Secure::String documentNumber;
    LibreSCRS::Secure::String dateOfBirth;  // YYMMDD
    LibreSCRS::Secure::String dateOfExpiry; // YYMMDD
};

// Compute the PACE MRZ-derived password via the canonical
// emrtd::crypto::detail::buildMrzInformation (mrzInfo = paddedDocNo + cd + DOB
// + cd + DOE + cd, BSI TR-03110) — the same construction BAC hashes for
// K_seed, so the two protocols can never drift.
//
// Secure::String's adopt-and-cleanse rvalue ctor copies the scratch into
// cleansing storage and zeroes the source on every exit path (incl.
// exceptions), so no PinStringScrubber is needed here.
LibreSCRS::Secure::String buildMrzInfo(std::string_view docNumber, std::string_view dob, std::string_view doe)
{
    std::string scratch = emrtd::crypto::detail::buildMrzInformation(docNumber, dob, doe);
    return LibreSCRS::Secure::String{std::move(scratch)};
}

struct SessionContext
{
    std::optional<std::variant<SecureMRZData, LibreSCRS::Secure::String>> credentials;
    LibreSCRS::Secure::String pendingDocNum;
    LibreSCRS::Secure::String pendingDob;
    LibreSCRS::Secure::String pendingExpiry;
    /// Discovery-probe verdict on plain LDS readability. On the contact
    /// interface of dual-interface documents the LDS carries the "Always"
    /// access condition, so EF.COM reads succeed without PACE; on the
    /// contactless interface the same read fails (6982) until PACE runs.
    /// Tri-state via the paired flag: an unprobed session keeps today's
    /// conservative SM activation.
    bool plainProbeDone{false};
    bool plainLdsReadable{false};
};

// Per-session state-map key + factory — the sanctioned plugin-support shape
// shared with the other CardPlugin implementations.
using LibreSCRS::Plugin::makeSessionKey;
using LibreSCRS::Plugin::SessionKey;

LibreSCRS::SmartCard::AppletAid makeEmrtdAid()
{
    return LibreSCRS::SmartCard::AppletAid{emrtd::EMRTD_AID[0], emrtd::EMRTD_AID[1], emrtd::EMRTD_AID[2],
                                           emrtd::EMRTD_AID[3], emrtd::EMRTD_AID[4], emrtd::EMRTD_AID[5],
                                           emrtd::EMRTD_AID[6]};
}

class EMRTDCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    EMRTDCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::emrtd::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::emrtd::kDisplayName},
                    /*priority=*/800);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::emrtd::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::emrtd::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            const auto key = makeSessionKey(session);
            {
                // New card insert on this reader: drop the state of EVERY
                // predecessor generation (generations are monotonic, so any
                // other entry under this reader name belongs to a dead
                // session). Keeps the per-session map bounded on hosts that
                // never call clearCredentials on dying sessions.
                std::lock_guard lock(mtx);
                std::erase_if(sessions, [&key](const auto& kv) { return kv.first.readerName == key.readerName; });
            }

            // One PC/SC transaction spans the applet SELECT and the probe so
            // no other client's APDUs can interleave between them and skew
            // the verdict. No plugin lock is held across card I/O: a wedged
            // transmit must not stall other sessions' activationProfile /
            // setCredentials calls.
            LibreSCRS::SmartCard::Internal::CardTransaction tx(conn);

            // SELECT eMRTD applet by AID (P2=0x0C: no FCI response)
            auto response = conn.transmit(LibreSCRS::SmartCard::Internal::selectByAID(
                {emrtd::EMRTD_AID, emrtd::EMRTD_AID + emrtd::EMRTD_AID_LEN}, 0x0C));
            if (!response.isSuccess())
                return false;

            // Interface probe: a plain EF.COM read succeeding right here is
            // the empirical signal that this session's interface exposes the
            // LDS without PACE (contact "Always" access) — cached for the
            // session lifetime (a new card insert re-probes). A transport
            // fault leaves the verdict UNKNOWN (conservative SM default, a
            // later re-insert re-probes); only completed probe I/O records a
            // positive readable/not-readable fact.
            bool probeDone = false;
            bool readable = false;
            try {
                LibreSCRS::SecureChannel::PlainChannel probeChannel(conn, makeEmrtdAid());
                emrtd::EMRTDCard probeCard(probeChannel);
                readable = !probeCard.readCOM().empty();
                probeDone = true;
            } catch (...) {
                // verdict stays unknown
            }
            if (probeDone) {
                std::lock_guard lock(mtx);
                auto& ctx = sessions[key];
                ctx.plainProbeDone = true;
                ctx.plainLdsReadable = readable;
            }
            return true;
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto data = readCardImpl(cardSession, std::move(onGroup));
            for (const auto& g : data.groups) {
                if (g.groupKey == "error")
                    return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                            std::string{"eMRTD authentication failed"});
            }
            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eMRTD readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eMRTD readCard failed (unknown error)"});
        }
    }

    /// @brief Declare the SM activation the upcoming read needs, derived from
    ///        the plugin's per-session credential store and the session's
    ///        installed credential provider.
    ///
    /// Cases, mirroring the host integrations:
    ///  - Deposited MRZ → PACE (MRZ) with BAC fallback (classical passports).
    ///  - Deposited CAN → PACE (CAN).
    ///  - Empty store + a credential provider installed (broker/agent):
    ///    when the discovery probe proved the LDS plain-readable on this
    ///    interface (contact "Always" access) → plain, no CAN prompt;
    ///    otherwise → PACE (CAN); the provider supplies the CAN on cache
    ///    miss. PACE protects the contactless interface — the contact
    ///    interface of dual-interface documents reads without it.
    ///  - Empty store + no provider (host discovery first call) → plain: the
    ///    wrapper performs no activation and @ref doReadCard either reads the
    ///    LDS directly (plain-readable interface) or returns the
    ///    `auth_required` probe.
    ///
    /// Lock ordering: the plugin store is read under @ref mtx, which is then
    /// released before querying @ref CardSession::hasCredentialProvider (that
    /// call locks the session mutex). Holding both at once would invert the
    /// lock order other code paths take.
    LibreSCRS::Plugin::ActivationProfile
    activationProfile(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        LibreSCRS::Plugin::ActivationProfile p;
        p.aid = makeEmrtdAid();

        const auto key = makeSessionKey(cardSession);
        bool haveCan = false;
        bool haveMrz = false;
        bool plainReadable = false;
        {
            std::lock_guard lock(mtx);
            auto it = sessions.find(key);
            if (it != sessions.end()) {
                if (it->second.credentials) {
                    // SessionContext::credentials is variant<SecureMRZData, Secure::String>;
                    // the MRZ alternative drives PACE (MRZ), the other (Secure::String)
                    // carries the CAN.
                    haveMrz = std::holds_alternative<SecureMRZData>(*it->second.credentials);
                    haveCan = !haveMrz;
                }
                plainReadable = it->second.plainProbeDone && it->second.plainLdsReadable;
            }
        }

        if (haveMrz) {
            p.primary = LibreSCRS::SmartCard::PaceRequest{LibreSCRS::Auth::PaceSecretKind::Mrz};
            p.allowBacFallback = true;
            return p;
        }
        if (haveCan) {
            p.primary = LibreSCRS::SmartCard::PaceRequest{LibreSCRS::Auth::PaceSecretKind::Can};
            return p;
        }
        // Empty store: a broker/agent path (provider installed) activates
        // PACE (CAN) — the provider supplies the CAN on cache miss — unless
        // the discovery probe proved the LDS plain-readable on this
        // interface (contact "Always" access) AND no SM tunnel is live: then
        // no activation is needed and no CAN is ever prompted. With a live
        // SM tunnel the PACE profile is kept even on a plain-readable
        // interface — the activation walk's wrapped SELECT re-binds the
        // shared tunnel to this applet (another plugin may have moved it),
        // which a plain profile would silently skip.
        const bool plainNow = plainReadable && !cardSession.activatedProtocol().has_value();
        if (cardSession.hasCredentialProvider() && !plainNow) {
            p.primary = LibreSCRS::SmartCard::PaceRequest{LibreSCRS::Auth::PaceSecretKind::Can};
            return p;
        }
        return LibreSCRS::Plugin::ActivationProfile::plain();
    }

    /// @brief Push any deposited CAN/MRZ secret into the session credential
    ///        cache so the activation walk finds it instead of re-prompting.
    ///
    /// A no-op when the store is empty (the broker/agent path, where the
    /// walk falls through to the installed credential provider). Preserves
    /// the BAC-input + PACE (MRZ) `mrzInfo` construction and the
    /// adopt-and-cleanse @ref LibreSCRS::Secure::String semantics that the
    /// in-band deposit used previously.
    void seedCredentials(LibreSCRS::SmartCard::CardSession& cardSession,
                         const LibreSCRS::Plugin::ActivationProfile& /*profile*/) const override
    {
        const auto key = makeSessionKey(cardSession);
        std::optional<std::variant<SecureMRZData, LibreSCRS::Secure::String>> creds;
        {
            std::lock_guard lock(mtx);
            auto it = sessions.find(key);
            if (it != sessions.end() && it->second.credentials)
                creds = it->second.credentials;
        }
        if (!creds)
            return;

        if (auto* can = std::get_if<LibreSCRS::Secure::String>(&*creds)) {
            cardSession.setPaceSecret(LibreSCRS::Auth::PaceSecretKind::Can, *can);
        } else if (auto* mrz = std::get_if<SecureMRZData>(&*creds)) {
            // Push BAC inputs (the fallback path). The Secure::String copy
            // ctor cleanses each per-copy block, so passing copies of the
            // session-held secret fields into the BAC slot retains cleansing
            // semantics throughout the lifetime of bacIn.
            LibreSCRS::SecureChannel::BacInput bacIn;
            bacIn.documentNumber = mrz->documentNumber;
            bacIn.dateOfBirth = mrz->dateOfBirth;
            bacIn.dateOfExpiry = mrz->dateOfExpiry;
            cardSession.setBacInput(std::move(bacIn));
            // Push PACE_MRZ password (mrzInfo encoding) — used if EF.CardAccess
            // is present and PACE is supported. buildMrzInfo returns a
            // Secure::String built via the adopt-and-cleanse rvalue ctor; its
            // scratch buffer is scrubbed on every exit path.
            cardSession.setPaceSecret(
                LibreSCRS::Auth::PaceSecretKind::Mrz,
                buildMrzInfo(mrz->documentNumber.view(), mrz->dateOfBirth.view(), mrz->dateOfExpiry.view()));
        }
    }

private:
    LibreSCRS::Plugin::CardData readCardImpl(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        LibreSCRS::Plugin::CardData data;
        data.cardType = "emrtd";

        auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
            if (onGroup)
                onGroup(data.cardType, group);
            data.groups.push_back(std::move(group));
        };

        // The readCard NVI wrapper has already consulted activationProfile():
        // a profile that requires activation seeded credentials and acquired
        // the SM channel before dispatching here. So an active channel means
        // "read over it"; no active channel means the profile was plain —
        // either a plain-readable interface (contact) or the host discovery
        // first call, which falls back to the auth_required probe below.
        auto* channel = LibreSCRS::SmartCard::Internal::ActiveChannelAccessor::active(cardSession);
        std::optional<LibreSCRS::SmartCard::ActiveChannelHolder> plainHolder;
        bool plainRead = false;

        if (!LibreSCRS::SmartCard::Internal::ActiveChannelAccessor::activatedProtocol(cardSession).has_value()) {
            // No live SM tunnel. When the discovery probe proved the LDS
            // plain-readable on this interface (contact "Always" access),
            // acquire a plain holder for the whole read: activateChannelFor
            // supplies the PC/SC transaction, the applet SELECT, and a
            // correctly bound plain channel in one move — and thereby also
            // heals a stale plain channel another plugin left installed
            // (bound to its own applet), which would otherwise be read
            // blindly. Unknown or not-readable verdicts keep today's paths
            // (SM activation with a provider, auth_required probe without).
            bool plainReadable = false;
            {
                std::lock_guard lock(mtx);
                auto it = sessions.find(makeSessionKey(cardSession));
                plainReadable = it != sessions.end() && it->second.plainProbeDone && it->second.plainLdsReadable;
            }
            if (plainReadable) {
                // From here on the pre-acquire channel pointer is dead: the
                // acquire below may CLOSE or REPLACE a previously installed
                // channel (destroying the object it pointed at), so any
                // non-committed attempt must fall through to the
                // auth_required probe with NO channel — never read over the
                // stale pointer.
                channel = nullptr;
                if (auto holder = cardSession.activateChannelFor(makeEmrtdAid(), LibreSCRS::CancelToken{})) {
                    if (auto* held = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(*holder);
                        held != nullptr) {
                        // Corroborate before committing: the probe verdict
                        // may be stale (card swapped mid-session). An empty
                        // COM read releases the holder and falls back to the
                        // auth_required probe below.
                        emrtd::EMRTDCard probeCard(*held);
                        if (!probeCard.readCOM().empty()) {
                            plainHolder = std::move(*holder);
                            channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(*plainHolder);
                            plainRead = true;
                        }
                    }
                }
            }
        }

        if (channel == nullptr) {
            // No SM channel — discovery probe. Reads EF.CardAccess via the raw
            // PCSC connection because no SM is active yet; this query informs
            // the host UI which credential type to prompt for.
            LibreSCRS::Plugin::CardFieldGroup authGroup;
            authGroup.groupKey = "auth_required";
            authGroup.groupLabel = "Authentication Required";

            auto addText = [&](const std::string& key, const std::string& label, const std::string& val) {
                authGroup.fields.push_back({key, label, LibreSCRS::Plugin::FieldType::Text, {val.begin(), val.end()}});
            };

            addText("status", "Status", "MRZ or CAN required");

            bool paceSupported = false;
            std::vector<std::string> paceOids;
            try {
                LibreSCRS::SmartCard::Internal::APDUCommand selectCmd{
                    0x00, 0xA4, 0x04, 0x0C, {emrtd::EMRTD_AID, emrtd::EMRTD_AID + emrtd::EMRTD_AID_LEN}, 0, false};
                conn.transmit(selectCmd);

                LibreSCRS::SmartCard::Internal::APDUCommand readCA{
                    0x00, 0xB0, static_cast<uint8_t>(0x80 | emrtd::SFID_CARD_ACCESS), 0x00, {}, 0x00, true};
                auto caResp = conn.transmit(readCA);
                if (caResp.isSuccess() && !caResp.data.empty()) {
                    paceOids = emrtd::crypto::parseCardAccess(caResp.data);
                    paceSupported = !paceOids.empty();
                }
            } catch (...) {
            }

            addText("pace_supported", "PACE Supported", paceSupported ? "true" : "false");
            if (!paceOids.empty()) {
                std::string oids;
                for (const auto& oid : paceOids) {
                    if (!oids.empty())
                        oids += ", ";
                    oids += oid;
                }
                addText("pace_oids", "PACE Algorithms", oids);
            }

            data.groups.push_back(std::move(authGroup));
            return data;
        }

        // SM channel established by the wrapper — read over it.
        emrtd::EMRTDCard card(*channel);

        // Auth method label for the security_status / presence group, derived
        // from the protocol the wrapper actually activated. The lock-free,
        // owner-tolerant accessor is required here: doReadCard runs while the
        // base readCard wrapper still holds the ActiveChannelHolder, so the
        // public CardSession::activatedProtocol() (which locks the non-recursive
        // session mutex on the owner thread) would self-deadlock.
        std::string authMethodLabel = "BAC";
        if (plainRead) {
            // Interface-neutral honesty: the readability probe proves plain
            // access, not the physical interface (a PACE-less legacy document
            // can be plain-readable over RF too).
            authMethodLabel = "None (plain read)";
        } else if (auto proto = LibreSCRS::SmartCard::Internal::ActiveChannelAccessor::activatedProtocol(cardSession)) {
            if (const auto* pace = std::get_if<LibreSCRS::SmartCard::PaceRequest>(&*proto))
                authMethodLabel =
                    (pace->secretKind == LibreSCRS::Auth::PaceSecretKind::Can) ? "PACE (CAN)" : "PACE (MRZ)";
        }

        // --- ICAO-compliant reading flow ---

        auto addTextField = [](LibreSCRS::Plugin::CardFieldGroup& g, std::string_view key, std::string_view label,
                               std::string_view val) {
            if (!val.empty())
                g.fields.push_back({std::string{key}, std::string{label}, LibreSCRS::Plugin::FieldType::Text,
                                    std::vector<uint8_t>{val.begin(), val.end()}});
        };

        // 1. Read COM → emit presence group
        auto dgList = card.readCOM();
        {
            LibreSCRS::Plugin::CardFieldGroup g;
            g.groupKey = "presence";
            g.groupLabel = "Data Groups Present";
            std::string dgListStr;
            for (int dg : dgList) {
                if (!dgListStr.empty())
                    dgListStr += ", ";
                dgListStr += "DG" + std::to_string(dg);
            }
            addTextField(g, "data_groups", "Data Groups", dgListStr);
            addTextField(g, "auth_method", "Authentication Method", authMethodLabel);
            emitGroup(std::move(g));
        }

        // 2. Read SOD → store raw bytes
        auto sodRaw = card.readSOD();

        // 3. Parse SOD → get authoritative DG list from hash entries
        std::vector<int> authoritativeDGs;
        std::optional<emrtd::crypto::SODContent> sodContent;
        if (sodRaw) {
            sodContent = emrtd::crypto::parseSOD(*sodRaw);
            if (sodContent) {
                for (const auto& [dgNum, hash] : sodContent->dgHashes)
                    authoritativeDGs.push_back(dgNum);
                std::sort(authoritativeDGs.begin(), authoritativeDGs.end());
            }
        }
        // Fall back to COM list if SOD parsing failed
        if (authoritativeDGs.empty())
            authoritativeDGs = dgList;

        bool hasDG14 = std::find(authoritativeDGs.begin(), authoritativeDGs.end(), 14) != authoritativeDGs.end();
        bool hasDG15 = std::find(authoritativeDGs.begin(), authoritativeDGs.end(), 15) != authoritativeDGs.end();

        // Storage for raw DG bytes (for passive auth)
        std::map<int, std::vector<uint8_t>> dgRawData;

        // 4. If DG14 present → Chip Authentication → upgrade SM
        emrtd::crypto::ChipAuthResult caResult;
        caResult.chipAuthentication = emrtd::crypto::ChipAuthResult::NOT_PERFORMED;
        caResult.activeAuthentication = emrtd::crypto::ChipAuthResult::NOT_PERFORMED;

        if (hasDG14) {
            auto dg14Result = card.readDataGroupSafe(14);
            if (dg14Result.status == emrtd::DGReadStatus::OK && !dg14Result.data.empty()) {
                dgRawData[14] = dg14Result.data;
                // Genuineness protocols run only over SM: Chip Authentication's
                // session-key replacement is a documented no-op on a plain
                // channel, so any verdict there would be unverifiable. The raw
                // DG14 bytes above feed passive authentication whenever EF.SOD
                // is itself readable; documents that SM-gate EF.SOD in plain
                // skip PA entirely and report it NOT_PERFORMED.
                if (!plainRead)
                    caResult = emrtd::crypto::performChipAuth(*channel, dg14Result.data);
                if (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::PASSED && caResult.newSessionKeys) {
                    // Promote channel SM keys to CA-derived keys. The
                    // public-channel SessionKeys carrier composes
                    // cleansing Secure::Buffer fields; the emrtd::crypto
                    // vectors are cleansed by their own destructor when
                    // caResult drops, so the post-copy bytes never
                    // persist uncleansed.
                    LibreSCRS::SecureChannel::SessionKeys newKeys;
                    newKeys.encKey =
                        LibreSCRS::Secure::Buffer{std::span<const std::uint8_t>{caResult.newSessionKeys->encKey}};
                    newKeys.macKey =
                        LibreSCRS::Secure::Buffer{std::span<const std::uint8_t>{caResult.newSessionKeys->macKey}};
                    newKeys.ssc =
                        LibreSCRS::Secure::Buffer{std::span<const std::uint8_t>{caResult.newSessionKeys->ssc}};
                    newKeys.cipher = (caResult.newAlgorithm == emrtd::crypto::SMAlgorithm::DES3)
                                         ? LibreSCRS::SecureChannel::SmCipher::Des3
                                         : LibreSCRS::SecureChannel::SmCipher::Aes;
                    LibreSCRS::SecureChannel::detail::ChannelStateMutator::replaceKeys(*channel, std::move(newKeys));
                }
            }
        }

        // 5. If no DG14 but DG15 present → Active Authentication
        if (caResult.chipAuthentication != emrtd::crypto::ChipAuthResult::PASSED && hasDG15) {
            auto dg15Result = card.readDataGroupSafe(15);
            if (dg15Result.status == emrtd::DGReadStatus::OK && !dg15Result.data.empty()) {
                dgRawData[15] = dg15Result.data;
                // Same SM-only rule as Chip Authentication above: no
                // genuineness verdict from a plain channel.
                if (!plainRead) {
                    auto aaResult = emrtd::crypto::performActiveAuth(*channel, dg15Result.data);
                    caResult.activeAuthentication = aaResult.activeAuthentication;
                    if (aaResult.errorDetail.size() > caResult.errorDetail.size())
                        caResult.errorDetail = aaResult.errorDetail;
                }
            }
        }

        // 6. Read remaining DGs and emit groups
        for (int dg : authoritativeDGs) {
            // Skip DG14/DG15 — already read above
            if (dg == 14 || dg == 15)
                continue;

            auto dgResult = card.readDataGroupSafe(dg);
            if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                dgRawData[dg] = dgResult.data;
            }

            // Parse and emit based on DG number
            switch (dg) {
            case 1: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[1] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg1) {
                    {
                        LibreSCRS::Plugin::CardFieldGroup g;
                        g.groupKey = "personal";
                        g.groupLabel = "Personal Data (DG1)";
                        addTextField(g, "surname", "Surname", parsed.dg1->surname);
                        addTextField(g, "given_names", "Given Names", parsed.dg1->givenNames);
                        addTextField(g, "nationality", "Nationality", parsed.dg1->nationality);
                        addTextField(g, "date_of_birth", "Date of Birth", formatMRZDate(parsed.dg1->dateOfBirth));
                        addTextField(g, "sex", "Sex", parsed.dg1->sex);
                        emitGroup(std::move(g));
                    }
                    {
                        LibreSCRS::Plugin::CardFieldGroup g;
                        g.groupKey = "document";
                        g.groupLabel = "Document Data (DG1)";
                        addTextField(g, "document_number", "Document Number", parsed.dg1->documentNumber);
                        addTextField(g, "document_code", "Document Code", parsed.dg1->documentCode);
                        addTextField(g, "issuing_state", "Issuing State", parsed.dg1->issuingState);
                        addTextField(g, "date_of_expiry", "Date of Expiry",
                                     formatMRZDate(parsed.dg1->dateOfExpiry, true));
                        addTextField(g, "personal_number", "Personal Number", parsed.dg1->optionalData);
                        emitGroup(std::move(g));
                    }
                }
                break;
            }
            case 2: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[2] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg2) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "photo";
                    g.groupLabel = "Photo";
                    g.fields.push_back({"photo", "Photo", LibreSCRS::Plugin::FieldType::Photo, parsed.dg2->imageData});
                    emitGroup(std::move(g));
                }
                break;
            }
            case 3: {
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "biometric_fingerprint";
                g.groupLabel = "Fingerprint (DG3)";
                if (dgResult.status == emrtd::DGReadStatus::ACCESS_DENIED) {
                    addTextField(g, "access", "Access", "EAC required");
                } else if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                    g.fields.push_back(
                        {"fingerprint", "Fingerprint", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                } else {
                    break; // NOT_PRESENT or ERROR — skip
                }
                emitGroup(std::move(g));
                break;
            }
            case 4: {
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "biometric_iris";
                g.groupLabel = "Iris (DG4)";
                if (dgResult.status == emrtd::DGReadStatus::ACCESS_DENIED) {
                    addTextField(g, "access", "Access", "EAC required");
                } else if (dgResult.status == emrtd::DGReadStatus::OK && !dgResult.data.empty()) {
                    g.fields.push_back({"iris", "Iris", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                } else {
                    break; // NOT_PRESENT or ERROR — skip
                }
                emitGroup(std::move(g));
                break;
            }
            case 5: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                // DG5 contains a portrait image — emit raw as photo
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "portrait";
                g.groupLabel = "Portrait (DG5)";
                g.fields.push_back({"portrait", "Portrait", LibreSCRS::Plugin::FieldType::Photo, dgResult.data});
                emitGroup(std::move(g));
                break;
            }
            case 7: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[7] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg7) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "signature";
                    g.groupLabel = "Signature / Mark (DG7)";
                    g.fields.push_back(
                        {"signature", "Signature", LibreSCRS::Plugin::FieldType::Photo, parsed.dg7->imageData});
                    emitGroup(std::move(g));
                }
                break;
            }
            case 11: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[11] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg11) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "additional";
                    g.groupLabel = "Additional Personal Data (DG11)";
                    addTextField(g, "full_name", "Full Name", parsed.dg11->fullName);
                    addTextField(g, "other_names", "Other Names", parsed.dg11->otherNames);
                    addTextField(g, "personal_number", "Personal Number", parsed.dg11->personalNumber);
                    addTextField(g, "place_of_birth", "Place of Birth", parsed.dg11->placeOfBirth);
                    addTextField(g, "address", "Address", parsed.dg11->address);
                    addTextField(g, "telephone", "Telephone", parsed.dg11->telephone);
                    addTextField(g, "profession", "Profession", parsed.dg11->profession);
                    addTextField(g, "title", "Title", parsed.dg11->title);
                    addTextField(g, "custody_info", "Custody Information", parsed.dg11->custodyInfo);
                    if (!g.fields.empty())
                        emitGroup(std::move(g));
                }
                break;
            }
            case 12: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                std::map<int, std::vector<uint8_t>> singleDG;
                singleDG[12] = dgResult.data;
                auto parsed = emrtd::parseDataGroups(singleDG);
                if (parsed.dg12) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "document_extra";
                    g.groupLabel = "Issuing Information (DG12)";
                    addTextField(g, "issuing_authority", "Issuing Authority", parsed.dg12->issuingAuthority);
                    std::string doi = parsed.dg12->dateOfIssue;
                    if (doi.size() == 8)
                        doi = LibreSCRS::SmartCard::Internal::formatDateYMD(doi);
                    else if (doi.size() == 6)
                        doi = formatMRZDate(doi, true);
                    addTextField(g, "date_of_issue", "Date of Issue", doi);
                    addTextField(g, "endorsements", "Endorsements", parsed.dg12->endorsements);
                    addTextField(g, "tax_exit", "Tax/Exit Requirements", parsed.dg12->taxExitRequirements);
                    if (!g.fields.empty())
                        emitGroup(std::move(g));
                }
                break;
            }
            case 13: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                LibreSCRS::Plugin::CardFieldGroup g;
                g.groupKey = "national";
                g.groupLabel = "National Data (DG13)";
                g.fields.push_back(
                    {"national_data", "National Data", LibreSCRS::Plugin::FieldType::Binary, dgResult.data});
                emitGroup(std::move(g));
                break;
            }
            case 16: {
                if (dgResult.status != emrtd::DGReadStatus::OK || dgResult.data.empty())
                    break;
                auto contacts = emrtd::EMRTDCard::parseDG16(dgResult.data);
                if (!contacts.empty()) {
                    LibreSCRS::Plugin::CardFieldGroup g;
                    g.groupKey = "contacts";
                    g.groupLabel = "Persons to Notify (DG16)";
                    int idx = 0;
                    for (const auto& contact : contacts) {
                        std::string prefix = (contacts.size() > 1) ? "contact_" + std::to_string(idx) + "_" : "";
                        addTextField(g, prefix + "name", "Name", contact.name);
                        addTextField(g, prefix + "telephone", "Telephone", contact.telephone);
                        addTextField(g, prefix + "address", "Address", contact.address);
                        ++idx;
                    }
                    emitGroup(std::move(g));
                }
                break;
            }
            default:
                break;
            }
        }

        // 7. Passive Authentication
        LibreSCRS::Plugin::SecurityStatus secStatus;

        if (sodRaw && !dgRawData.empty()) {
            // CSCA trust store path from env var
            std::string trustStorePath;
            if (const char* envPath = std::getenv("LIBRESCRS_CSCA_STORE"))
                trustStorePath = envPath;

            auto paResult = emrtd::crypto::performPassiveAuth(*sodRaw, dgRawData, trustStorePath);

            // SOD signature check
            {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_sod_signature";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "SOD Digital Signature";
                check.status = (paResult.sodSignature == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (paResult.sodSignature == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                if (!paResult.dscSubject.empty())
                    check.detail = "DSC: " + paResult.dscSubject;
                secStatus.checks.push_back(std::move(check));
            }

            // CSCA chain check
            {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_csca_chain";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "CSCA Certificate Chain";
                check.status = (paResult.cscaChain == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (paResult.cscaChain == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                if (trustStorePath.empty())
                    check.detail = "No CSCA trust store configured";
                secStatus.checks.push_back(std::move(check));
            }

            // Per-DG hash checks
            for (const auto& [dgNum, status] : paResult.dgHashes) {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_dg" + std::to_string(dgNum) + "_hash";
                check.category = LibreSCRS::Plugin::SecurityCategory::DataIntegrity;
                check.label = "DG" + std::to_string(dgNum) + " Hash (" + paResult.hashAlgorithm + ")";
                check.status = (status == emrtd::crypto::PAResult::PASSED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                               : (status == emrtd::crypto::PAResult::FAILED)
                                   ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                                   : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
                secStatus.checks.push_back(std::move(check));
            }

            if (!paResult.errorDetail.empty()) {
                LibreSCRS::Plugin::SecurityCheck check;
                check.checkId = "pa_error";
                check.category = LibreSCRS::Plugin::SecurityCategory::Authenticity;
                check.label = "Passive Authentication";
                check.status = LibreSCRS::Plugin::SecurityCheck::Status::Failed;
                check.errorDetail = paResult.errorDetail;
                secStatus.checks.push_back(std::move(check));
            }
        }

        // Chip Authentication check
        {
            LibreSCRS::Plugin::SecurityCheck check;
            check.checkId = "chip_auth";
            check.category = LibreSCRS::Plugin::SecurityCategory::Genuineness;
            check.label = "Chip Authentication";
            check.status = (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::PASSED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                           : (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::FAILED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                           : (caResult.chipAuthentication == emrtd::crypto::ChipAuthResult::NOT_SUPPORTED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::NotSupported
                               : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
            if (!caResult.protocol.empty())
                check.detail = caResult.protocol;
            secStatus.checks.push_back(std::move(check));
        }

        // Active Authentication check
        {
            LibreSCRS::Plugin::SecurityCheck check;
            check.checkId = "active_auth";
            check.category = LibreSCRS::Plugin::SecurityCategory::Genuineness;
            check.label = "Active Authentication";
            check.status = (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::PASSED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Passed
                           : (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::FAILED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::Failed
                           : (caResult.activeAuthentication == emrtd::crypto::ChipAuthResult::NOT_SUPPORTED)
                               ? LibreSCRS::Plugin::SecurityCheck::Status::NotSupported
                               : LibreSCRS::Plugin::SecurityCheck::Status::NotPerformed;
            if (!caResult.errorDetail.empty())
                check.errorDetail = caResult.errorDetail;
            secStatus.checks.push_back(std::move(check));
        }

        secStatus.computeOverall();

        // 8. Emit security_status group
        {
            LibreSCRS::Plugin::CardFieldGroup g;
            g.groupKey = "security_status";
            g.groupLabel = "Security Verification";

            addTextField(g, "overall_integrity", "Data Integrity",
                         LibreSCRS::Plugin::statusToString(secStatus.overallIntegrity));
            addTextField(g, "overall_authenticity", "Data Authenticity",
                         LibreSCRS::Plugin::statusToString(secStatus.overallAuthenticity));
            addTextField(g, "overall_genuineness", "Chip Genuineness",
                         LibreSCRS::Plugin::statusToString(secStatus.overallGenuineness));

            for (const auto& check : secStatus.checks) {
                std::string val{LibreSCRS::Plugin::statusToString(check.status)};
                if (!check.detail.empty())
                    val += " (" + check.detail + ")";
                if (!check.errorDetail.empty())
                    val += " [" + check.errorDetail + "]";
                addTextField(g, check.checkId, check.label, val);
            }

            emitGroup(std::move(g));
        }

        // Holder destruction at scope exit ends the PC/SC transaction and
        // releases CardSession's sessionMutex. The PaceChannel itself remains
        // installed on CardSession's activeChannel slot so that subsequent
        // plugin activations (notably pkcs15-plugin sign on the same card)
        // take the wrapped-SELECT fast path through the same SM tunnel.
        return data;
    }

public:
    void clearCredentials(LibreSCRS::SmartCard::CardSession& cardSession) noexcept override
    {
        try {
            const auto mapKey = makeSessionKey(cardSession);
            std::lock_guard lock(mtx);
            auto it = sessions.find(mapKey);
            if (it == sessions.end())
                return;
            // Wipe the secrets but keep the interface-probe verdict: plain
            // LDS readability is a property of the reader interface, not a
            // credential, and losing it here would silently revert a contact
            // session to CAN prompting for the rest of its lifetime.
            const bool probeDone = it->second.plainProbeDone;
            const bool readable = it->second.plainLdsReadable;
            sessions.erase(it);
            if (probeDone) {
                auto& ctx = sessions[mapKey];
                ctx.plainProbeDone = true;
                ctx.plainLdsReadable = readable;
            }
        } catch (...) {
            // clearCredentials is noexcept — swallow any failure while
            // computing the session key or taking the mutex. The lock_guard
            // destructor itself cannot throw, so the map stays consistent.
        }
    }

    void setCredentials(LibreSCRS::SmartCard::CardSession& cardSession, std::string_view key,
                        const LibreSCRS::Secure::String& value) override
    {
        const auto mapKey = makeSessionKey(cardSession);
        std::lock_guard lock(mtx);
        auto& session = sessions[mapKey];
        // SessionContext now holds Secure::String for every secret field;
        // the inbound value copy-constructs into cleansing storage and the
        // pending fields are cleansed automatically on clear() / dtor /
        // session erase. No plain std::string is materialised here.
        if (key == "can") {
            session.credentials = value;
            session.pendingDocNum.clear();
            session.pendingDob.clear();
            session.pendingExpiry.clear();
        } else if (key == "mrz_doc_number") {
            session.pendingDocNum = value;
            trySetMRZ(session);
        } else if (key == "mrz_dob") {
            session.pendingDob = value;
            trySetMRZ(session);
        } else if (key == "mrz_expiry") {
            session.pendingExpiry = value;
            trySetMRZ(session);
        }
    }

private:
    static void trySetMRZ(SessionContext& session)
    {
        if (!session.pendingDocNum.empty() && !session.pendingDob.empty() && !session.pendingExpiry.empty()) {
            SecureMRZData mrz;
            mrz.documentNumber = std::move(session.pendingDocNum);
            mrz.dateOfBirth = std::move(session.pendingDob);
            mrz.dateOfExpiry = std::move(session.pendingExpiry);
            session.credentials = std::move(mrz);
            // After moving the secret bytes into the credentials variant,
            // explicitly clear the (now moved-from) pending slots to keep
            // the SessionContext snapshot consistent and to release the
            // residual pimpl handles.
            session.pendingDocNum.clear();
            session.pendingDob.clear();
            session.pendingExpiry.clear();
        }
    }

    mutable std::mutex mtx;
    mutable std::map<SessionKey, SessionContext> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(EMRTDCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
