#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# abi-snapshot.sh — capture / verify the LibreSCRS public C++ ABI surface.
#
# LibreMiddleware ships as a set of static archives (libLibreSCRS_*.a) plus
# the public PKCS#11 shared object (librescrs-pkcs11.so). The ABI surface
# that consumer SDK builds depend on is the demangled set of T-binding
# (global text, default-visible) symbols exported from each public archive,
# plus the dynamic-symbols list from the SO.
#
# This script generates a stable, sorted, human-readable text artefact
# checked into the tree at:
#   ci/abi/4.0-baseline.txt
#
# Use --check to compare a fresh build against the baseline; the script
# fails non-zero on any difference. Use --update to regenerate the baseline.
#
# Why text not abigail/abicompat: LibreSCRS-specific. The bulk of the API
# is plain C++20 value types + factories + builders — header-only or
# trivially inlined. abidiff against XML is overkill and obscures cosmetic
# diffs (typedef churn, unsigned-int vs size_t under different toolchains).
# A demangled T-symbol diff catches the cases that matter — function added
# / removed / signature changed — with a one-line review per change.
#
# Usage:
#   abi-snapshot.sh [--check|--update] [BUILD_DIR]
#
# Default action: --check. Default BUILD_DIR: build.

set -euo pipefail

# Force a deterministic, locale-independent sort so the baseline lines
# up byte-for-byte across developer machines and CI runners. Without
# LC_ALL=C, glibc's default UTF-8 collation interleaves alphabetic and
# punctuation differently than ASCII (e.g. en_US.UTF-8 sorts
# `…CancelSource const&)` before `…CancelSource&&)` while sr_RS sorts
# the other way), and any diff against the baseline is pure noise.
export LC_ALL=C

ACTION="check"
BUILD_DIR="build"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) ACTION="check"; shift ;;
        --update) ACTION="update"; shift ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) BUILD_DIR="$1"; shift ;;
    esac
done

if [[ ! -d "$BUILD_DIR" ]]; then
    echo "ERROR: build dir '$BUILD_DIR' not found" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BASELINE="${REPO_ROOT}/ci/abi/4.0-baseline.txt"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

snapshot="${SCRATCH}/snapshot.txt"

{
    echo "# LibreSCRS public ABI snapshot"
    echo "# Generated by ci/scripts/abi-snapshot.sh"
    echo "# Format: one demangled T-binding symbol per line, sorted; one"
    echo "# section per public archive / SO, header line '== <basename> =='."
    echo "# Re-generate with: ci/scripts/abi-snapshot.sh --update <build_dir>"
    echo "# Diff a fresh build against this baseline with: ci/scripts/abi-snapshot.sh --check"

    # Public static archives — T-binding only (global text). Internal
    # functions (anonymous-namespace, static, LIBRESCRS_INTERNAL) carry
    # 't' (lowercase, file-local) and are excluded by design.
    while IFS= read -r archive; do
        name="$(basename "$archive")"
        echo
        echo "== $name =="
        nm -U "$archive" 2>/dev/null \
            | awk '$2 == "T" { print $3 }' \
            | c++filt 2>/dev/null \
            | sort -u
    done < <(find "$BUILD_DIR" -name 'libLibreSCRS_*.a' | sort)

    # PKCS#11 shared object — dynamic symbols (T-binding) only.
    # PKCS#11 has a fixed C ABI (the C_* function table); we still
    # snapshot any C++ symbols that leak (should be zero — verified
    # by the SOVERSION'd .so's own visibility settings).
    while IFS= read -r so; do
        name="$(basename "$so")"
        echo
        echo "== $name =="
        # `--defined-only` is GNU-only; `-U` is portable.
        nm -D -U "$so" 2>/dev/null \
            | awk '$2 == "T" { print $3 }' \
            | c++filt 2>/dev/null \
            | sort -u
    done < <(find "$BUILD_DIR" -path "*/lib/pkcs11/librescrs-pkcs11.so.[0-9]*" -not -name "*.[0-9]" | sort | head -1)

} > "$snapshot"

case "$ACTION" in
    update)
        mkdir -p "$(dirname "$BASELINE")"
        cp "$snapshot" "$BASELINE"
        echo "Wrote ABI baseline: $BASELINE"
        wc -l "$BASELINE"
        ;;
    check)
        if [[ ! -f "$BASELINE" ]]; then
            echo "ERROR: baseline not found at $BASELINE" >&2
            echo "       Run 'ci/scripts/abi-snapshot.sh --update <build_dir>' to capture." >&2
            exit 2
        fi
        if diff -u "$BASELINE" "$snapshot" > "${SCRATCH}/abi-diff.txt"; then
            echo "ABI snapshot matches baseline ($(wc -l < "$BASELINE") lines)."
            exit 0
        else
            echo "ABI DRIFT detected vs $BASELINE:" >&2
            cat "${SCRATCH}/abi-diff.txt" >&2
            echo >&2
            echo "If this drift is intentional (a new public API addition or" >&2
            echo "an explicit breaking change for a major bump):" >&2
            echo "   ci/scripts/abi-snapshot.sh --update $BUILD_DIR" >&2
            exit 1
        fi
        ;;
esac
