// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <pcsc_connection.h>
#include <eu_vrc_card.h>
#include <eu_vrc_types.h>

#include <format>
#include <unordered_map>

#include "manifest.h" // generated by librescrs_add_plugin (A5)

namespace {

// A5 (4.0 hardening): EU VRC defers all matching to canHandleConnection;
// kAtrs (from manifest.json) is intentionally empty.

class EuVrcCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    EuVrcCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::eu_vrc::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::eu_vrc::kDisplayName},
                    /*priority=*/200);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::eu_vrc::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::eu_vrc::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            return euvrc::EuVrcCard::probe(conn);
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            euvrc::EuVrcCard card(conn);
            auto doc = card.readCard();

            LibreSCRS::Plugin::CardData data;
            data.cardType = "eu-vrc";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            // Registration
            {
                LibreSCRS::Plugin::CardFieldGroup reg;
                reg.groupKey = "registration";
                reg.groupLabel = "Registration";

                reg.addText("registration_number", "A: Registration Number", doc.registrationNumber);
                reg.addText("date_of_first_registration", "B: First Registration", doc.firstRegistration);
                reg.addText("registration_date", "I: Registration Date", doc.registrationDate);
                reg.addText("expiry_date", "H: Expiry Date", doc.expiryDate);
                reg.addText("member_state", "Member State", doc.memberState);
                reg.addText("competent_authority", "Competent Authority", doc.competentAuthority);
                reg.addText("issuing_authority", "Issuing Authority", doc.issuingAuthority);
                reg.addText("document_number", "Document Number", doc.documentNumber);
                reg.addText("type_approval_number", "K: Type Approval", doc.typeApproval);
                reg.addText("ownership_status", "C.4: Ownership Status", doc.ownershipStatus);
                reg.addText("previous_document", "Previous Document", doc.previousDocument);
                emitGroup(std::move(reg));
            }

            // Vehicle
            {
                LibreSCRS::Plugin::CardFieldGroup veh;
                veh.groupKey = "vehicle";
                veh.groupLabel = "Vehicle";

                veh.addText("vehicle_make", "D.1: Make", doc.vehicleMake);
                veh.addText("vehicle_type", "D.2: Type", doc.vehicleType);
                veh.addText("commercial_description", "D.3: Description", doc.commercialDesc);
                veh.addText("vehicle_id_number", "E: VIN", doc.vin);
                veh.addText("vehicle_category", "J: Category", doc.vehicleCategory);
                veh.addText("colour", "R: Colour", doc.colour);
                veh.addText("engine_capacity", "P.1: Engine Capacity", doc.engineCapacity);
                veh.addText("maximum_net_power", "P.2: Max Power", doc.maxNetPower);
                veh.addText("type_of_fuel", "P.3: Fuel", doc.fuelType);
                veh.addText("engine_id_number", "P.5: Engine ID", doc.engineIdNumber);
                veh.addText("vehicle_mass", "G: Mass", doc.vehicleMass);
                veh.addText("maximum_permissible_laden_mass", "F.1: Max Laden Mass", doc.maxLadenMass);
                veh.addText("power_weight_ratio", "Q: Power/Weight", doc.powerWeightRatio);
                veh.addText("number_of_seats", "S.1: Seats", doc.numberOfSeats);
                veh.addText("number_of_standing_places", "S.2: Standing Places", doc.standingPlaces);
                veh.addText("number_of_axles", "L: Axles", doc.numberOfAxles);
                veh.addText("max_speed", "T: Max Speed", doc.maxSpeed);
                veh.addText("wheelbase", "M: Wheelbase", doc.wheelbase);
                veh.addText("max_laden_mass_service", "F.2: Max Laden Mass (Service)", doc.maxLadenMassService);
                veh.addText("max_laden_mass_whole", "F.3: Max Laden Mass (Whole)", doc.maxLadenMassWhole);
                veh.addText("braked_trailer_mass", "O.1: Braked Trailer Mass", doc.brakedTrailerMass);
                veh.addText("unbraked_trailer_mass", "O.2: Unbraked Trailer Mass", doc.unbrakedTrailerMass);
                veh.addText("rated_engine_speed", "P.4: Rated Engine Speed", doc.ratedEngineSpeed);
                veh.addText("stationary_sound_level", "U.1: Stationary Sound Level", doc.stationarySoundLevel);
                veh.addText("engine_speed_ref", "U.2: Engine Speed (Sound)", doc.engineSpeedRef);
                veh.addText("drive_by_sound", "U.3: Drive-By Sound", doc.driveBySound);
                veh.addText("fuel_consumption", "V.7: Fuel Consumption", doc.fuelConsumption);
                veh.addText("co2_emissions", "V.7: CO2 Emissions", doc.co2);
                veh.addText("environmental_category", "V.9: Environmental Category", doc.envCategory);
                veh.addText("fuel_tank_capacity", "W: Fuel Tank Capacity", doc.fuelTankCapacity);
                emitGroup(std::move(veh));
            }

            // Holder
            {
                LibreSCRS::Plugin::CardFieldGroup holder;
                holder.groupKey = "holder";
                holder.groupLabel = "Holder";

                holder.addText("holder_name", "C.1.1: Name", doc.holderName);
                holder.addText("holder_other_names", "C.1.2: Other Names", doc.holderOtherNames);
                holder.addText("holder_address", "C.1.3: Address", doc.holderAddress);
                emitGroup(std::move(holder));
            }

            // Owner (only if non-empty)
            if (!doc.owner2Name.empty()) {
                LibreSCRS::Plugin::CardFieldGroup owner;
                owner.groupKey = "owner";
                owner.groupLabel = "Owner";

                owner.addText("owner2_name", "C.2: Owner Name", doc.owner2Name);
                emitGroup(std::move(owner));
            }

            // User (only if non-empty)
            if (!doc.userName.empty() || !doc.userOtherNames.empty() || !doc.userAddress.empty()) {
                LibreSCRS::Plugin::CardFieldGroup user;
                user.groupKey = "user";
                user.groupLabel = "User";

                user.addText("user_name", "C.3: Name", doc.userName);
                user.addText("user_other_names", "C.3: Other Names", doc.userOtherNames);
                user.addText("user_address", "C.3: Address", doc.userAddress);
                emitGroup(std::move(user));
            }

            // National Extensions (only if non-empty)
            if (!doc.nationalTags.empty()) {
                // Known Serbian national extension tag names
                static const std::unordered_map<uint32_t, std::pair<std::string, std::string>> serbianTags = {
                    {0xC2, {"owners_personal_no", "Owner Personal Number"}},
                    {0xC3, {"users_personal_no", "User Personal Number"}},
                    {0xC4, {"vehicle_load", "Vehicle Load"}},
                    {0xC5, {"year_of_production", "Year of Production"}},
                    {0xC9, {"serial_number", "Serial Number"}},
                };

                LibreSCRS::Plugin::CardFieldGroup national;
                national.groupKey = "national";
                national.groupLabel = "National Extensions";

                for (const auto& [tag, value] : doc.nationalTags) {
                    auto it = serbianTags.find(tag);
                    std::string key =
                        (it != serbianTags.end()) ? it->second.first : std::format("national_{:04X}", tag);
                    std::string label =
                        (it != serbianTags.end()) ? it->second.second : std::format("Tag 0x{:02X}", tag);
                    national.addText(key, label, value);
                }
                emitGroup(std::move(national));
            }

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eu-vrc readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"eu-vrc readCard failed (unknown error)"});
        }
    }
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(EuVrcCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
