// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <piv_card.h>
#include <piv_types.h>
#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <smartcard/pcsc_connection.h>

#include <format>
#include <string>

#include "manifest.h" // generated by librescrs_add_plugin (A5)

namespace {

// A5 (4.0 hardening): PIV detection runs through canHandleConnection
// (SELECT-AID with the canonical PIV AID) — PIV cards do not have a
// distinguishing ATR. kAtrs (from manifest.json) is intentionally empty.

/// Convert a byte vector to a hex string (lowercase, no separators).
std::string toHex(const std::vector<uint8_t>& bytes)
{
    std::string result;
    result.reserve(bytes.size() * 2);
    for (uint8_t b : bytes)
        result += std::format("{:02x}", b);
    return result;
}

/// Decode pinUsagePolicy bits into a human-readable string.
std::string decodePinPolicy(uint16_t policy)
{
    std::string result;
    // Bit 7 of first byte (0x80) = Application PIN required
    if (policy & 0x8000)
        result += "Application PIN";
    // Bit 6 of first byte (0x40) = Global PIN required
    if (policy & 0x4000) {
        if (!result.empty())
            result += ", ";
        result += "Global PIN";
    }
    // Bit 4 of first byte (0x10) = OCC (biometric on-card comparison)
    if (policy & 0x1000) {
        if (!result.empty())
            result += ", ";
        result += "OCC";
    }
    if (result.empty())
        result = "none";
    return result;
}

class PIVCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    PIVCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::piv::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::piv::kDisplayName},
                    /*priority=*/700);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::piv::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::piv::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        try {
            piv::PIVCard card(conn);
            return card.probe();
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback /*onGroup*/) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            smartcard::CardTransaction tx(conn);
            piv::PIVCard card(conn);
            if (!card.probe()) {
                return ReadResult::unsupportedCard(LibreSCRS::Auth::ErrorKeys::unsupportedCard(),
                                                   std::string{"PIV probe returned false"});
            }
            auto pivData = card.readAll();

            LibreSCRS::Plugin::CardData data;
            data.cardType = "piv";

            // CHUID group
            {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "chuid";
                group.groupLabel = "CHUID";
                group.addText("guid", "GUID", toHex(pivData.chuid.guid));
                group.addText("fascn", "FASC-N", toHex(pivData.chuid.fascn));
                group.addText("expirationDate", "Expiration Date", pivData.chuid.expirationDate);
                data.groups.push_back(std::move(group));
            }

            // CCC group
            {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "ccc";
                group.groupLabel = "CCC";
                group.addText("cardIdentifier", "Card Identifier", toHex(pivData.ccc.cardIdentifier));
                data.groups.push_back(std::move(group));
            }

            // Printed info group (optional)
            if (pivData.printedInfo) {
                const auto& pi = *pivData.printedInfo;
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "printed";
                group.groupLabel = "Printed Information";
                group.addText("name", "Name", pi.name);
                group.addText("employeeAffiliation", "Employee Affiliation", pi.employeeAffiliation);
                group.addText("org1", "Organization (Line 1)", pi.organizationAffiliation1);
                group.addText("org2", "Organization (Line 2)", pi.organizationAffiliation2);
                group.addText("expiry", "Expiration Date", pi.expirationDate);
                group.addText("serialNumber", "Agency Serial Number", pi.agencyCardSerialNumber);
                group.addText("issuerId", "Issuer Identification", pi.issuerIdentification);
                data.groups.push_back(std::move(group));
            }

            // Discovery group
            {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "discovery";
                group.groupLabel = "Discovery";
                group.addText("pinPolicy", "PIN Policy", decodePinPolicy(pivData.discovery.pinUsagePolicy));
                data.groups.push_back(std::move(group));
            }

            // Key history group (optional)
            if (pivData.keyHistory) {
                const auto& kh = *pivData.keyHistory;
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "keyHistory";
                group.groupLabel = "Key History";
                group.addText("onCardCerts", "On-Card Certificates", std::to_string(kh.keysWithOnCardCerts));
                group.addText("offCardCerts", "Off-Card Certificates", std::to_string(kh.keysWithOffCardCerts));
                group.addText("offCardURL", "Off-Card URL", kh.offCardCertURL);
                data.groups.push_back(std::move(group));
            }

            // PKI group (if certificates present)
            if (!pivData.certificates.empty()) {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "pki";
                group.groupLabel = "PKI";
                group.addText("certificateCount", "Certificate Count", std::to_string(pivData.certificates.size()));
                data.groups.push_back(std::move(group));
            }

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"PIV readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"PIV readCard failed (unknown error)"});
        }
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        smartcard::CardTransaction tx(conn);
        piv::PIVCard card(conn);
        card.probe();
        auto certs = card.readCertificates();

        std::vector<LibreSCRS::Plugin::CertificateData> result;
        result.reserve(certs.size());
        for (auto& cert : certs) {
            LibreSCRS::Plugin::CertificateData cd;
            cd.label = cert.slotName;
            cd.derBytes = std::move(cert.certBytes);
            // PIV slot reference is always a concrete byte; engage the optional.
            cd.keyFID = static_cast<std::uint16_t>(cert.keyReference);
            result.push_back(std::move(cd));
        }
        return result;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry> getPINList(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        smartcard::CardTransaction tx(conn);
        piv::PIVCard card(conn);
        card.probe();
        auto pins = card.discoverPINs();

        std::vector<LibreSCRS::Plugin::PinStatusEntry> result;
        for (const auto& pin : pins) {
            LibreSCRS::Plugin::PinStatusEntry entry;
            entry.label = pin.label;
            entry.reference = pin.keyReference;
            entry.initialized = true;

            try {
                int tries = card.getPINTriesLeft(pin.keyReference);
                if (tries >= 0)
                    entry.retriesLeft = tries;
                entry.blocked = (tries == 0);
            } catch (...) {
                // leave entry.retriesLeft as std::nullopt
            }

            entry.minLength = std::size_t{6};
            entry.maxLength = std::size_t{8};
            entry.canChange = false;
            result.push_back(std::move(entry));
        }
        return result;
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& session,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        smartcard::CardTransaction tx(conn);
        piv::PIVCard card(conn);
        card.probe();

        auto pins = card.discoverPINs();
        if (pins.empty())
            return {};

        // 4.0 hardening: pass Secure::String directly; before this hardening change the
        // call widened to std::string{pin.view()} which left a non-cleansed
        // PIN copy on the heap until allocator reuse.
        return card.verifyPIN(pins.front().keyReference, pin);
    }

    std::optional<int> getPINTriesLeft(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        smartcard::CardTransaction tx(conn);
        piv::PIVCard card(conn);
        card.probe();

        auto pins = card.discoverPINs();
        if (pins.empty())
            return std::nullopt;

        int tries = card.getPINTriesLeft(pins.front().keyReference);
        if (tries < 0)
            return std::nullopt;
        return tries;
    }

    std::vector<LibreSCRS::Plugin::KeyReference>
    discoverKeyReferences(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        smartcard::CardTransaction tx(conn);
        piv::PIVCard card(conn);
        card.probe();
        auto internal = card.discoverKeys();
        std::vector<LibreSCRS::Plugin::KeyReference> result;
        result.reserve(internal.size());
        for (auto& kv : internal) {
            result.push_back({std::move(kv.first), kv.second});
        }
        return result;
    }
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(PIVCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
