// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Auth/SecretParameter.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PinOutcome.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <pcsc_connection.h>

#include <libopensc/opensc.h>
#include <libopensc/pkcs15.h>

#include <openssl/x509.h>

#include <LibreSCRS_internal/Crypto/OpenSslPtr.h>

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <string_view>
#include <vector>

#include "manifest.h" // generated by librescrs_add_plugin
#include "opensc_reader_bridge.h"
#include "pin_family_quirks.h"
#include "pin_lifecycle_derivation.h"
#include "pkcs15_cert_ptr.h"

namespace {

using LibreSCRS::Internal::Crypto::X509Ptr;
using LibreSCRS::OpenSc::Pkcs15CertPtr;

// OpenSC fallback for unknown PKCS#15-shaped cards. Sits BELOW specific
// plugins (rs-eid, rs-health, emrtd, eu-vrc — priorities 100-ish) but
// ABOVE the generic LM PKCS#15 parser (pkcs15-plugin, priority 900):
// OpenSC's full driver chain (srbeid, cardos, ias-ecc, openpgp, …)
// handles card-specific quirks the generic parser does not. Never
// matches by ATR — relies on canHandleConnection driving sc_pkcs15_bind()
// against the live session. kAtrs (from manifest.json) is intentionally empty.

std::string extractSubjectCN(const uint8_t* der, size_t len)
{
    // X509Ptr keeps the parsed cert alive across the std::string ctor at
    // the bottom of this function, which can throw std::bad_alloc on a
    // pathological allocator. The previous raw-X509* path leaked the
    // cert on that unwind because the explicit X509_free was unreachable.
    const uint8_t* p = der;
    X509Ptr cert(d2i_X509(nullptr, &p, static_cast<long>(len)));
    if (!cert)
        return "(unreadable)";

    X509_NAME* subject = X509_get_subject_name(cert.get());
    char buf[256] = {};
    X509_NAME_get_text_by_NID(subject, NID_commonName, buf, sizeof(buf));

    std::string cn(buf);
    return cn.empty() ? "(no CN)" : cn;
}

// Per-session OpenSC binding state. Owned by the plugin's session map,
// keyed by PCSCConnection*. A fresh entry is created on canHandleConnection()
// and torn down by ~OpenSCSession() (invoked when erased from the map, when
// the map itself is destroyed, or — critically — during stack unwind if
// `sessions.emplace(...)` throws bad_alloc on a partially-built session).
//
// Move-only RAII: the libopensc resources (ctx / card / p15card) are
// owned by exactly one OpenSCSession at any time. Copy is disabled to
// prevent double-free; move nulls out the source so the moved-from
// instance's dtor is a no-op.
class OpenSCSession
{
public:
    OpenSCSession() = default;
    ~OpenSCSession() noexcept
    {
        release();
    }

    OpenSCSession(const OpenSCSession&) = delete;
    OpenSCSession& operator=(const OpenSCSession&) = delete;

    OpenSCSession(OpenSCSession&& other) noexcept
        : ctx(other.ctx), card(other.card), p15card(other.p15card), readerName(std::move(other.readerName)),
          hasPKI(other.hasPKI), bridge(std::move(other.bridge))
    {
        other.ctx = nullptr;
        other.card = nullptr;
        other.p15card = nullptr;
        other.hasPKI = false;
    }

    OpenSCSession& operator=(OpenSCSession&& other) noexcept
    {
        if (this != &other) {
            release();
            ctx = other.ctx;
            card = other.card;
            p15card = other.p15card;
            readerName = std::move(other.readerName);
            hasPKI = other.hasPKI;
            bridge = std::move(other.bridge);
            other.ctx = nullptr;
            other.card = nullptr;
            other.p15card = nullptr;
            other.hasPKI = false;
        }
        return *this;
    }

    // Public for direct field-style use at call sites (mirrors prior POD
    // shape). All four owning pointers are managed by release() and the
    // move ctor; the std::string + bool are trivially handled by the
    // generated move ops.
    sc_context_t* ctx = nullptr;
    sc_card_t* card = nullptr;
    sc_pkcs15_card_t* p15card = nullptr;
    std::string readerName;
    bool hasPKI = false;

    // Single-session bridge: owns the librescrs-bridge sc_reader + its private
    // data at a stable heap address (survives this OpenSCSession's move into
    // the sessions map after sc_connect_card set card->reader = &reader). Holds
    // no PC/SC connection of its own — it routes libopensc through the LM
    // PCSCConnection. Released last in release() (it is NOT in ctx->readers, so
    // sc_release_context does not free it).
    std::unique_ptr<LibreSCRS::OpenSc::Bridge::OpenScBridge> bridge;

private:
    // Order matters: PKCS#15 binding holds references into the underlying
    // sc_card; the card must be disconnected before releasing the context.
    void release() noexcept
    {
        if (p15card) {
            sc_pkcs15_unbind(p15card);
            p15card = nullptr;
        }
        if (card) {
            sc_disconnect_card(card);
            card = nullptr;
        }
        if (ctx) {
            sc_release_context(ctx);
            ctx = nullptr;
        }
        // The bridge reader is NOT in ctx->readers, so sc_release_context did
        // not free it; resetting frees the sc_reader + private-data block.
        // Must run after sc_disconnect_card/sc_release_context, which used
        // card->reader = &bridge->reader.
        bridge.reset();
        hasPKI = false;
    }
};

} // namespace

namespace LibreSCRS::OpenSc {

namespace {

/// Maps libopensc's resolved card-driver identity to a quirk-table family.
/// Uses only the driver short_name that sc_connect_card already resolved —
/// no ATR probing or new detection here; unrecognised drivers stay Unknown
/// (nullptr quirks: nothing beyond evidence-derived kind/state is
/// advertised for them).
LibreSCRS::Plugin::Internal::FamilyId familyFromDriverShortName(const char* shortName) noexcept
{
    using LibreSCRS::Plugin::Internal::FamilyId;
    if (!shortName)
        return FamilyId::Unknown;
    const std::string_view name{shortName};
    if (name == "PIV-II")
        return FamilyId::Piv;
    if (name == "srbeid") // vendored driver for the Serbian CardEdge applet
        return FamilyId::CurrentLkCardEdge;
    return FamilyId::Unknown;
}

} // namespace

/// @brief Builds lifecycle-classified PIN entries from parsed PKCS#15 auth
///        objects via the shared derivation engine.
///
/// Non-member seam so unit tests can drive it with synthetic sc_pkcs15
/// objects (the test target compiles this translation unit directly).
/// Reads ONLY the already-parsed structures — no card I/O — so calling it
/// from getPINList preserves the non-consumption invariant.
std::vector<LibreSCRS::Plugin::PinStatusEntry> buildPinStatusEntries(sc_pkcs15_object_t* const* pinObjs, int pinCount,
                                                                     const char* driverShortName)
{
    namespace Internal = LibreSCRS::Plugin::Internal;

    std::vector<LibreSCRS::Plugin::PinStatusEntry> result;
    if (!pinObjs || pinCount <= 0)
        return result;

    // Pass 1: per-object evidence from the parsed AODF attributes. The
    // needs-change signal is a bit test: drivers OR
    // SC_PIN_STATE_NEEDS_CHANGE onto the logged state.
    std::vector<Internal::PinEvidence> evidence;
    std::vector<const sc_pkcs15_object_t*> objs; // aligned with evidence
    std::vector<const sc_pkcs15_auth_info_t*> infos;
    evidence.reserve(static_cast<std::size_t>(pinCount));
    objs.reserve(static_cast<std::size_t>(pinCount));
    infos.reserve(static_cast<std::size_t>(pinCount));
    for (int i = 0; i < pinCount; ++i) {
        const sc_pkcs15_object_t* obj = pinObjs[i];
        const auto* info = obj ? static_cast<const sc_pkcs15_auth_info_t*>(obj->data) : nullptr;
        if (!info)
            continue;

        Internal::PinEvidence ev;
        // An empty AODF label must never be advertised verbatim: the
        // changePIN selector contract reserves the EMPTY selector for the
        // legacy default-PIN fallback, so "" would alias this record onto
        // a DIFFERENT credential. The documented "pin_<reference>" form
        // is the non-aliasing substitute — resolveChangePinTarget accepts
        // it verbatim and addresses the record by its reference.
        const auto reference = static_cast<std::uint8_t>(info->attrs.pin.reference & 0xff);
        ev.label = obj->label[0] ? std::string{obj->label} : "pin_" + std::to_string(reference);
        ev.reference = reference;
        ev.ownId.assign(info->auth_id.value, info->auth_id.value + info->auth_id.len);
        const unsigned int flags = info->attrs.pin.flags;
        ev.localScope = (flags & SC_PKCS15_PIN_FLAG_LOCAL) != 0;
        // inQscdDf / paceEvidence stay false: the generic OpenSC path has
        // no signature-DF map and no PACE evidence.
        ev.soPinFlag = (flags & SC_PKCS15_PIN_FLAG_SO_PIN) != 0;
        ev.unblockingPinFlag = (flags & SC_PKCS15_PIN_FLAG_UNBLOCKING_PIN) != 0;
        ev.unblockDisabledFlag = (flags & SC_PKCS15_PIN_FLAG_UNBLOCK_DISABLED) != 0;
        ev.changeDisabledFlag = (flags & SC_PKCS15_PIN_FLAG_CHANGE_DISABLED) != 0;
        ev.initialized = (flags & SC_PKCS15_PIN_FLAG_INITIALIZED) != 0;
        // tries_left semantics: -1 = unknown; >= 0 = real count, 0 blocked.
        ev.blocked = (info->tries_left == 0);
        ev.needsChangeSignal = (info->logged_in & SC_PIN_STATE_NEEDS_CHANGE) != 0;
        evidence.push_back(std::move(ev));
        objs.push_back(obj);
        infos.push_back(info);
    }

    // Pass 2: resolve the AODF authId protection chain per the derivation
    // engine's contract — when object i is protected by auth object j,
    // record the protecting object's FULL id bytes on i (matched against
    // the target's ownId during derivation) and mark j as the unblocking
    // chain target.
    for (std::size_t i = 0; i < objs.size(); ++i) {
        const sc_pkcs15_id* protecting = &objs[i]->auth_id;
        if (protecting->len == 0)
            continue;
        for (std::size_t j = 0; j < objs.size(); ++j) {
            if (j == i)
                continue;
            if (sc_pkcs15_compare_id(&infos[j]->auth_id, protecting)) {
                evidence[i].authIdChainTarget =
                    std::vector<std::uint8_t>(protecting->value, protecting->value + protecting->len);
                evidence[j].unblockingPinFlag = true;
                break;
            }
        }
    }

    const Internal::FamilyQuirks* quirks = Internal::findFamilyQuirks(familyFromDriverShortName(driverShortName));

    for (std::size_t i = 0; i < evidence.size(); ++i) {
        auto entry = Internal::derivePinStatus(evidence[i], evidence, quirks);
        // Caller-populated counters/lengths (outside the engine's remit).
        const sc_pkcs15_auth_info_t* info = infos[i];
        if (info->tries_left >= 0)
            entry.retriesLeft = info->tries_left;
        if (info->attrs.pin.min_length > 0)
            entry.minLength = info->attrs.pin.min_length;
        if (info->attrs.pin.max_length > 0)
            entry.maxLength = info->attrs.pin.max_length;
        result.push_back(std::move(entry));
    }
    return result;
}

/// @brief Resolves the @c changePIN selector over the enumerated AUTH_PIN
///        objects.
///
/// Selector contract (see the @c changePIN doc in CardPlugin.h): an EMPTY
/// selector keeps the legacy default-PIN behaviour and resolves the FIRST
/// enumerated object; a non-empty selector must match an object's label
/// or the documented "pin_<reference>" form (decimal reference). A
/// non-empty selector that matches nothing resolves to @c nullptr — the
/// caller must refuse WITHOUT touching the card (mutating a PIN the host
/// did not address is never acceptable on multi-PIN cards).
sc_pkcs15_object_t* resolveChangePinTarget(sc_pkcs15_object_t* const* pinObjs, int pinCount, std::string_view pinLabel)
{
    if (!pinObjs || pinCount <= 0)
        return nullptr;
    if (pinLabel.empty())
        return pinObjs[0]; // legacy default-PIN path

    for (int i = 0; i < pinCount; ++i) {
        if (pinObjs[i] && std::string_view{pinObjs[i]->label} == pinLabel)
            return pinObjs[i];
    }

    constexpr std::string_view prefix = "pin_";
    if (pinLabel.starts_with(prefix)) {
        const std::string_view suffix = pinLabel.substr(prefix.size());
        int reference = 0;
        const auto [ptr, ec] = std::from_chars(suffix.data(), suffix.data() + suffix.size(), reference);
        if (ec == std::errc{} && ptr == suffix.data() + suffix.size() && reference >= 0) {
            for (int i = 0; i < pinCount; ++i) {
                const auto* info = pinObjs[i] ? static_cast<const sc_pkcs15_auth_info_t*>(pinObjs[i]->data) : nullptr;
                if (info && info->attrs.pin.reference == reference)
                    return pinObjs[i];
            }
        }
    }
    return nullptr;
}

/// @brief Signature of the libopensc PIN-change entry point
///        (@c sc_pkcs15_change_pin) as consumed by the change-dispatch seam.
using ChangePinFn = int (*)(sc_pkcs15_card_t*, sc_pkcs15_object_t*, const unsigned char*, std::size_t,
                            const unsigned char*, std::size_t);
/// @brief Signature of the post-change counter refresh
///        (@c sc_pkcs15_get_pin_info) as consumed by the change-dispatch seam.
using RefreshPinInfoFn = int (*)(sc_pkcs15_card_t*, sc_pkcs15_object_t*);

/// @brief Change-dispatch seam: applies the @c changePIN selector contract
///        over the enumerated AUTH_PIN objects and dispatches the change to
///        the resolved object through the injected driver entry points.
///
/// Non-member seam (same rationale as @ref buildPinStatusEntries): the unit
/// tests compile this translation unit directly and drive the selector with
/// synthetic sc_pkcs15 objects plus fake driver functions, so the
/// addressed-object contract is asserted without any card I/O. Production
/// callers pass @c sc_pkcs15_change_pin / @c sc_pkcs15_get_pin_info.
LibreSCRS::Plugin::PINResult changePinWithSelector(sc_pkcs15_card_t* p15card, sc_pkcs15_object_t* const* pinObjs,
                                                   int pinCount, std::string_view pinLabel,
                                                   const LibreSCRS::Secure::String& oldPin,
                                                   const LibreSCRS::Secure::String& newPin, ChangePinFn changeFn,
                                                   RefreshPinInfoFn refreshFn)
{
    static_assert(LibreSCRS::Auth::SecretParameter<decltype(oldPin)>,
                  "changePIN oldPin parameter must be Secure::String const&");
    static_assert(LibreSCRS::Auth::SecretParameter<decltype(newPin)>,
                  "changePIN newPin parameter must be Secure::String const&");

    LibreSCRS::Plugin::PINResult result;
    sc_pkcs15_object_t* target = resolveChangePinTarget(pinObjs, pinCount, pinLabel);
    if (!target) {
        // Non-empty selector with no matching PIN object (or an empty
        // object set): refuse before anything reaches the card.
        result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return result;
    }

    auto oldView = oldPin.view();
    auto newView = newPin.view();
    const int rc = changeFn(p15card, target, reinterpret_cast<const unsigned char*>(oldView.data()), oldView.size(),
                            reinterpret_cast<const unsigned char*>(newView.data()), newView.size());

    // Refresh tries_left from card (change may not update auth_info on all
    // drivers).
    refreshFn(p15card, target);
    const auto* authInfo = static_cast<const sc_pkcs15_auth_info_t*>(target->data);
    if (authInfo->tries_left >= 0)
        result.retriesLeft = authInfo->tries_left;
    result.blocked = (authInfo->tries_left == 0);
    result.outcome = LibreSCRS::Plugin::classifyPinOutcome(result, rc == 0);
    return result;
}

} // namespace LibreSCRS::OpenSc

namespace {

class OpenSCCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    OpenSCCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::opensc::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::opensc::kDisplayName},
                    /*priority=*/800);
    }

    ~OpenSCCardPlugin() override
    {
        std::lock_guard lock(mtx);
        // OpenSCSession dtor releases libopensc resources; clearing the
        // map invokes it for every entry.
        sessions.clear();
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::opensc::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::opensc::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> atr,
                             LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);

        // Start a fresh session for this connection, tearing down any prior
        // state keyed to the same PCSCConnection* (re-entrancy safety on
        // card re-insert against the same reader). The erased value's
        // ~OpenSCSession() releases libopensc resources.
        sessions.erase(&conn);

        OpenSCSession session;
        session.readerName = conn.readerName();

        int rc = sc_establish_context(&session.ctx, "librescrs");
        if (rc < 0)
            return false;

        // Bind libopensc to the agent's single LM PCSCConnection via the
        // bridge reader, instead of opening a second sc_connect_card. The
        // built-in pcsc reader_driver stays as ctx->reader_driver (its init
        // already ran in sc_establish_context, harmlessly); we drive our own
        // injected reader, whose transmit op routes through conn.transmit().
        // Use the ATR the agent already read for this session (the
        // canHandleConnection `atr` argument == CardSession::atr()); no extra
        // SCardStatus, and it cannot throw across the plugin boundary the way
        // a detached-connection getATR() would.
        session.bridge = std::make_unique<LibreSCRS::OpenSc::Bridge::OpenScBridge>();
        session.bridge->data.conn = &conn;
        session.bridge->readerName = conn.readerName();
        LibreSCRS::OpenSc::Bridge::initBridgeReader(session.ctx, *session.bridge, atr);

        rc = sc_connect_card(&session.bridge->reader, &session.card);
        if (rc < 0) {
            // ~OpenSCSession runs on scope exit and releases ctx + bridge.
            return false;
        }

        rc = sc_pkcs15_bind(session.card, nullptr, &session.p15card);
        if (rc < 0) {
            return false;
        }

        // Detect PKI presence (PIN + RSA objects). No longer exposed
        // externally — kept for diagnostic/read-path hinting.
        sc_pkcs15_object_t* pinObjs[8];
        int pinCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 8);

        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        session.hasPKI = (pinCount > 0 || keyCount > 0);

        sessions.emplace(&conn, std::move(session));
        return true;
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            LibreSCRS::Plugin::CardData data;
            data.cardType = "opensc";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
            std::lock_guard lock(mtx);
            auto it = sessions.find(&conn);
            if (it == sessions.end() || !it->second.p15card) {
                return ReadResult::unsupportedCard(
                    LibreSCRS::Auth::ErrorKeys::unsupportedCard(),
                    std::string{"opensc session not bound — canHandleConnection was not called or failed"});
            }
            auto& session = it->second;

            // Token info group. Field keys ("label" / "serial_number" /
            // "manufacturer") MUST match the well-known token-header keys
            // GUI hosts use to localise the row labels; the same keys are
            // emitted by readTokenInfo() below, keeping the two surfaces
            // consistent.
            LibreSCRS::Plugin::CardFieldGroup tokenGroup;
            tokenGroup.groupKey = "token";
            tokenGroup.groupLabel = "Token Info";

            auto* ti = session.p15card->tokeninfo;
            if (ti) {
                auto addField = [&](const std::string& key, const std::string& label, const char* val) {
                    if (val && val[0] != '\0') {
                        std::string s(val);
                        tokenGroup.fields.push_back(
                            {key, label, LibreSCRS::Plugin::FieldType::Text, {s.begin(), s.end()}});
                    }
                };
                addField("label", "Label", ti->label);
                addField("serial_number", "Serial Number", ti->serial_number);
                addField("manufacturer", "Manufacturer", ti->manufacturer_id);

                // Decode flags to human-readable string
                std::string flagStr;
                if (ti->flags & SC_PKCS15_TOKEN_PRN_GENERATION)
                    flagStr += "PRN ";
                if (ti->flags & SC_PKCS15_TOKEN_LOGIN_REQUIRED)
                    flagStr += "Login required ";
                if (!flagStr.empty()) {
                    flagStr.pop_back(); // remove trailing space
                    tokenGroup.fields.push_back(
                        {"flags", "Flags", LibreSCRS::Plugin::FieldType::Text, {flagStr.begin(), flagStr.end()}});
                }
            }
            emitGroup(std::move(tokenGroup));

            // Certificates summary group
            sc_pkcs15_object_t* certObjs[16];
            int certCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_CERT_X509, certObjs, 16);

            if (certCount > 0) {
                LibreSCRS::Plugin::CardFieldGroup certGroup;
                certGroup.groupKey = "certificates";
                certGroup.groupLabel = "Certificates";

                for (int i = 0; i < certCount; ++i) {
                    auto* certInfo = static_cast<sc_pkcs15_cert_info_t*>(certObjs[i]->data);
                    sc_pkcs15_cert_t* certRaw = nullptr;
                    int rc = sc_pkcs15_read_certificate(session.p15card, certInfo, 0, &certRaw);

                    // Pkcs15CertPtr wraps the cert across extractSubjectCN
                    // (allocates the CN std::string) and the throwing
                    // certGroup.fields.push_back below.
                    Pkcs15CertPtr cert(certRaw);
                    std::string cn = "(unreadable)";
                    if (rc == 0 && cert) {
                        cn = extractSubjectCN(cert->data.value, cert->data.len);
                    }

                    std::string key = "cert_" + std::to_string(i);
                    std::string label =
                        certObjs[i]->label[0] ? certObjs[i]->label : ("Certificate " + std::to_string(i));
                    certGroup.fields.push_back(
                        {key, label, LibreSCRS::Plugin::FieldType::Text, {cn.begin(), cn.end()}});
                }
                emitGroup(std::move(certGroup));
            }

            // PIN state is surfaced via the typed getPINList() override
            // (PinStatusEntry vector), not via the readCard() data groups.

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"opensc readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"opensc readCard failed (unknown error)"});
        }
    }

    LibreSCRS::Plugin::CardFieldGroup readTokenInfo(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        // Best-effort token-info read mirroring the pkcs15-plugin contract.
        // The group key/label are populated up-front so the presentation
        // layer can render its placeholder header from an empty group when
        // nothing could be read (no bound p15card, no tokeninfo).
        //
        // Field keys ("label", "serial_number", "manufacturer") are the
        // well-known token-header keys consumed by GUI hosts; cross-plugin
        // key drift would silently demote to placeholder rendering even
        // when the data is present.
        LibreSCRS::Plugin::CardFieldGroup group;
        group.groupKey = "token";
        group.groupLabel = "Token Info";

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return group;

        auto* ti = it->second.p15card->tokeninfo;
        if (!ti)
            return group;

        // CardFieldGroup::addText throws on (empty value, empty fields) by
        // design — skip empty values up-front so a single missing field can
        // never cascade into a fully empty group.
        auto safeAddText = [&](std::string_view key, std::string_view label, const char* value) {
            if (!value || value[0] == '\0')
                return;
            std::string_view sv(value);
            try {
                group.addText(key, label, sv);
            } catch (const std::exception& ex) {
                std::clog << "[librescrs.opensc.plugin] readTokenInfo: addText(" << key << ") threw: " << ex.what()
                          << "\n";
            } catch (...) {
                std::clog << "[librescrs.opensc.plugin] readTokenInfo: addText threw (non-std exception)\n";
            }
        };

        safeAddText("label", "Label", ti->label);
        safeAddText("serial_number", "Serial Number", ti->serial_number);
        safeAddText("manufacturer", "Manufacturer", ti->manufacturer_id);
        return group;
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::CertificateData> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* certObjs[16];
        int certCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_CERT_X509, certObjs, 16);

        for (int i = 0; i < certCount; ++i) {
            auto* certInfo = static_cast<sc_pkcs15_cert_info_t*>(certObjs[i]->data);
            sc_pkcs15_cert_t* certRaw = nullptr;
            int rc = sc_pkcs15_read_certificate(session.p15card, certInfo, 0, &certRaw);
            if (rc < 0 || !certRaw)
                continue;

            // Pkcs15CertPtr keeps the cert alive across cd.derBytes.assign()
            // (throws bad_alloc on large certs) and the throwable
            // result.push_back below — both leaked the cert previously.
            Pkcs15CertPtr cert(certRaw);

            LibreSCRS::Plugin::CertificateData cd;
            cd.label = certObjs[i]->label;
            cd.derBytes.assign(cert->data.value, cert->data.value + cert->data.len);
            // The PKCS#15 object id IS the PKCS#11 CKA_ID — surface it so the
            // in-process sign path selects THIS exact key by CKA_ID rather than
            // the non-unique label.
            cd.ckaId.assign(certInfo->id.value, certInfo->id.value + certInfo->id.len);

            // Try to find associated private key for FID and key size
            sc_pkcs15_object_t* keyObj = nullptr;
            rc = sc_pkcs15_find_prkey_by_id(session.p15card, &certInfo->id, &keyObj);
            if (rc == 0 && keyObj) {
                auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObj->data);
                cd.keyFID = static_cast<std::uint16_t>(keyInfo->key_reference);
                cd.keySizeBits = static_cast<std::uint16_t>(keyInfo->modulus_length);
            }

            result.push_back(std::move(cd));
        }

        return result;
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& cardSession,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return {};
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0)
            return {};

        auto pinView = pin.view();
        int rc = sc_pkcs15_verify_pin(session.p15card, pinObjs[0], reinterpret_cast<const uint8_t*>(pinView.data()),
                                      pinView.size());

        // Refresh tries_left from card (verify may not update auth_info on all drivers)
        sc_pkcs15_get_pin_info(session.p15card, pinObjs[0]);
        auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjs[0]->data);

        LibreSCRS::Plugin::PINResult result;
        if (authInfo->tries_left >= 0)
            result.retriesLeft = authInfo->tries_left;
        result.blocked = (authInfo->tries_left == 0);
        result.outcome = LibreSCRS::Plugin::classifyPinOutcome(result, rc == 0);
        return result;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry>
    getPINList(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::PinStatusEntry> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[8];
        int pinCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 8);
        if (pinCount <= 0)
            return result;

        // Lifecycle classification runs on the already-parsed AODF data
        // only — no APDUs, preserving the non-consumption invariant.
        const char* driverShortName =
            (session.card && session.card->driver) ? session.card->driver->short_name : nullptr;
        return LibreSCRS::OpenSc::buildPinStatusEntries(pinObjs, pinCount, driverShortName);
    }

    LibreSCRS::Plugin::PINResult changePIN(LibreSCRS::SmartCard::CardSession& cardSession, std::string_view pinLabel,
                                           const LibreSCRS::Secure::String& oldPin,
                                           const LibreSCRS::Secure::String& newPin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card) {
            LibreSCRS::Plugin::PINResult r;
            r.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return r;
        }
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0) {
            LibreSCRS::Plugin::PINResult r;
            r.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return r;
        }

        return LibreSCRS::OpenSc::changePinWithSelector(session.p15card, pinObjs, count, pinLabel, oldPin, newPin,
                                                        &sc_pkcs15_change_pin, &sc_pkcs15_get_pin_info);
    }

    LibreSCRS::Plugin::CredentialCounters readCounters(LibreSCRS::SmartCard::CardSession& cardSession,
                                                       std::string_view /*pinLabel*/) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return {};
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0)
            return {};

        int rc = sc_pkcs15_get_pin_info(session.p15card, pinObjs[0]);
        if (rc < 0)
            return {};
        auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjs[0]->data);
        LibreSCRS::Plugin::CredentialCounters c;
        if (authInfo->tries_left >= 0)
            c.retriesLeft = authInfo->tries_left;
        if (authInfo->max_tries > 0)
            c.retriesMax = authInfo->max_tries;
        // OpenSC's sc_pkcs15_auth_info models no usage/reset counter, so
        // uses*/unblocksLeft stay absent — the documented OpenSC limit.
        return c;
    }

    LibreSCRS::Plugin::SignResult doSign(LibreSCRS::SmartCard::CardSession& cardSession, std::uint16_t keyReference,
                                         std::span<const std::uint8_t> data,
                                         LibreSCRS::Plugin::SignMechanism mechanism) const override
    {
        auto pluginError = []() {
            LibreSCRS::Plugin::SignResult r;
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
            return r;
        };

        // 4.0 ABI v6 reserves the ECDSA_SHA{256,384,512} mechanisms. This plugin
        // only supports RSA_PKCS — surface anything else as NotImplemented
        // so callers can route to an ECDSA-capable plugin (or a future
        // extension of this driver) instead of producing a silently RSA-
        // signed blob for an ECDSA request.
        if (mechanism != LibreSCRS::Plugin::SignMechanism::RSA_PKCS) {
            LibreSCRS::Plugin::SignResult r;
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::NotImplemented;
            return r;
        }

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return pluginError();
        auto& session = it->second;

        // Find private key by reference
        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        sc_pkcs15_object_t* targetKey = nullptr;
        for (int i = 0; i < keyCount; ++i) {
            auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObjs[i]->data);
            if (static_cast<uint16_t>(keyInfo->key_reference) == keyReference) {
                targetKey = keyObjs[i];
                break;
            }
        }
        if (!targetKey)
            return pluginError();

        auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(targetKey->data);
        size_t sigLen = keyInfo->modulus_length / 8; // RSA signature length in bytes
        std::vector<uint8_t> sig(sigLen);

        int rc = sc_pkcs15_compute_signature(session.p15card, targetKey,
                                             SC_ALGORITHM_RSA_PAD_PKCS1_TYPE_01 | SC_ALGORITHM_RSA_HASH_NONE,
                                             data.data(), data.size(), sig.data(), sig.size(), nullptr);

        if (rc < 0)
            return pluginError();
        sig.resize(static_cast<size_t>(rc));
        LibreSCRS::Plugin::SignResult result;
        result.signature = std::move(sig);
        result.outcome = LibreSCRS::Plugin::SignResultOutcome::Ok;
        return result;
    }

    LibreSCRS::Plugin::DecipherResult doDecipher(LibreSCRS::SmartCard::CardSession& cardSession,
                                                 std::uint16_t keyReference, std::span<const std::uint8_t> ciphertext,
                                                 LibreSCRS::Plugin::DecipherMechanism mechanism) const override
    {
        auto pluginError = []() {
            LibreSCRS::Plugin::DecipherResult r;
            r.outcome = LibreSCRS::Plugin::DecipherResultOutcome::PluginError;
            return r;
        };

        // This release supports only PKCS#1 v1.5 decrypt (SR cards are v1.5
        // only, no OAEP). Surface any other mechanism as NotImplemented so a
        // caller can route to a future OAEP-capable driver instead of silently
        // producing a v1.5-stripped result.
        if (mechanism != LibreSCRS::Plugin::DecipherMechanism::RSA_PKCS1_V15) {
            LibreSCRS::Plugin::DecipherResult r;
            r.outcome = LibreSCRS::Plugin::DecipherResultOutcome::NotImplemented;
            return r;
        }

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return pluginError();
        auto& session = it->second;

        // Find private key by reference (same resolution as doSign).
        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        sc_pkcs15_object_t* targetKey = nullptr;
        for (int i = 0; i < keyCount; ++i) {
            auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObjs[i]->data);
            if (static_cast<uint16_t>(keyInfo->key_reference) == keyReference) {
                targetKey = keyObjs[i];
                break;
            }
        }
        if (!targetKey)
            return pluginError();

        auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(targetKey->data);
        size_t outCap = keyInfo->modulus_length / 8; // RSA block size in bytes
        std::vector<uint8_t> out(outCap);

        // Raw RSA decrypt + software PKCS#1 v1.5 unpad. The srbeid driver
        // advertises only SC_ALGORITHM_RSA_RAW and wires decipher to the raw
        // c^d mod N transform (card-srbeid.c:91,287), so it returns the full
        // padded block. Requesting SC_ALGORITHM_RSA_PAD_PKCS1_TYPE_02 makes
        // libopensc take the "card does raw, host strips padding" path
        // (sc_get_encoding_flags: pflags=TYPE_02, sflags=PAD_NONE —
        // padding.c:728) and then strip the v1.5 type-02 padding in
        // sc_pkcs15_decipher (pkcs15-sec.c:316). TYPE_02 (not TYPE_01) is the
        // decryption padding marker; TYPE_01 is the signing form. Verified
        // against the vendored OpenSC #3701 source.
        int rc = sc_pkcs15_decipher(session.p15card, targetKey, SC_ALGORITHM_RSA_PAD_PKCS1_TYPE_02, ciphertext.data(),
                                    ciphertext.size(), out.data(), out.size(), nullptr);
        if (rc < 0)
            return pluginError();
        out.resize(static_cast<size_t>(rc));
        LibreSCRS::Plugin::DecipherResult result;
        result.plaintext = std::move(out);
        result.outcome = LibreSCRS::Plugin::DecipherResultOutcome::Ok;
        return result;
    }

    std::vector<LibreSCRS::Plugin::KeyReference>
    discoverKeyReferences(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::KeyReference> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        for (int i = 0; i < keyCount; ++i) {
            auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObjs[i]->data);
            result.push_back({keyObjs[i]->label, static_cast<std::uint16_t>(keyInfo->key_reference)});
        }

        return result;
    }

    void clearCredentials(LibreSCRS::SmartCard::CardSession& cardSession) noexcept override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
            std::lock_guard lock(mtx);
            // Erasing the entry invokes ~OpenSCSession on the held value.
            sessions.erase(&conn);
        } catch (...) {
            // clearCredentials is noexcept — swallow unwrap/lock failures.
        }
    }

private:
    mutable std::mutex mtx;
    mutable std::map<const LibreSCRS::SmartCard::Internal::PCSCConnection*, OpenSCSession> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(OpenSCCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
