// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <smartcard/pcsc_connection.h>

#include <libopensc/opensc.h>
#include <libopensc/pkcs15.h>

#include <openssl/x509.h>

#include <iostream>
#include <map>
#include <mutex>
#include <string_view>

#include "manifest.h" // generated by librescrs_add_plugin (A5)

namespace {

// OpenSC fallback for unknown PKCS#15-shaped cards. Sits BELOW specific
// plugins (rs-eid, rs-health, emrtd, eu-vrc — priorities 100-ish) but
// ABOVE the generic LM PKCS#15 parser (pkcs15-plugin, priority 900):
// OpenSC's full driver chain (srbeid, cardos, ias-ecc, openpgp, …)
// handles card-specific quirks the generic parser does not. Never
// matches by ATR — relies on canHandleConnection driving sc_pkcs15_bind()
// against the live session. kAtrs (from manifest.json) is intentionally empty.

std::string extractSubjectCN(const uint8_t* der, size_t len)
{
    const uint8_t* p = der;
    X509* cert = d2i_X509(nullptr, &p, static_cast<long>(len));
    if (!cert)
        return "(unreadable)";

    X509_NAME* subject = X509_get_subject_name(cert);
    char buf[256] = {};
    X509_NAME_get_text_by_NID(subject, NID_commonName, buf, sizeof(buf));

    std::string cn(buf);
    X509_free(cert);
    return cn.empty() ? "(no CN)" : cn;
}

// Per-session OpenSC binding state. Owned by the plugin's session map,
// keyed by PCSCConnection*. A fresh entry is created on canHandleConnection()
// and torn down by clearSession() (invoked from clearCredentials() and the
// plugin destructor). Shape mirrors the EMRTD plugin's SessionContext.
struct OpenSCSession
{
    sc_context_t* ctx = nullptr;
    sc_card_t* card = nullptr;
    sc_pkcs15_card_t* p15card = nullptr;
    std::string readerName;
    bool hasPKI = false;
};

class OpenSCCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    OpenSCCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::opensc::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::opensc::kDisplayName},
                    /*priority=*/800);
    }

    ~OpenSCCardPlugin() override
    {
        std::lock_guard lock(mtx);
        for (auto& [key, session] : sessions) {
            releaseSession(session);
        }
        sessions.clear();
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::opensc::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::opensc::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);

        // Start a fresh session for this connection, tearing down any prior
        // state keyed to the same PCSCConnection* (re-entrancy safety on
        // card re-insert against the same reader).
        auto it = sessions.find(&conn);
        if (it != sessions.end()) {
            releaseSession(it->second);
            sessions.erase(it);
        }

        OpenSCSession session;
        session.readerName = conn.readerName();

        int rc = sc_establish_context(&session.ctx, "librescrs");
        if (rc < 0)
            return false;

        sc_reader_t* reader = sc_ctx_get_reader_by_name(session.ctx, session.readerName.c_str());
        if (!reader) {
            releaseSession(session);
            return false;
        }

        rc = sc_connect_card(reader, &session.card);
        if (rc < 0) {
            releaseSession(session);
            return false;
        }

        rc = sc_pkcs15_bind(session.card, nullptr, &session.p15card);
        if (rc < 0) {
            releaseSession(session);
            return false;
        }

        // Detect PKI presence (PIN + RSA objects). No longer exposed
        // externally — kept for diagnostic/read-path hinting.
        sc_pkcs15_object_t* pinObjs[8];
        int pinCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 8);

        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        session.hasPKI = (pinCount > 0 || keyCount > 0);

        sessions.emplace(&conn, std::move(session));
        return true;
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& cardSession,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            LibreSCRS::Plugin::CardData data;
            data.cardType = "opensc";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
            std::lock_guard lock(mtx);
            auto it = sessions.find(&conn);
            if (it == sessions.end() || !it->second.p15card) {
                return ReadResult::unsupportedCard(
                    LibreSCRS::Auth::ErrorKeys::unsupportedCard(),
                    std::string{"opensc session not bound — canHandleConnection was not called or failed"});
            }
            auto& session = it->second;

            // Token info group. Field keys ("label" / "serial_number" /
            // "manufacturer") MUST match the well-known token-header keys
            // GUI hosts use to localise the row labels; the same keys are
            // emitted by readTokenInfo() below, keeping the two surfaces
            // consistent.
            LibreSCRS::Plugin::CardFieldGroup tokenGroup;
            tokenGroup.groupKey = "token";
            tokenGroup.groupLabel = "Token Info";

            auto* ti = session.p15card->tokeninfo;
            if (ti) {
                auto addField = [&](const std::string& key, const std::string& label, const char* val) {
                    if (val && val[0] != '\0') {
                        std::string s(val);
                        tokenGroup.fields.push_back(
                            {key, label, LibreSCRS::Plugin::FieldType::Text, {s.begin(), s.end()}});
                    }
                };
                addField("label", "Label", ti->label);
                addField("serial_number", "Serial Number", ti->serial_number);
                addField("manufacturer", "Manufacturer", ti->manufacturer_id);

                // Decode flags to human-readable string
                std::string flagStr;
                if (ti->flags & SC_PKCS15_TOKEN_PRN_GENERATION)
                    flagStr += "PRN ";
                if (ti->flags & SC_PKCS15_TOKEN_LOGIN_REQUIRED)
                    flagStr += "Login required ";
                if (!flagStr.empty()) {
                    flagStr.pop_back(); // remove trailing space
                    tokenGroup.fields.push_back(
                        {"flags", "Flags", LibreSCRS::Plugin::FieldType::Text, {flagStr.begin(), flagStr.end()}});
                }
            }
            emitGroup(std::move(tokenGroup));

            // Certificates summary group
            sc_pkcs15_object_t* certObjs[16];
            int certCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_CERT_X509, certObjs, 16);

            if (certCount > 0) {
                LibreSCRS::Plugin::CardFieldGroup certGroup;
                certGroup.groupKey = "certificates";
                certGroup.groupLabel = "Certificates";

                for (int i = 0; i < certCount; ++i) {
                    auto* certInfo = static_cast<sc_pkcs15_cert_info_t*>(certObjs[i]->data);
                    sc_pkcs15_cert_t* cert = nullptr;
                    int rc = sc_pkcs15_read_certificate(session.p15card, certInfo, 0, &cert);

                    std::string cn = "(unreadable)";
                    if (rc == 0 && cert) {
                        cn = extractSubjectCN(cert->data.value, cert->data.len);
                        sc_pkcs15_free_certificate(cert);
                    }

                    std::string key = "cert_" + std::to_string(i);
                    std::string label =
                        certObjs[i]->label[0] ? certObjs[i]->label : ("Certificate " + std::to_string(i));
                    certGroup.fields.push_back(
                        {key, label, LibreSCRS::Plugin::FieldType::Text, {cn.begin(), cn.end()}});
                }
                emitGroup(std::move(certGroup));
            }

            // PINs group — mirrors pkcs15-plugin layout: label → "tries left: N".
            // tries_left == -1 (e.g. PIV iso7816 after VERIFY SUCCESS) renders as "unknown".
            sc_pkcs15_object_t* pinObjsAll[8];
            int pinCountAll = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjsAll, 8);
            if (pinCountAll > 0) {
                LibreSCRS::Plugin::CardFieldGroup pinGroup;
                pinGroup.groupKey = "pins";
                pinGroup.groupLabel = "PINs";

                for (int i = 0; i < pinCountAll; ++i) {
                    auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjsAll[i]->data);
                    std::string label = pinObjsAll[i]->label[0] ? pinObjsAll[i]->label : ("PIN " + std::to_string(i));
                    std::string triesStr =
                        (authInfo && authInfo->tries_left >= 0) ? std::to_string(authInfo->tries_left) : "unknown";
                    std::string value = "tries left: " + triesStr;
                    std::string key = "pin_" + label;
                    pinGroup.fields.push_back(
                        {key, label, LibreSCRS::Plugin::FieldType::Text, {value.begin(), value.end()}});
                }
                emitGroup(std::move(pinGroup));
            }

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"opensc readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"opensc readCard failed (unknown error)"});
        }
    }

    LibreSCRS::Plugin::CardFieldGroup readTokenInfo(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        // Best-effort token-info read mirroring the pkcs15-plugin contract.
        // The group key/label are populated up-front so the presentation
        // layer can render its placeholder header from an empty group when
        // nothing could be read (no bound p15card, no tokeninfo).
        //
        // Field keys ("label", "serial_number", "manufacturer") are the
        // well-known token-header keys consumed by GUI hosts; cross-plugin
        // key drift would silently demote to placeholder rendering even
        // when the data is present.
        LibreSCRS::Plugin::CardFieldGroup group;
        group.groupKey = "token";
        group.groupLabel = "Token Info";

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return group;

        auto* ti = it->second.p15card->tokeninfo;
        if (!ti)
            return group;

        // CardFieldGroup::addText throws on (empty value, empty fields) by
        // design — skip empty values up-front so a single missing field can
        // never cascade into a fully empty group.
        auto safeAddText = [&](std::string_view key, std::string_view label, const char* value) {
            if (!value || value[0] == '\0')
                return;
            std::string_view sv(value);
            try {
                group.addText(key, label, sv);
            } catch (const std::exception& ex) {
                std::clog << "[librescrs.opensc.plugin] readTokenInfo: addText(" << key << ") threw: " << ex.what()
                          << "\n";
            } catch (...) {
                std::clog << "[librescrs.opensc.plugin] readTokenInfo: addText threw (non-std exception)\n";
            }
        };

        safeAddText("label", "Label", ti->label);
        safeAddText("serial_number", "Serial Number", ti->serial_number);
        safeAddText("manufacturer", "Manufacturer", ti->manufacturer_id);
        return group;
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::CertificateData> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* certObjs[16];
        int certCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_CERT_X509, certObjs, 16);

        for (int i = 0; i < certCount; ++i) {
            auto* certInfo = static_cast<sc_pkcs15_cert_info_t*>(certObjs[i]->data);
            sc_pkcs15_cert_t* cert = nullptr;
            int rc = sc_pkcs15_read_certificate(session.p15card, certInfo, 0, &cert);
            if (rc < 0 || !cert)
                continue;

            LibreSCRS::Plugin::CertificateData cd;
            cd.label = certObjs[i]->label;
            cd.derBytes.assign(cert->data.value, cert->data.value + cert->data.len);

            // Try to find associated private key for FID and key size
            sc_pkcs15_object_t* keyObj = nullptr;
            rc = sc_pkcs15_find_prkey_by_id(session.p15card, &certInfo->id, &keyObj);
            if (rc == 0 && keyObj) {
                auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObj->data);
                cd.keyFID = static_cast<std::uint16_t>(keyInfo->key_reference);
                cd.keySizeBits = static_cast<std::uint16_t>(keyInfo->modulus_length);
            }

            sc_pkcs15_free_certificate(cert);
            result.push_back(std::move(cd));
        }

        return result;
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& cardSession,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return {};
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0)
            return {};

        auto pinView = pin.view();
        int rc = sc_pkcs15_verify_pin(session.p15card, pinObjs[0], reinterpret_cast<const uint8_t*>(pinView.data()),
                                      pinView.size());

        // Refresh tries_left from card (verify may not update auth_info on all drivers)
        sc_pkcs15_get_pin_info(session.p15card, pinObjs[0]);
        auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjs[0]->data);

        LibreSCRS::Plugin::PINResult result;
        if (authInfo->tries_left >= 0)
            result.retriesLeft = authInfo->tries_left;
        result.blocked = (authInfo->tries_left == 0);
        if (rc == 0)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (result.blocked)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (result.retriesLeft.has_value())
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return result;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry>
    getPINList(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::PinStatusEntry> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[8];
        int pinCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 8);
        if (pinCount <= 0)
            return result;

        for (int i = 0; i < pinCount; ++i) {
            auto* info = static_cast<const sc_pkcs15_auth_info_t*>(pinObjs[i]->data);
            if (!info)
                continue;

            LibreSCRS::Plugin::PinStatusEntry entry;
            entry.label = pinObjs[i]->label[0] ? pinObjs[i]->label : "PIN";
            entry.reference = static_cast<std::uint8_t>(info->attrs.pin.reference & 0xff);

            // tries_left semantics: -1 = unknown (e.g. PIV iso7816 after VERIFY
            // SUCCESS — card does not surface remaining count); >= 0 = real count,
            // 0 means blocked.
            if (info->tries_left >= 0) {
                entry.retriesLeft = info->tries_left;
                entry.blocked = (info->tries_left == 0);
            }

            entry.initialized = (info->attrs.pin.flags & SC_PKCS15_PIN_FLAG_INITIALIZED) != 0;

            if (info->attrs.pin.min_length > 0)
                entry.minLength = info->attrs.pin.min_length;
            if (info->attrs.pin.max_length > 0)
                entry.maxLength = info->attrs.pin.max_length;

            const bool isPuk = (info->attrs.pin.flags & SC_PKCS15_PIN_FLAG_UNBLOCKING_PIN) != 0;
            const bool isSoPin = (info->attrs.pin.flags & SC_PKCS15_PIN_FLAG_SO_PIN) != 0;
            const bool changeDisabled = (info->attrs.pin.flags & SC_PKCS15_PIN_FLAG_CHANGE_DISABLED) != 0;
            entry.canChange = !isPuk && !isSoPin && !changeDisabled;

            result.push_back(std::move(entry));
        }
        return result;
    }

    LibreSCRS::Plugin::PINResult changePIN(LibreSCRS::SmartCard::CardSession& cardSession,
                                           std::string_view /*pinLabel*/, const LibreSCRS::Secure::String& oldPin,
                                           const LibreSCRS::Secure::String& newPin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card) {
            LibreSCRS::Plugin::PINResult r;
            r.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return r;
        }
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0) {
            LibreSCRS::Plugin::PINResult r;
            r.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return r;
        }

        auto oldView = oldPin.view();
        auto newView = newPin.view();
        int rc = sc_pkcs15_change_pin(session.p15card, pinObjs[0], reinterpret_cast<const uint8_t*>(oldView.data()),
                                      oldView.size(), reinterpret_cast<const uint8_t*>(newView.data()), newView.size());

        // Refresh tries_left from card
        sc_pkcs15_get_pin_info(session.p15card, pinObjs[0]);
        auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjs[0]->data);
        LibreSCRS::Plugin::PINResult result;
        if (authInfo->tries_left >= 0)
            result.retriesLeft = authInfo->tries_left;
        result.blocked = (authInfo->tries_left == 0);
        if (rc == 0)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (result.blocked)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (result.retriesLeft.has_value())
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return result;
    }

    std::optional<int> getPINTriesLeft(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return std::nullopt;
        auto& session = it->second;

        sc_pkcs15_object_t* pinObjs[4];
        int count = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_AUTH_PIN, pinObjs, 4);
        if (count <= 0)
            return std::nullopt;

        int rc = sc_pkcs15_get_pin_info(session.p15card, pinObjs[0]);
        if (rc < 0)
            return std::nullopt;
        auto* authInfo = static_cast<sc_pkcs15_auth_info_t*>(pinObjs[0]->data);
        if (authInfo->tries_left < 0)
            return std::nullopt;
        return authInfo->tries_left;
    }

    LibreSCRS::Plugin::SignResult doSign(LibreSCRS::SmartCard::CardSession& cardSession, std::uint16_t keyReference,
                                         std::span<const std::uint8_t> data,
                                         LibreSCRS::Plugin::SignMechanism mechanism) const override
    {
        auto pluginError = []() {
            LibreSCRS::Plugin::SignResult r;
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
            return r;
        };

        // 4.0 ABI v6 reserves the ECDSA_SHA{256,384,512} mechanisms. This plugin
        // only supports RSA_PKCS — surface anything else as NotImplemented
        // so callers can route to an ECDSA-capable plugin (or a future
        // extension of this driver) instead of producing a silently RSA-
        // signed blob for an ECDSA request.
        if (mechanism != LibreSCRS::Plugin::SignMechanism::RSA_PKCS) {
            LibreSCRS::Plugin::SignResult r;
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::NotImplemented;
            return r;
        }

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return pluginError();
        auto& session = it->second;

        // Find private key by reference
        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        sc_pkcs15_object_t* targetKey = nullptr;
        for (int i = 0; i < keyCount; ++i) {
            auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObjs[i]->data);
            if (static_cast<uint16_t>(keyInfo->key_reference) == keyReference) {
                targetKey = keyObjs[i];
                break;
            }
        }
        if (!targetKey)
            return pluginError();

        auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(targetKey->data);
        size_t sigLen = keyInfo->modulus_length / 8; // RSA signature length in bytes
        std::vector<uint8_t> sig(sigLen);

        int rc = sc_pkcs15_compute_signature(session.p15card, targetKey,
                                             SC_ALGORITHM_RSA_PAD_PKCS1_TYPE_01 | SC_ALGORITHM_RSA_HASH_NONE,
                                             data.data(), data.size(), sig.data(), sig.size(), nullptr);

        if (rc < 0)
            return pluginError();
        sig.resize(static_cast<size_t>(rc));
        LibreSCRS::Plugin::SignResult result;
        result.signature = std::move(sig);
        result.outcome = LibreSCRS::Plugin::SignResultOutcome::Ok;
        return result;
    }

    std::vector<LibreSCRS::Plugin::KeyReference>
    discoverKeyReferences(LibreSCRS::SmartCard::CardSession& cardSession) const override
    {
        std::vector<LibreSCRS::Plugin::KeyReference> result;

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
        std::lock_guard lock(mtx);
        auto it = sessions.find(&conn);
        if (it == sessions.end() || !it->second.p15card)
            return result;
        auto& session = it->second;

        sc_pkcs15_object_t* keyObjs[8];
        int keyCount = sc_pkcs15_get_objects(session.p15card, SC_PKCS15_TYPE_PRKEY_RSA, keyObjs, 8);

        for (int i = 0; i < keyCount; ++i) {
            auto* keyInfo = static_cast<sc_pkcs15_prkey_info_t*>(keyObjs[i]->data);
            result.push_back({keyObjs[i]->label, static_cast<std::uint16_t>(keyInfo->key_reference)});
        }

        return result;
    }

    void clearCredentials(LibreSCRS::SmartCard::CardSession& cardSession) noexcept override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(cardSession);
            std::lock_guard lock(mtx);
            auto it = sessions.find(&conn);
            if (it != sessions.end()) {
                releaseSession(it->second);
                sessions.erase(it);
            }
        } catch (...) {
            // clearCredentials is noexcept — swallow unwrap/lock failures.
        }
    }

private:
    // Release libopensc resources owned by a single session. Safe to call
    // on a partially-initialised session (fields are checked for null).
    // Does not touch the sessions map — callers are responsible for erase.
    static void releaseSession(OpenSCSession& session)
    {
        if (session.p15card) {
            sc_pkcs15_unbind(session.p15card);
            session.p15card = nullptr;
        }
        if (session.card) {
            sc_disconnect_card(session.card);
            session.card = nullptr;
        }
        if (session.ctx) {
            sc_release_context(session.ctx);
            session.ctx = nullptr;
        }
        session.hasPKI = false;
    }

    mutable std::mutex mtx;
    mutable std::map<const LibreSCRS::SmartCard::Internal::PCSCConnection*, OpenSCSession> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(OpenSCCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
