# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2026 hirashix0
#
# Helper -P script: read IN_FILE, emit a C++ translation unit defining
#   extern const unsigned char SYMBOL[];
#   extern const unsigned int  SYMBOLLen;
# We use `unsigned int` (not size_t) so the constant matches the harness
# declaration without needing a header include for size_t.
if(NOT IN_FILE OR NOT OUT_FILE OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedFuzzCert: IN_FILE, OUT_FILE, SYMBOL required")
endif()

file(READ "${IN_FILE}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

set(BODY "")
set(IDX 0)
while(IDX LESS HEX_LEN)
    string(SUBSTRING "${HEX_CONTENT}" ${IDX} 2 BYTE)
    if(BODY STREQUAL "")
        set(BODY "0x${BYTE}")
    else()
        math(EXPR CHUNK "(${IDX} / 2) % 16")
        if(CHUNK EQUAL 0)
            string(APPEND BODY ",\n    0x${BYTE}")
        else()
            string(APPEND BODY ",0x${BYTE}")
        endif()
    endif()
    math(EXPR IDX "${IDX} + 2")
endwhile()

file(WRITE "${OUT_FILE}"
"// Auto-generated by fuzz/EmbedFuzzCert.cmake — do not edit.
// Embeds the test TL signing certificate (DER) as a C array for the
// fuzz_tl_signature_verifier harness. Source: test/fixtures/trust/.

extern \"C\" {
extern const unsigned char ${SYMBOL}[];
extern const unsigned int  ${SYMBOL}Len;
const unsigned char ${SYMBOL}[] = {
    ${BODY}
};
const unsigned int ${SYMBOL}Len = ${BYTE_LEN};
}
")
