// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include "scaffold_generator.h"
#include "output_formatter.h"

#include <format>
#include <sstream>

namespace card_mapper {

std::string generateProtocolHeader(const std::string& name, const ScanResult& scanResult)
{
    std::ostringstream out;

    // SPDX header
    out << "// SPDX-License-Identifier: LGPL-2.1-or-later\n";
    out << "// Auto-generated by card_mapper --discover --scaffold\n";
    out << "// Review and rename fields before use\n";
    out << "\n";
    out << "#pragma once\n";
    out << "\n";
    out << "#include <array>\n";
    out << "#include <cstdint>\n";
    out << "\n";
    out << "namespace " << name << "::protocol {\n";
    out << "\n";

    // ATR
    if (!scanResult.atr.empty()) {
        out << "// ATR: " << formatHex(scanResult.atr) << "\n";
        out << "\n";
    }

    // AIDs from detected applets
    int aidIndex = 0;
    for (const auto& applet : scanResult.detectedApplets) {
        for (const auto& aid : applet.aids) {
            out << "// AID\n";
            out << std::format("constexpr std::array<uint8_t, {}> kAID_{} = {{", aid.size(), aidIndex);
            for (size_t i = 0; i < aid.size(); ++i) {
                if (i > 0)
                    out << ", ";
                out << std::format("0x{:02X}", aid[i]);
            }
            out << "};\n";
            out << "\n";
            ++aidIndex;
        }
    }

    // File IDs from detected applets
    for (const auto& applet : scanResult.detectedApplets) {
        for (const auto& df : applet.dataFiles) {
            if (df.fidHi == 0 && df.fidLo == 0)
                continue;

            out << "// File ID: " << formatFid(df.fidHi, df.fidLo) << "\n";
            out << std::format("constexpr uint8_t kFile_{:02X}{:02X}_H = 0x{:02X};\n", df.fidHi, df.fidLo, df.fidHi);
            out << std::format("constexpr uint8_t kFile_{:02X}{:02X}_L = 0x{:02X};\n", df.fidHi, df.fidLo, df.fidLo);
            out << "\n";
        }
    }

    // TLV Tags from detected applets
    for (const auto& applet : scanResult.detectedApplets) {
        for (const auto& df : applet.dataFiles) {
            if (df.tags.empty())
                continue;

            out << "// TLV Tags (16-bit LE) \xe2\x80\x94 rename based on card spec\n";
            for (const auto& tag : df.tags) {
                out << std::format("constexpr uint16_t kTag_{:04X} = 0x{:04X};", tag.tag, tag.tag);
                if (!tag.type.empty()) {
                    out << "  // " << tag.type;
                }
                out << "\n";
            }
            out << "\n";
        }
    }

    // File tree info from rootNode children
    for (const auto& applet : scanResult.detectedApplets) {
        const auto& root = applet.rootNode;
        for (const auto& df : root.children) {
            for (const auto& ef : df.children) {
                if (ef.fidHi == 0 && ef.fidLo == 0)
                    continue;

                // Only emit if not already emitted as a data file
                bool alreadyEmitted = false;
                for (const auto& dataFile : applet.dataFiles) {
                    if (dataFile.fidHi == ef.fidHi && dataFile.fidLo == ef.fidLo) {
                        alreadyEmitted = true;
                        break;
                    }
                }
                if (alreadyEmitted)
                    continue;

                out << std::format("constexpr uint8_t kFile_{:02X}{:02X}_H = 0x{:02X};\n", ef.fidHi, ef.fidLo,
                                   ef.fidHi);
                out << std::format("constexpr uint8_t kFile_{:02X}{:02X}_L = 0x{:02X};\n", ef.fidHi, ef.fidLo,
                                   ef.fidLo);
                out << "\n";
            }
        }
    }

    out << "} // namespace " << name << "::protocol\n";

    return out.str();
}

} // namespace card_mapper
