// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <eidcard.h>
#include <eidtypes.h>
#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <LibreSCRS/Trust/TrustStore.h>
#include <pcsc_connection.h>

#include <filesystem>
#include <fstream>

#include "manifest.h" // generated by librescrs_add_plugin

namespace {

LibreSCRS::Plugin::CardFieldGroup personalGroup(const eidcard::FixedPersonalData& fp)
{
    LibreSCRS::Plugin::CardFieldGroup group;
    group.groupKey = "personal";
    group.groupLabel = "Personal Data";

    group.addText("personal_number", "Personal Number", fp.personalNumber);
    group.addText("surname", "Surname", fp.surname);
    group.addText("given_name", "Given Name", fp.givenName);
    group.addText("parent_given_name", "Parent Given Name", fp.parentGivenName);
    group.addText("sex", "Sex", fp.sex);
    group.addText("place_of_birth", "Place of Birth", fp.placeOfBirth);
    group.addText("community_of_birth", "Community of Birth", fp.communityOfBirth);
    group.addText("state_of_birth", "State of Birth", fp.stateOfBirth);
    group.addText("date_of_birth", "Date of Birth", fp.dateOfBirth);
    group.addText("nationality", "Nationality", fp.nationalityFull);
    group.addText("status_of_foreigner", "Status of Foreigner", fp.statusOfForeigner);

    return group;
}

LibreSCRS::Plugin::CardFieldGroup addressGroup(const eidcard::VariablePersonalData& vp)
{
    LibreSCRS::Plugin::CardFieldGroup group;
    group.groupKey = "address";
    group.groupLabel = "Address";

    group.addText("state", "State", vp.state);
    group.addText("community", "Community", vp.community);
    group.addText("place", "Place", vp.place);
    group.addText("street", "Street", vp.street);
    group.addText("house_number", "House Number", vp.houseNumber);
    group.addText("house_letter", "House Letter", vp.houseLetter);
    group.addText("entrance", "Entrance", vp.entrance);
    group.addText("floor", "Floor", vp.floor);
    group.addText("apartment_number", "Apartment Number", vp.apartmentNumber);

    return group;
}

LibreSCRS::Plugin::CardFieldGroup documentGroup(const eidcard::DocumentData& doc)
{
    LibreSCRS::Plugin::CardFieldGroup group;
    group.groupKey = "document";
    group.groupLabel = "Document Data";

    group.addText("doc_reg_no", "Registration Number", doc.docRegNo);
    group.addText("document_type", "Document Type", doc.documentType);
    group.addText("document_serial_number", "Serial Number", doc.documentSerialNumber);
    group.addText("issuing_date", "Issuing Date", doc.issuingDate);
    group.addText("expiry_date", "Expiry Date", doc.expiryDate);
    group.addText("issuing_authority", "Issuing Authority", doc.issuingAuthority);

    return group;
}

// 4.0 hardening: pluginId / displayName / capabilities / kAtrs come
// from the per-plugin manifest.json via the generated manifest.h header.
// The two known card-family ATRs (Apollo, Gemalto) are encoded with masks
// in the manifest — the meaningful prefix bytes get mask 0xFF and the
// trailing bytes mask 0x00 (don't care).

class EidCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    EidCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::rs_eid::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::rs_eid::kDisplayName},
                    /*priority=*/100);
    }

    /// @brief Trust subsystem: cache the unified TrustStore for use during card-data
    ///        signature verification in @ref readCard. Single injection point
    ///        from CardPluginService construction; pointer stays valid for
    ///        plugin lifetime.
    /// @since 4.0 — NVI seam (LM-CRIT review): the public
    ///        @ref CardPlugin::setTrustStore now wraps with a single-shot
    ///        guard, calling this protected virtual at most once per plugin
    ///        instance. Method is noexcept by contract; pure pointer move,
    ///        no allocation or throw surface.
    void doSetTrustStore(std::shared_ptr<const LibreSCRS::Trust::TrustStore> store) noexcept override
    {
        trustStore = std::move(store);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::rs_eid::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::rs_eid::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        try {
            // Try to detect card type by selecting eID applet AIDs
            eidcard::EIdCard card(conn);
            return card.getCardType() != eidcard::CardType::Unknown;
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            eidcard::EIdCard card(conn);

            LibreSCRS::Plugin::CardData data;
            data.cardType = "rs-eid";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            // 1. Meta (card type detection — fast, single SELECT)
            auto cardType = card.getCardType();
            {
                LibreSCRS::Plugin::CardFieldGroup meta;
                meta.groupKey = "meta";
                meta.groupLabel = "Card Metadata";
                std::string ct;
                switch (cardType) {
                case eidcard::CardType::Apollo2008:
                    ct = "Apollo2008";
                    break;
                case eidcard::CardType::Gemalto2014:
                    ct = "Gemalto2014";
                    break;
                case eidcard::CardType::ForeignerIF2020:
                    ct = "ForeignerIF2020";
                    break;
                default:
                    ct = "Unknown";
                    break;
                }
                meta.fields.push_back(
                    {"card_type", "Card Type", LibreSCRS::Plugin::FieldType::Text, {ct.begin(), ct.end()}});
                emitGroup(std::move(meta));
            }

            // 2. Personal data (card I/O: readFixedPersonalData)
            auto fixedPersonal = card.readFixedPersonalData();
            emitGroup(personalGroup(fixedPersonal));

            // 3. Address (card I/O: readVariablePersonalData)
            auto variablePersonal = card.readVariablePersonalData();
            {
                auto addrGrp = addressGroup(variablePersonal);
                if (!variablePersonal.addressDate.empty()) {
                    addrGrp.fields.push_back(
                        {"address_date",
                         "Address Date",
                         LibreSCRS::Plugin::FieldType::Text,
                         {variablePersonal.addressDate.begin(), variablePersonal.addressDate.end()}});
                }
                emitGroup(std::move(addrGrp));
            }

            // 4. Document (card I/O: readDocumentData)
            auto documentData = card.readDocumentData();
            emitGroup(documentGroup(documentData));

            // 5. Photo (card I/O: readPortrait — slowest)
            auto photo = card.readPortrait();
            if (!photo.empty()) {
                LibreSCRS::Plugin::CardFieldGroup photoGroup;
                photoGroup.groupKey = "photo";
                photoGroup.groupLabel = "Photo";
                photoGroup.fields.push_back({"photo", "Photo", LibreSCRS::Plugin::FieldType::Photo, photo});
                emitGroup(std::move(photoGroup));
            }

            // 6. Verification — feed trust anchors from the injected TrustStore.
            //    enumerableAnchors() returns the provider anchors only (bundled certs +
            //    Trusted-List-derived anchors); the OS system store is NOT included (it
            //    is consulted only by TrustStore::validateChain, a different surface).
            //    If no TrustStore was injected (registry constructed without one,
            //    e.g. minimal test harnesses), card verification proceeds without
            //    trust anchors — chain validation will mark all chains untrusted.
            if (trustStore) {
                for (const auto& anchor : trustStore->enumerableAnchors()) {
                    card.addTrustedCertificate(anchor.certificateDer);
                }
            }

            auto toStr = [](eidcard::VerificationResult r) -> std::string {
                switch (r) {
                case eidcard::VerificationResult::Valid:
                    return "valid";
                case eidcard::VerificationResult::Invalid:
                    return "invalid";
                default:
                    return "unknown";
                }
            };

            auto cardVerification = card.verifyCard();
            auto fixedVerification = card.verifyFixedData();
            auto variableVerification = card.verifyVariableData();

            // Emit verification as a separate group for the streaming path
            LibreSCRS::Plugin::CardFieldGroup verGroup;
            verGroup.groupKey = "verification";
            verGroup.groupLabel = "Verification";
            auto addVerField = [&](const std::string& key, const std::string& val) {
                verGroup.fields.push_back({key, key, LibreSCRS::Plugin::FieldType::Text, {val.begin(), val.end()}});
            };
            addVerField("card_verification", toStr(cardVerification));
            addVerField("fixed_verification", toStr(fixedVerification));
            addVerField("variable_verification", toStr(variableVerification));
            emitGroup(std::move(verGroup));

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"rs-eid readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"rs-eid readCard failed (unknown error)"});
        }
    }

private:
    /// @brief Unified TrustStore injected once by CardPluginService at
    ///        construction. Used during card-data signature verification
    ///         May be null if registry was constructed without one.
    std::shared_ptr<const LibreSCRS::Trust::TrustStore> trustStore;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(EidCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
