// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include "health_groups.h"

#include <healthcard.h>
#include <healthtypes.h>
#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <pcsc_connection.h>

#include "manifest.h" // generated by librescrs_add_plugin

namespace {

// 4.0 hardening: rs-health defers all matching to canHandleConnection
// (probe via AID/SELECT). kAtrs (from manifest.json) is intentionally empty.

class HealthCardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    HealthCardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::rs_health::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::rs_health::kDisplayName},
                    /*priority=*/200);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::rs_health::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::rs_health::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        try {
            return healthcard::HealthCard::probe(conn);
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            healthcard::HealthCard card(conn);
            auto doc = card.readDocumentData();

            // The group shape lives in the tested builder (health_groups.h):
            // guarded adds — a self-carrier card has every carrier field
            // empty, and an unguarded addText on that shape throws — and
            // empty groups are never emitted.
            LibreSCRS::Plugin::CardData data = healthcard::buildHealthGroups(doc);
            if (onGroup) {
                for (const auto& group : data.groups)
                    onGroup(data.cardType, group);
            }
            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"rs-health readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"rs-health readCard failed (unknown error)"});
        }
    }
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(HealthCardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
