// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <cardedge.h>
#include <pki_applet_guard.h>
#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <apdu.h>
#include <smartcard/pcsc_connection.h>

#include <string_view>

#include "manifest.h" // generated by librescrs_add_plugin (A5)

namespace {

// PKCS#15 AID — same as cardedge::protocol::AID_PKCS15 (inlined to avoid private header dependency)
const std::vector<uint8_t> AID_PKCS15 = {0xA0, 0x00, 0x00, 0x00, 0x63, 0x50, 0x4B, 0x43, 0x53, 0x2D, 0x31, 0x35};

// A5 (4.0 hardening): pluginId / displayName / capabilities / kAtrs come
// from the per-plugin manifest.json via the generated manifest.h header.
// CardEdge defers all ATR matching to canHandleConnection (the on-card
// PKI applet is detected by SELECT-AID + a PKCS#15 root-DF probe), so
// kAtrs is intentionally empty.

class CardEdgePlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    CardEdgePlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::cardedge::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::cardedge::kDisplayName},
                    /*priority=*/840);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::cardedge::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::cardedge::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        try {
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            // Phase 1: SELECT PKCS#15 AID
            auto resp = conn.transmit(smartcard::selectByAID(AID_PKCS15));
            if (!resp.isSuccess())
                return false;

            // Phase 2: SELECT root dir 0x7000 (CardEdge-specific, not present on standard PKCS#15)
            resp = conn.transmit(smartcard::selectByFileId(0x70, 0x00));
            return resp.isSuccess();
        } catch (...) {
            return false;
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& /*session*/,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            LibreSCRS::Plugin::CardData data;
            data.cardType = "cardedge";

            LibreSCRS::Plugin::CardFieldGroup meta;
            meta.groupKey = "meta";
            meta.groupLabel = "Card Metadata";
            std::string name = "CardEdge (Serbian PKI)";
            meta.fields.push_back(
                {"card_type", "Card Type", LibreSCRS::Plugin::FieldType::Text, {name.begin(), name.end()}});
            if (onGroup)
                onGroup(data.cardType, meta);
            data.groups.push_back(std::move(meta));

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"cardedge readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"cardedge readCard failed (unknown error)"});
        }
    }

    LibreSCRS::Plugin::CardFieldGroup readTokenInfo(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto info = cardedge::readTokenInfo(conn);

        // Fallback for cards without EF(TokenInfo)
        if (info.label.empty())
            info.label = "CardEdge PKI Token";
        if (info.manufacturer.empty())
            info.manufacturer = "CardEdge";

        LibreSCRS::Plugin::CardFieldGroup group;
        group.groupKey = "token";
        group.groupLabel = "Token Info";
        group.addText("label", "Label", info.label);
        group.addText("serial_number", "Serial Number", info.serialNumber);
        group.addText("manufacturer", "Manufacturer", info.manufacturer);
        return group;
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto certs = cardedge::readCertificates(conn);

        std::vector<LibreSCRS::Plugin::CertificateData> result;
        for (const auto& cert : certs) {
            LibreSCRS::Plugin::CertificateData cd;
            cd.label = cert.label;
            cd.derBytes = cert.derBytes;
            // Internal cardedge::CertificateData uses 0 as "unknown" sentinel;
            // map that to a disengaged optional on the public surface per
            // ABI v6 (4.0).
            if (cert.keyFID != 0)
                cd.keyFID = cert.keyFID;
            if (cert.keySizeBits != 0)
                cd.keySizeBits = cert.keySizeBits;
            result.push_back(std::move(cd));
        }
        return result;
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& session,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto r = cardedge::verifyPIN(conn, pin.view());
        LibreSCRS::Plugin::PINResult out;
        if (r.retriesLeft >= 0)
            out.retriesLeft = r.retriesLeft;
        out.blocked = r.blocked;
        if (r.success)
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (out.blocked)
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (out.retriesLeft.has_value())
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return out;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry> getPINList(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto result = cardedge::getPINTriesLeft(conn);
        LibreSCRS::Plugin::PinStatusEntry entry;
        entry.label = "PIN";
        entry.reference = 0x80;
        if (result.retriesLeft >= 0)
            entry.retriesLeft = result.retriesLeft;
        entry.initialized = true;
        entry.blocked = result.blocked;
        entry.minLength = std::size_t{4};
        entry.maxLength = std::size_t{8};
        entry.canChange = true;
        return {entry};
    }

    LibreSCRS::Plugin::PINResult changePIN(LibreSCRS::SmartCard::CardSession& session, std::string_view /*pinLabel*/,
                                           const LibreSCRS::Secure::String& oldPin,
                                           const LibreSCRS::Secure::String& newPin) const override
    {
        // CardEdge exposes a single PIN on the PKI applet — pinLabel is accepted
        // for API symmetry but not used to select between multiple PINs.
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto r = cardedge::changePIN(conn, oldPin.view(), newPin.view());
        LibreSCRS::Plugin::PINResult result;
        if (r.retriesLeft >= 0)
            result.retriesLeft = r.retriesLeft;
        result.blocked = r.blocked;
        if (r.success)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (result.blocked)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (result.retriesLeft.has_value())
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return result;
    }

    LibreSCRS::Plugin::SignResult doSign(LibreSCRS::SmartCard::CardSession& session, std::uint16_t keyReference,
                                         std::span<const std::uint8_t> data,
                                         LibreSCRS::Plugin::SignMechanism mechanism) const override
    {
        // CardEdge on the RS eID is RSA-only at the applet level. 4.0 ABI v6
        // reserves ECDSA_SHA{256,384,512} mechanisms; surface anything
        // other than RSA_PKCS as NotImplemented rather than silently
        // RSA-signing an ECDSA request.
        if (mechanism != LibreSCRS::Plugin::SignMechanism::RSA_PKCS) {
            LibreSCRS::Plugin::SignResult r;
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::NotImplemented;
            return r;
        }

        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto sig = cardedge::signData(conn, keyReference, {data.begin(), data.end()});
        LibreSCRS::Plugin::SignResult result;
        const bool succeeded = !sig.empty();
        result.signature = std::move(sig);
        result.outcome =
            succeeded ? LibreSCRS::Plugin::SignResultOutcome::Ok : LibreSCRS::Plugin::SignResultOutcome::PluginError;
        return result;
    }

    std::vector<LibreSCRS::Plugin::KeyReference>
    discoverKeyReferences(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        cardedge::PkiAppletGuard guard(conn);
        auto internal = cardedge::discoverKeyReferences(conn);
        std::vector<LibreSCRS::Plugin::KeyReference> result;
        result.reserve(internal.size());
        for (auto& kv : internal) {
            result.push_back({std::move(kv.first), kv.second});
        }
        return result;
    }
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(CardEdgePlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
