# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileCopyrightText: 2026 hirashix0

# Invoked via -P. Reads IN_FILE, writes OUT_FILE as a C++ translation unit
# defining SYMBOL and SYMBOLSize.
if(NOT IN_FILE OR NOT OUT_FILE OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedBinaryRun: IN_FILE, OUT_FILE, SYMBOL required")
endif()

file(READ "${IN_FILE}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# Capture the input filename for the generated banner so the licence
# attribution points at the right upstream package.
get_filename_component(IN_FILE_NAME "${IN_FILE}" NAME)

# Emit as 0xNN,0xNN,... 16 per line.
set(BODY "")
set(IDX 0)
while(IDX LESS HEX_LEN)
    string(SUBSTRING "${HEX_CONTENT}" ${IDX} 2 BYTE)
    if(BODY STREQUAL "")
        set(BODY "0x${BYTE}")
    else()
        math(EXPR CHUNK "(${IDX} / 2) % 16")
        if(CHUNK EQUAL 0)
            string(APPEND BODY ",\n    0x${BYTE}")
        else()
            string(APPEND BODY ",0x${BYTE}")
        endif()
    endif()
    math(EXPR IDX "${IDX} + 2")
endwhile()

file(WRITE "${OUT_FILE}"
"// Auto-generated by cmake/EmbedBinaryRun.cmake — do not edit.
//
// This file embeds the byte contents of \"${IN_FILE_NAME}\" — see the
// upstream source's licence (typically thirdparty/<package>/LICENSE-*).
// The SPDX licence of this generated TU is derivative of the input
// file's licence and is NOT \"LGPL-2.1-or-later\" by default. For the
// bundled Liberation Sans font that licence is OFL-1.1
// (thirdparty/liberation-sans/LICENSE-OFL-1.1.txt). Do NOT edit by hand.

#include <cstddef>

extern \"C\" {
extern const unsigned char ${SYMBOL}[];
extern const size_t ${SYMBOL}Size;
const unsigned char ${SYMBOL}[] = {
    ${BODY}
};
const size_t ${SYMBOL}Size = ${BYTE_LEN};
}
")
