// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <pkcs15_card.h>
#include <pkcs15_types.h>

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Auth/PaceSecretKind.h>
#include <LibreSCRS/CancelToken.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/Secure/String.h>
#include <LibreSCRS/SecureChannel/ChannelErrors.h>
#include <LibreSCRS/SecureChannel/ISecureChannel.h>
#include <LibreSCRS/SecureChannel/PlainChannel.h>
#include <LibreSCRS/SmartCard/ActiveChannelHolder.h>
#include <LibreSCRS/SmartCard/AppletAid.h>
#include <LibreSCRS/SmartCard/CardSession.h>
#include <LibreSCRS/SmartCard/SmProtocolRequest.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <smartcard/pcsc_connection.h>

#include <algorithm>
#include <compare>
#include <cstdint>
#include <expected>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <string_view>
#include <variant>

#include "manifest.h" // generated by librescrs_add_plugin (A5)
#include "probe_trace.h"

namespace {

// A5 (4.0 hardening): generic PKCS#15 matches via SELECT-DF probe in
// canHandleConnection, never via ATR. kAtrs (from manifest.json) is
// intentionally empty.

/// @brief Per-session key — mirrors the emrtd-plugin shape.
struct SessionKey
{
    std::string readerName;
    std::uint64_t generation{0};

    auto operator<=>(const SessionKey&) const = default;
};

SessionKey makeSessionKey(LibreSCRS::SmartCard::CardSession& session)
{
    return SessionKey{session.readerName(), LibreSCRS::SmartCard::detail::sessionGeneration(session)};
}

/// @brief Plugin-side memory of whether this card session is PACE-gated.
///
/// Stage 5 moved PACE / SM ownership from this plugin to
/// @ref LibreSCRS::SmartCard::CardSession. The plugin only needs to know
/// *which* activation flavour to request for a given operation
/// (plain vs. PACE-CAN). The CAN itself is held by CardSession via
/// @ref CardSession::setPaceSecret. This struct is intentionally tiny.
struct SessionContext
{
    /// @brief @c true after a successful "PACE required" probe (canHandle
    ///        returned needsPace) or after @ref setCredentials("can", ...)
    ///        has been called. When false the plugin uses
    ///        @ref activateChannelFor (PlainChannel) instead of
    ///        @ref activateChannelWithSm.
    bool requiresPace{false};
};

LibreSCRS::SmartCard::AppletAid pkcs15AppletAid()
{
    return LibreSCRS::SmartCard::AppletAid::fromBytes(
        std::span<const std::uint8_t>{pkcs15::kPkcs15Aid.data(), pkcs15::kPkcs15Aid.size()});
}

/// @brief Result of a cheap reachability probe against the AID, used to
///        decide whether PACE is required.
enum class ProbeResult {
    Ok,         ///< Plain SELECT succeeded — no SM needed for this card.
    NeedsPace,  ///< Card returned 6982 — PACE must be run first.
    Unreachable ///< Other failure; treat as not-PKCS#15.
};

ProbeResult probeApplet(LibreSCRS::SmartCard::Internal::PCSCConnection& conn)
{
    std::vector<std::uint8_t> aid(pkcs15::kPkcs15Aid.begin(), pkcs15::kPkcs15Aid.end());
    auto aidResp = conn.transmit(LibreSCRS::SmartCard::Internal::selectByAID(aid, 0x0C));
    if (aidResp.isSuccess())
        return ProbeResult::Ok;
    if (aidResp.sw1 == 0x69 && aidResp.sw2 == 0x82)
        return ProbeResult::NeedsPace;
    return ProbeResult::Unreachable;
}

/// @brief Acquire an @ref ActiveChannelHolder appropriate for this session.
///
/// PACE-gated cards take the SM activation path
/// (@ref CardSession::activateChannelWithSm with @c PaceRequest{Can});
/// non-PACE cards take the plain path. The CAN — if needed — must have
/// been deposited in CardSession's cache via @ref setCredentials before
/// this call; CardSession's preflight short-circuits with
/// @c CredentialsRequired if neither a cached CAN nor a provider is
/// available. The Stage 4 PaceChannel installed by emrtd-plugin (if the
/// user came through the display flow first) is reused via §5.3b Case 2.
std::expected<LibreSCRS::SmartCard::ActiveChannelHolder, LibreSCRS::SecureChannel::ChannelActivationError>
acquireChannel(LibreSCRS::SmartCard::CardSession& session, bool requiresPace)
{
    auto aid = pkcs15AppletAid();
    if (requiresPace) {
        return session.activateChannelWithSm(
            aid, LibreSCRS::SmartCard::PaceRequest{LibreSCRS::Auth::PaceSecretKind::Can}, LibreSCRS::CancelToken{});
    }
    return session.activateChannelFor(aid, LibreSCRS::CancelToken{});
}

class PKCS15CardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    PKCS15CardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::pkcs15::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::pkcs15::kDisplayName},
                    /*priority=*/900);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::pkcs15::kCapabilities;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::pkcs15::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
        const auto mapKey = makeSessionKey(session);
        try {
            // Cheap, no-SM probe to decide between PlainChannel (RS eID,
            // PKS, AET) and PaceChannel (NAM CL, GEO CL) for subsequent
            // operations. The actual applet selection happens later through
            // CardSession::activateChannel{For,WithSm}.
            const auto state = probeApplet(conn);
            if (state == ProbeResult::Ok) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = false;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=true");
                return true;
            }
            if (state == ProbeResult::NeedsPace) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = true;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=needsPace");
                return true;
            }
            // Unreachable: try the full PKCS15Card probe path which includes
            // EF.DIR fallback (some cards expose PKCS#15 only through the
            // EF.DIR application registry, not via direct AID SELECT).
            LibreSCRS::SecureChannel::PlainChannel probeChannel(conn, LibreSCRS::SmartCard::AppletAid{});
            pkcs15::PKCS15Card card(probeChannel);
            if (card.probe()) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = false;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=true");
                return true;
            }
            LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=false");
            return false;
        } catch (...) {
            LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=false threw=true");
            return false;
        }
    }

    void setCredentials(LibreSCRS::SmartCard::CardSession& session, std::string_view key,
                        const LibreSCRS::Secure::String& value) override
    {
        if (key != "can")
            return;
        // CardSession owns the CAN cache from Stage 4 onwards; this plugin
        // simply forwards the secret. Successful PACE activation through
        // CardSession reuses the same cache slot whether the secret was
        // deposited by emrtd-plugin (display flow) or by us (direct sign).
        session.setPaceSecret(LibreSCRS::Auth::PaceSecretKind::Can, LibreSCRS::Secure::String{value.view()});
        std::lock_guard lock(stateMutex);
        sessions[makeSessionKey(session)].requiresPace = true;
    }

    void clearCredentials(LibreSCRS::SmartCard::CardSession& session) noexcept override
    {
        try {
            std::lock_guard lock(stateMutex);
            sessions.erase(makeSessionKey(session));
        } catch (...) {
            // clearCredentials is noexcept; swallow allocator faults.
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto holderResult = acquireChannel(session, requiresPaceFor(session));
            if (!holderResult)
                return mapActivationError(holderResult.error(), "pkcs15 doReadCard");
            auto holder = std::move(*holderResult);
            auto* channel = holder.activeChannel();
            if (channel == nullptr)
                return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                      "pkcs15 doReadCard: channel not active after activation");

            pkcs15::PKCS15Card card(*channel);
            LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=doReadCard");
            auto profile = card.readProfile();

            LibreSCRS::Plugin::CardData data;
            data.cardType = "pkcs15";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "token";
                group.groupLabel = "Token Info";
                group.addText("label", "Label", profile.tokenInfo.label);
                group.addText("serial_number", "Serial Number", profile.tokenInfo.serialNumber);
                group.addText("manufacturer", "Manufacturer", profile.tokenInfo.manufacturer);
                emitGroup(std::move(group));
            }

            if (!profile.certificates.empty()) {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "certificates";
                group.groupLabel = "Certificates";
                for (const auto& cert : profile.certificates) {
                    group.addText("cert_" + cert.label, cert.label, cert.label);
                }
                emitGroup(std::move(group));
            }

            if (!profile.pins.empty()) {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "pins";
                group.groupLabel = "PINs";
                for (const auto& pin : profile.pins) {
                    int tries = card.getPINTriesLeft(pin);
                    std::string triesStr = (tries >= 0) ? std::to_string(tries) : "unknown";
                    group.addText("pin_" + pin.label, pin.label, "tries left: " + triesStr);
                }
                emitGroup(std::move(group));
            }

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"pkcs15 readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"pkcs15 readCard failed (unknown error)"});
        }
    }

    LibreSCRS::Plugin::CardFieldGroup readTokenInfo(LibreSCRS::SmartCard::CardSession& session) const override
    {
        LibreSCRS::Plugin::CardFieldGroup group;
        group.groupKey = "token";
        group.groupLabel = "Token Info";

        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return group; // empty on activation failure; best-effort path
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr)
            return group;

        pkcs15::PKCS15Card card(*channel);
        auto info = card.readTokenInfo();
        group.addText("label", "Label", info.label);
        group.addText("serial_number", "Serial Number", info.serialNumber);
        group.addText("manufacturer", "Manufacturer", info.manufacturer);
        return group;
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& session) const override
    {
        std::vector<LibreSCRS::Plugin::CertificateData> result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return result;
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr)
            return result;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=readCertificates");
        auto profile = card.readProfile();

        for (const auto& cert : profile.certificates) {
            auto der = card.readCertificate(cert);
            if (der.empty())
                continue;

            LibreSCRS::Plugin::CertificateData cd;
            cd.label = cert.label;
            cd.derBytes = std::move(der);

            for (const auto& key : profile.privateKeys) {
                if (key.id == cert.id) {
                    if (key.path.size() >= 2) {
                        cd.keyFID = static_cast<std::uint16_t>((key.path[key.path.size() - 2] << 8) |
                                                               key.path[key.path.size() - 1]);
                    } else if (key.keyReference != 0) {
                        cd.keyFID = static_cast<std::uint16_t>(key.keyReference);
                    } else {
                        cd.keyFID = std::uint16_t{1};
                    }
                    if (key.keySizeBits != 0)
                        cd.keySizeBits = key.keySizeBits;
                    break;
                }
            }

            result.push_back(std::move(cd));
        }

        return result;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry> getPINList(LibreSCRS::SmartCard::CardSession& session) const override
    {
        std::vector<LibreSCRS::Plugin::PinStatusEntry> result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return result;
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr)
            return result;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=getPINList");
        auto profile = card.readProfile();

        for (const auto& pin : profile.pins) {
            LibreSCRS::Plugin::PinStatusEntry entry;
            entry.label = pin.label;
            entry.reference = pin.pinReference;
            entry.initialized = pin.initialized;

            if (pin.initialized) {
                try {
                    int tries = card.getPINTriesLeft(pin);
                    if (tries >= 0)
                        entry.retriesLeft = tries;
                    entry.blocked = (tries == 0);
                } catch (...) {
                    // leave entry.retriesLeft as std::nullopt
                }
            }

            if (pin.minLength > 0)
                entry.minLength = static_cast<std::size_t>(pin.minLength);
            if (pin.maxLength > 0)
                entry.maxLength = static_cast<std::size_t>(pin.maxLength);
            entry.canChange = !pin.unblockingPin && pin.label.find("PUK") == std::string::npos;
            result.push_back(std::move(entry));
        }
        return result;
    }

    LibreSCRS::Plugin::PINResult changePIN(LibreSCRS::SmartCard::CardSession& session, std::string_view pinLabel,
                                           const LibreSCRS::Secure::String& oldPin,
                                           const LibreSCRS::Secure::String& newPin) const override
    {
        LibreSCRS::Plugin::PINResult result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=changePIN");
        auto profile = card.readProfile();

        const pkcs15::PinInfo* pinInfo = findPinByLabel(profile, pinLabel);
        if (!pinInfo)
            pinInfo = findUserPin(profile);
        if (!pinInfo) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }

        auto r = card.changePIN(*pinInfo, oldPin.view(), newPin.view());
        if (r.retriesLeft >= 0)
            result.retriesLeft = r.retriesLeft;
        result.blocked = r.blocked;
        if (r.success)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (result.blocked)
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (result.retriesLeft.has_value())
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return result;
    }

    std::optional<int> getPINTriesLeft(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return std::nullopt;
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr)
            return std::nullopt;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=getPINTriesLeft");
        auto profile = card.readProfile();
        auto* pin = findUserPin(profile);
        if (!pin)
            return std::nullopt;

        int tries = card.getPINTriesLeft(*pin);
        if (tries < 0)
            return std::nullopt;
        return tries;
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& session,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        LibreSCRS::Plugin::PINResult out;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult) {
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return out;
        }
        auto holder = std::move(*holderResult);
        auto* channel = holder.activeChannel();
        if (channel == nullptr) {
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return out;
        }

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=verifyPIN");
        auto profile = card.readProfile();
        auto* pinInfo = findUserPin(profile);
        if (!pinInfo)
            return {};

        auto r = card.verifyPIN(*pinInfo, pin.view());
        if (r.retriesLeft >= 0)
            out.retriesLeft = r.retriesLeft;
        out.blocked = r.blocked;
        if (r.success)
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::Ok;
        else if (out.blocked)
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::Blocked;
        else if (out.retriesLeft.has_value())
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::InvalidPin;
        else
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
        return out;
    }

private:
    bool requiresPaceFor(LibreSCRS::SmartCard::CardSession& session) const
    {
        std::lock_guard lock(stateMutex);
        auto it = sessions.find(makeSessionKey(session));
        return it != sessions.end() && it->second.requiresPace;
    }

    static LibreSCRS::Plugin::ReadResult mapActivationError(LibreSCRS::SecureChannel::ChannelActivationError err,
                                                            const char* what)
    {
        using LibreSCRS::Plugin::ReadResult;
        using Err = LibreSCRS::SecureChannel::ChannelActivationError;
        std::string suffix;
        switch (err) {
        case Err::Cancelled:
        case Err::UserCancelled:
            suffix = "user cancelled";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::PaceWrongSecret:
            suffix = "wrong CAN";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::CredentialsRequired:
            suffix = "CAN required";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::CardRemoved:
            suffix = "card removed";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        case Err::SelectAppletFailed:
            suffix = "failed to select PKCS#15 applet";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        case Err::PaceUnsupported:
            suffix = "card does not support PACE";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        default:
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": activation failed");
        }
    }

    static const pkcs15::PinInfo* findUserPin(const pkcs15::PKCS15Profile& profile)
    {
        for (const auto& pin : profile.pins) {
            if (pin.local && pin.initialized)
                return &pin;
        }
        for (const auto& pin : profile.pins) {
            if (pin.initialized)
                return &pin;
        }
        return nullptr;
    }

    static const pkcs15::PinInfo* findPinByLabel(const pkcs15::PKCS15Profile& profile, std::string_view pinLabel)
    {
        if (pinLabel.empty())
            return nullptr;

        for (const auto& pin : profile.pins) {
            if (pin.label == pinLabel)
                return &pin;
        }

        constexpr std::string_view prefix = "pin_";
        if (pinLabel.starts_with(prefix)) {
            std::string_view suffix = pinLabel.substr(prefix.size());
            for (const auto& pin : profile.pins) {
                if (pin.label == suffix)
                    return &pin;
            }
            try {
                std::string suffixStr{suffix};
                size_t consumed = 0;
                int ref = std::stoi(suffixStr, &consumed);
                if (consumed == suffixStr.size() && ref >= 0 && ref <= 0xFF) {
                    for (const auto& pin : profile.pins) {
                        if (pin.pinReference == static_cast<uint8_t>(ref))
                            return &pin;
                    }
                }
            } catch (const std::exception&) {
                // fall through
            }
        }

        return nullptr;
    }

    mutable std::mutex stateMutex;
    mutable std::map<SessionKey, SessionContext> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(PKCS15CardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
