// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

#include <pkcs15_card.h>
#include <pkcs15_types.h>

#include <internal/PinClassification.h>

#include <LibreSCRS/Auth/ErrorKeys.h>
#include <LibreSCRS/Auth/PaceSecretKind.h>
#include <LibreSCRS/CancelToken.h>
#include <LibreSCRS/Plugin/CardPlugin.h>
#include <LibreSCRS/Plugin/PinOutcome.h>
#include <LibreSCRS/Plugin/PluginExport.h>
#include <LibreSCRS/Plugin/SessionKey.h>
#include <LibreSCRS/Secure/String.h>
#include <LibreSCRS/SecureChannel/ChannelErrors.h>
#include <LibreSCRS_internal/SecureChannel/ISecureChannel.h>
#include <LibreSCRS_internal/SecureChannel/PlainChannel.h>
#include <LibreSCRS/SmartCard/ActiveChannelHolder.h>
#include <LibreSCRS/SmartCard/AppletAid.h>
#include <LibreSCRS_internal/SmartCard/ActiveChannelHolderInternal.h>
#include <LibreSCRS/SmartCard/CardSession.h>
#include <LibreSCRS/SmartCard/SmProtocolRequest.h>
#include <LibreSCRS/SmartCard/detail/Unwrap.h>
#include <apdu.h>
#include <pcsc_connection.h>

#include <algorithm>
#include <compare>
#include <cstdint>
#include <cstdio>
#include <exception>
#include <expected>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <variant>

#include "manifest.h" // generated by librescrs_add_plugin (A5)
#include "probe_trace.h"

namespace {

// A5 (4.0 hardening): generic PKCS#15 matches via SELECT-DF probe in
// canHandleConnection, never via ATR. kAtrs (from manifest.json) is
// intentionally empty.

// Per-session state-map key + factory — the sanctioned plugin-support shape
// shared with the other CardPlugin implementations.
using LibreSCRS::Plugin::makeSessionKey;
using LibreSCRS::Plugin::SessionKey;

/// @brief Plugin-side memory of whether this card session is PACE-gated.
///
/// PACE / SM ownership lives on @ref LibreSCRS::SmartCard::CardSession;
/// the plugin only needs to know *which* activation flavour to request
/// for a given operation (plain vs. PACE-CAN). The CAN itself is held by
/// CardSession via @ref CardSession::setPaceSecret. This struct is
/// intentionally tiny.
struct SessionContext
{
    /// @brief @c true after a successful "PACE required" probe (canHandle
    ///        returned needsPace) or after @ref setCredentials("can", ...)
    ///        has been called. When false the plugin uses
    ///        @ref activateChannelFor (PlainChannel) instead of
    ///        @ref activateChannelWithSm.
    bool requiresPace{false};

    /// @brief The signing PIN, deposited per-session by the caller via
    ///        @ref setCredentials("pin", ...) immediately before a sign.
    ///
    /// Held here (not on @ref CardSession, which only owns PACE secrets) as a
    /// transient, session-scoped @ref LibreSCRS::Secure::String: it is consumed
    /// by @ref doSign (hash-on-card RSA-SHA256, where the lower
    /// @c PKCS15Card::sign owns the atomic verify+sign and therefore needs the
    /// PIN) and wiped when the session entry is erased by
    /// @ref clearCredentials. The map is keyed by session, so no cross-reader
    /// bleed. @since 4.3
    LibreSCRS::Secure::String pin;
};

LibreSCRS::SmartCard::AppletAid pkcs15AppletAid()
{
    return LibreSCRS::SmartCard::AppletAid::fromBytes(
        std::span<const std::uint8_t>{pkcs15::kPkcs15Aid.data(), pkcs15::kPkcs15Aid.size()});
}

/// @brief Result of a cheap reachability probe against the AID, used to
///        decide whether PACE is required.
enum class ProbeResult {
    Ok,         ///< Plain SELECT succeeded — no SM needed for this card.
    NeedsPace,  ///< Card returned 6982 — PACE must be run first.
    Unreachable ///< Other failure; treat as not-PKCS#15.
};

ProbeResult probeApplet(LibreSCRS::SmartCard::Internal::PCSCConnection& conn)
{
    std::vector<std::uint8_t> aid(pkcs15::kPkcs15Aid.begin(), pkcs15::kPkcs15Aid.end());
    auto aidResp = conn.transmit(LibreSCRS::SmartCard::Internal::selectByAID(aid, 0x0C));
    if (aidResp.isSuccess())
        return ProbeResult::Ok;
    if (aidResp.sw1 == 0x69 && aidResp.sw2 == 0x82)
        return ProbeResult::NeedsPace;
    return ProbeResult::Unreachable;
}

/// @brief Acquire an @ref ActiveChannelHolder appropriate for this session.
///
/// PACE-gated cards take the SM activation path
/// (@ref CardSession::activateChannelWithSm with @c PaceRequest{Can});
/// non-PACE cards take the plain path. The CAN — if needed — must have
/// been deposited in CardSession's cache via @ref setCredentials before
/// this call; CardSession's preflight short-circuits with
/// @c CredentialsRequired if neither a cached CAN nor a provider is
/// available. A PaceChannel installed earlier by emrtd-plugin (when the
/// user came through the display flow first) is reused via wrapped
/// SELECT on the existing SM tunnel — no rePACE.
std::expected<LibreSCRS::SmartCard::ActiveChannelHolder, LibreSCRS::SecureChannel::ChannelActivationError>
acquireChannel(LibreSCRS::SmartCard::CardSession& session, bool requiresPace)
{
    auto aid = pkcs15AppletAid();
    if (requiresPace) {
        return session.activateChannelWithSm(
            aid, LibreSCRS::SmartCard::PaceRequest{LibreSCRS::Auth::PaceSecretKind::Can}, LibreSCRS::CancelToken{});
    }
    return session.activateChannelFor(aid, LibreSCRS::CancelToken{});
}

class PKCS15CardPlugin final : public LibreSCRS::Plugin::CardPlugin
{
public:
    PKCS15CardPlugin()
    {
        setIdentity(std::string{LibreSCRS::Plugin::generated::pkcs15::kPluginId},
                    std::string{LibreSCRS::Plugin::generated::pkcs15::kDisplayName},
                    /*priority=*/900);
    }

    LibreSCRS::Plugin::CardCapabilities capabilities() const override
    {
        return LibreSCRS::Plugin::generated::pkcs15::kCapabilities;
    }

    // NAM / IAS-ECC and other PACE-gated PKCS#15 cards require the CAN (PACE)
    // before any read; plain PKCS#15 cards do not. The base derives this from a
    // STATIC activation profile (plain -> None), but this plugin decides PACE at
    // RUNTIME via the probe (see canHandle / requiresPaceFor), so the static
    // derivation under-reports as None. Report it correctly here: PaceCan when
    // the card needs PACE (which is also the signal that selects on-card SHA-256
    // signing — IAS-ECC SSCDs hash the message on-card), else None.
    LibreSCRS::Auth::PreReadAuthMethod preReadAuth(LibreSCRS::SmartCard::CardSession& session) const override
    {
        return requiresPaceFor(session) ? LibreSCRS::Auth::PreReadAuthMethod::PaceCan
                                        : LibreSCRS::Auth::PreReadAuthMethod::None;
    }

    std::span<const LibreSCRS::Plugin::Atr> supportedAtrs() const noexcept override
    {
        return LibreSCRS::Plugin::generated::pkcs15::kAtrs;
    }

    bool canHandleConnection(std::span<const std::uint8_t> /*atr*/,
                             LibreSCRS::SmartCard::CardSession& session) const override
    {
        const auto mapKey = makeSessionKey(session);
        try {
            // A live SM channel on the session means PACE/BAC has already
            // been established (e.g. user came through the emrtd-plugin
            // display flow first). PACE SM is session-scoped per BSI
            // TR-03110 §3 — a plain SELECT-AID over the raw connection
            // would reset the card-side SM context, breaking the next
            // wrapped APDU. Probe the PKCS#15 applet through the SM-aware
            // CardSession::transmitInternal funnel instead: wrapped
            // SELECT-AID stays inside the SM tunnel and the response SW
            // distinguishes "applet present" (0x9000 — Serbian eID and
            // similar hybrid cards, accept the candidate and route
            // subsequent acquireChannel() through the SM activation fast
            // path) from "applet absent" (e.g. 0x6A82 — foreign passport
            // that exposes only the eMRTD LDS and no PKCS#15 layer;
            // decline so the host does not attach an empty Token section
            // to a card it cannot actually read certificates from).
            if (session.hasLiveSecureChannel()) {
                std::vector<std::uint8_t> probeAid(::pkcs15::kPkcs15Aid.begin(), ::pkcs15::kPkcs15Aid.end());
                auto probeResp =
                    session.transmitInternal(LibreSCRS::SmartCard::Internal::selectByAID(probeAid, /*p2=*/0x0C));
                if (probeResp.isSuccess()) {
                    std::lock_guard lock(stateMutex);
                    sessions[mapKey].requiresPace = true;
                    LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=needsPace via=liveSm-wrapped-probe");
                    return true;
                }
                char swBuf[12];
                std::snprintf(swBuf, sizeof(swBuf), "0x%04X", probeResp.statusWord());
                LibreSCRS::Internal::probeTrace(std::string{"PROBE-PKCS15-CANHANDLE result=false "
                                                            "via=liveSm-wrapped-probe SW="} +
                                                swBuf);
                return false;
            }
            auto& conn = LibreSCRS::SmartCard::detail::unwrap(session);
            // Cheap, no-SM probe to decide between PlainChannel (contact
            // PKCS#15 families) and PaceChannel (PACE-gated contactless
            // families) for subsequent operations. The actual applet
            // selection happens later through
            // CardSession::activateChannel{For,WithSm}.
            const auto state = probeApplet(conn);
            if (state == ProbeResult::Ok) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = false;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=true");
                return true;
            }
            if (state == ProbeResult::NeedsPace) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = true;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=needsPace");
                return true;
            }
            // Unreachable: try the full PKCS15Card probe path which includes
            // EF.DIR fallback (some cards expose PKCS#15 only through the
            // EF.DIR application registry, not via direct AID SELECT).
            LibreSCRS::SecureChannel::PlainChannel probeChannel(conn, LibreSCRS::SmartCard::AppletAid{});
            pkcs15::PKCS15Card card(probeChannel);
            if (card.probe()) {
                std::lock_guard lock(stateMutex);
                sessions[mapKey].requiresPace = false;
                LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=true");
                return true;
            }
            LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=false");
            return false;
        } catch (...) {
            LibreSCRS::Internal::probeTrace("PROBE-PKCS15-CANHANDLE result=false threw=true");
            return false;
        }
    }

    void setCredentials(LibreSCRS::SmartCard::CardSession& session, std::string_view key,
                        const LibreSCRS::Secure::String& value) override
    {
        if (key == "can") {
            // CardSession owns the CAN cache; this plugin simply forwards the
            // secret. Successful PACE activation through CardSession reuses
            // the same cache slot whether the secret was deposited by
            // emrtd-plugin (display flow) or by us (direct sign).
            session.setPaceSecret(LibreSCRS::Auth::PaceSecretKind::Can, LibreSCRS::Secure::String{value.view()});
            std::lock_guard lock(stateMutex);
            sessions[makeSessionKey(session)].requiresPace = true;
            return;
        }
        if (key == "pin") {
            // The signing PIN: held per-session for the immediately following
            // hash-on-card sign (see @ref doSign), where the lower
            // PKCS15Card::sign owns the atomic verify+MSE+PSO and therefore
            // needs the PIN. Wiped by clearCredentials. CardSession only owns
            // PACE secrets, so the eSign PIN lives here (session-keyed map ->
            // no cross-reader bleed), NOT in the PACE cache.
            std::lock_guard lock(stateMutex);
            sessions[makeSessionKey(session)].pin = LibreSCRS::Secure::String{value.view()};
            return;
        }
    }

    void clearCredentials(LibreSCRS::SmartCard::CardSession& session) noexcept override
    {
        try {
            std::lock_guard lock(stateMutex);
            sessions.erase(makeSessionKey(session));
        } catch (...) {
            // clearCredentials is noexcept; swallow allocator faults.
        }
    }

    LibreSCRS::Plugin::ReadResult doReadCard(LibreSCRS::SmartCard::CardSession& session,
                                             GroupCallback onGroup) const override
    {
        using LibreSCRS::Plugin::ReadResult;
        try {
            auto holderResult = acquireChannel(session, requiresPaceFor(session));
            if (!holderResult)
                return mapActivationError(holderResult.error(), "pkcs15 doReadCard");
            auto holder = std::move(*holderResult);
            auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
            if (channel == nullptr)
                return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                      "pkcs15 doReadCard: channel not active after activation");

            pkcs15::PKCS15Card card(*channel);
            LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=doReadCard");
            auto profile = card.readProfile();

            LibreSCRS::Plugin::CardData data;
            data.cardType = "pkcs15";

            auto emitGroup = [&](LibreSCRS::Plugin::CardFieldGroup&& group) {
                if (onGroup)
                    onGroup(data.cardType, group);
                data.groups.push_back(std::move(group));
            };

            {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "token";
                group.groupLabel = "Token Info";
                group.addText("label", "Label", profile.tokenInfo.label);
                group.addText("serial_number", "Serial Number", profile.tokenInfo.serialNumber);
                group.addText("manufacturer", "Manufacturer", profile.tokenInfo.manufacturer);
                emitGroup(std::move(group));
            }

            if (!profile.certificates.empty()) {
                LibreSCRS::Plugin::CardFieldGroup group;
                group.groupKey = "certificates";
                group.groupLabel = "Certificates";
                for (const auto& cert : profile.certificates) {
                    group.addText("cert_" + cert.label, cert.label, cert.label);
                }
                emitGroup(std::move(group));
            }

            // PIN state is surfaced via the typed getPINList() override
            // (PinStatusEntry vector), not via the readCard() data groups.

            return ReadResult::ok(std::move(data));
        } catch (const std::exception& ex) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"pkcs15 readCard failed: "} + ex.what());
        } catch (...) {
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{"pkcs15 readCard failed (unknown error)"});
        }
    }

    LibreSCRS::Plugin::CardFieldGroup readTokenInfo(LibreSCRS::SmartCard::CardSession& session) const override
    {
        // Best-effort token-info read. Every failure mode below degrades to
        // a partial or empty group rather than escaping an exception:
        //   - channel activation failure → empty group, no fields
        //   - card.readTokenInfo() throw (select / SM teardown / parse) →
        //     empty group, no fields
        //   - per-field addText failure → the offending field is skipped,
        //     siblings are preserved
        //
        // The presentation layer relies on the group's key/label being set
        // up-front so it can render its placeholder header from an empty
        // group; the fields vector is permitted to be empty when nothing
        // could be read.
        LibreSCRS::Plugin::CardFieldGroup group;
        group.groupKey = "token";
        group.groupLabel = "Token Info";

        // Diagnostics route through std::clog with the
        // "[librescrs.pkcs15.plugin]" category prefix to keep this TU (and
        // therefore the dlopen'd plugin .so) Qt-free. LM plugins are loaded
        // by LibreCelik (Qt6), LibreKDE (Qt6+KF6), LibreMac BridgeNative
        // (Swift), and p11-kit consumers (Kleopatra, Firefox, gpgsm,
        // Thunderbird) — pulling Qt into the plugin would break the Qt-free
        // hosts. Pattern mirrors MonitorService.cpp's flood-warning emission.
        std::optional<LibreSCRS::SmartCard::ActiveChannelHolder> holderOpt;
        try {
            auto holderResult = acquireChannel(session, requiresPaceFor(session));
            if (!holderResult) {
                std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: acquireChannel failed with code "
                          << static_cast<int>(holderResult.error()) << "\n";
                return group;
            }
            holderOpt.emplace(std::move(*holderResult));
        } catch (const std::exception& ex) {
            std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: acquireChannel threw: " << ex.what() << "\n";
            return group;
        } catch (...) {
            std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: acquireChannel threw (non-std exception)\n";
            return group;
        }

        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(*holderOpt);
        if (channel == nullptr) {
            std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: channel not active after activation\n";
            return group;
        }

        pkcs15::TokenInfo info;
        try {
            pkcs15::PKCS15Card card(*channel);
            info = card.readTokenInfo();
        } catch (const std::exception& ex) {
            std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: card.readTokenInfo threw: " << ex.what() << "\n";
            return group;
        } catch (...) {
            std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: card.readTokenInfo threw (non-std exception)\n";
            return group;
        }

        // Per-field guard: skip empty values up-front (CardFieldGroup::addText
        // throws std::logic_error on `(empty value, empty fields)` by design,
        // so unconditional calls would cascade a single missing field into a
        // fully empty group). The try/catch around addText is the defensive
        // tail: even if the upstream contract relaxes, the plugin still
        // returns whatever sibling fields succeeded.
        auto safeAddText = [&](std::string_view key, std::string_view label, std::string_view value) {
            if (value.empty())
                return;
            try {
                group.addText(key, label, value);
            } catch (const std::exception& ex) {
                std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: addText(" << key << ") threw: " << ex.what()
                          << "\n";
            } catch (...) {
                std::clog << "[librescrs.pkcs15.plugin] readTokenInfo: addText threw (non-std exception)\n";
            }
        };

        safeAddText("label", "Label", info.label);
        safeAddText("serial_number", "Serial Number", info.serialNumber);
        safeAddText("manufacturer", "Manufacturer", info.manufacturer);
        return group;
    }

    std::vector<LibreSCRS::Plugin::CertificateData>
    readCertificates(LibreSCRS::SmartCard::CardSession& session) const override
    {
        std::vector<LibreSCRS::Plugin::CertificateData> result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return result;
        auto holder = std::move(*holderResult);
        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
        if (channel == nullptr)
            return result;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=readCertificates");
        auto profile = card.readProfile();

        for (const auto& cert : profile.certificates) {
            auto der = card.readCertificate(cert);
            if (der.empty())
                continue;

            LibreSCRS::Plugin::CertificateData cd;
            cd.label = cert.label;
            cd.derBytes = std::move(der);
            // The PKCS#15 object id IS the PKCS#11 CKA_ID the bridge exposes
            // (see pkcs15_pkcs11_slot.cpp) — surface it so the in-process sign
            // path can select THIS exact key by CKA_ID rather than the
            // non-unique label.
            cd.ckaId = cert.id;

            for (const auto& key : profile.privateKeys) {
                if (key.id == cert.id) {
                    if (key.path.size() >= 2) {
                        cd.keyFID = static_cast<std::uint16_t>((key.path[key.path.size() - 2] << 8) |
                                                               key.path[key.path.size() - 1]);
                    } else if (key.keyReference != 0) {
                        cd.keyFID = static_cast<std::uint16_t>(key.keyReference);
                    } else {
                        cd.keyFID = std::uint16_t{1};
                    }
                    if (key.keySizeBits != 0)
                        cd.keySizeBits = key.keySizeBits;
                    break;
                }
            }

            result.push_back(std::move(cd));
        }

        return result;
    }

    std::vector<LibreSCRS::Plugin::PinStatusEntry> getPINList(LibreSCRS::SmartCard::CardSession& session) const override
    {
        std::vector<LibreSCRS::Plugin::PinStatusEntry> result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return result;
        auto holder = std::move(*holderResult);
        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
        if (channel == nullptr)
            return result;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=getPINList");
        auto profile = card.readProfile();

        for (const auto& pin : profile.pins) {
            LibreSCRS::Plugin::PinStatusEntry entry;
            entry.label = pin.label;
            entry.reference = pin.pinReference;
            entry.initialized = pin.initialized;

            if (pin.initialized) {
                try {
                    int tries = card.getPINTriesLeft(pin);
                    if (tries >= 0)
                        entry.retriesLeft = tries;
                    entry.blocked = (tries == 0);
                } catch (...) {
                    // leave entry.retriesLeft as std::nullopt
                }
            }

            if (pin.minLength > 0)
                entry.minLength = static_cast<std::size_t>(pin.minLength);
            if (pin.maxLength > 0)
                entry.maxLength = static_cast<std::size_t>(pin.maxLength);
            entry.canChange = !pin.unblockingPin && pin.label.find("PUK") == std::string::npos;
            result.push_back(std::move(entry));
        }
        return result;
    }

    LibreSCRS::Plugin::PINResult changePIN(LibreSCRS::SmartCard::CardSession& session, std::string_view pinLabel,
                                           const LibreSCRS::Secure::String& oldPin,
                                           const LibreSCRS::Secure::String& newPin) const override
    {
        LibreSCRS::Plugin::PINResult result;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }
        auto holder = std::move(*holderResult);
        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
        if (channel == nullptr) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=changePIN");
        auto profile = card.readProfile();

        const pkcs15::PinInfo* pinInfo = findPinByLabel(profile, pinLabel);
        if (!pinInfo)
            pinInfo = findUserPin(profile);
        if (!pinInfo) {
            result.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return result;
        }

        auto r = card.changePIN(*pinInfo, oldPin.view(), newPin.view());
        if (r.retriesLeft >= 0)
            result.retriesLeft = r.retriesLeft;
        result.blocked = r.blocked;
        result.outcome = LibreSCRS::Plugin::classifyPinOutcome(result, r.success);
        return result;
    }

    std::optional<int> getPINTriesLeft(LibreSCRS::SmartCard::CardSession& session) const override
    {
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult)
            return std::nullopt;
        auto holder = std::move(*holderResult);
        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
        if (channel == nullptr)
            return std::nullopt;

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=getPINTriesLeft");
        auto profile = card.readProfile();
        auto* pin = findUserPin(profile);
        if (!pin)
            return std::nullopt;

        int tries = card.getPINTriesLeft(*pin);
        if (tries < 0)
            return std::nullopt;
        return tries;
    }

    // Raw on-card RSA decrypt is not yet implemented for the generic PKCS#15
    // fallback family. Unlike the opensc plugin (which binds an
    // sc_pkcs15_card_t and delegates to sc_pkcs15_decipher), this plugin
    // operates over the LM-native pkcs15::PKCS15Card abstraction on an SM
    // channel and has no libopensc card handle. A raw-decrypt path would
    // require a dedicated MSE:Set-CT (P2=0xB8) + PSO DECIPHER APDU sequence on
    // pkcs15::PKCS15Card mirroring its sign() path — new on-card crypto rather
    // than a delegation — so it is deferred. Returning NotImplemented
    // explicitly (rather than inheriting the base default) keeps the gap
    // visible to callers and documents the reason at the override site.
    LibreSCRS::Plugin::DecipherResult doDecipher(LibreSCRS::SmartCard::CardSession& /*session*/,
                                                 std::uint16_t /*keyReference*/,
                                                 std::span<const std::uint8_t> /*ciphertext*/,
                                                 LibreSCRS::Plugin::DecipherMechanism /*mechanism*/) const override
    {
        LibreSCRS::Plugin::DecipherResult r;
        r.outcome = LibreSCRS::Plugin::DecipherResultOutcome::NotImplemented;
        return r;
    }

    // Hash-on-card RSA-SHA256 signing for the IAS-ECC / PKCS#15 family
    // (NAM: Cryptovision SCE 8.0-C2V0 SSCD). The caller deposits the signing
    // PIN via setCredentials("pin", ...) immediately before this call (the same
    // per-session seam used for the CAN). PKCS15Card::sign owns the atomic
    // select + verifyPIN + MSE(0x28) + PSO over the RAW message — the exact
    // EVP-verified sequence the LibreCelik / AdES path uses — so we do NOT
    // pre-verify here. Only RSA_SHA256 (raw message, card hashes) is honoured;
    // a caller-supplied DigestInfo (RSA_PKCS) is rejected by these cards, so
    // that mechanism inherits the base NotImplemented.
    LibreSCRS::Plugin::SignResult doSign(LibreSCRS::SmartCard::CardSession& session, std::uint16_t keyReference,
                                         std::span<const std::uint8_t> data,
                                         LibreSCRS::Plugin::SignMechanism mechanism) const override
    {
        LibreSCRS::Plugin::SignResult r;
        // Honour RSA_SHA256 ONLY for cards that actually hash on-card — i.e.
        // PACE-gated IAS-ECC SSCDs (NAM). For any other mechanism, OR a plain
        // PKCS#15 card (no PACE) that expects a caller-built DigestInfo, return
        // NotImplemented so the agent falls back to its verify + RSA_PKCS
        // DigestInfo path. This matters because RsaSha256Pkcs1's on-card attempt
        // set (pkcs15_card.cpp) is narrower than RsaPkcs1 and brute-forces
        // hash-on-card algos, which is wrong for a DigestInfo card; gating here
        // keeps the fallback alive for the rest of the PKCS#15 family (only the
        // NAM hash-on-card path is exercised + HW-verified today).
        if (mechanism != LibreSCRS::Plugin::SignMechanism::RSA_SHA256 || !requiresPaceFor(session)) {
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::NotImplemented;
            return r;
        }
        // Pull the per-session signing PIN deposited by setCredentials("pin").
        LibreSCRS::Secure::String pin;
        {
            std::lock_guard lock(stateMutex);
            auto it = sessions.find(makeSessionKey(session));
            if (it != sessions.end())
                pin = LibreSCRS::Secure::String{it->second.pin.view()};
        }
        if (pin.view().empty()) {
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError; // no PIN deposited
            return r;
        }
        try {
            auto holderResult = acquireChannel(session, requiresPaceFor(session));
            if (!holderResult) {
                r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
                return r;
            }
            auto holder = std::move(*holderResult);
            auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
            if (channel == nullptr) {
                r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
                return r;
            }
            pkcs15::PKCS15Card card(*channel);
            auto profile = card.readProfile();

            // Resolve the private key whose on-card file id matches keyReference
            // (the keyFID readCertificates surfaced from the PrKDF path).
            const pkcs15::PrivateKeyInfo* matched = nullptr;
            for (const auto& key : profile.privateKeys) {
                std::uint16_t fid;
                if (key.path.size() >= 2)
                    fid = static_cast<std::uint16_t>((key.path[key.path.size() - 2] << 8) |
                                                     key.path[key.path.size() - 1]);
                else if (key.keyReference != 0)
                    fid = static_cast<std::uint16_t>(key.keyReference);
                else
                    fid = std::uint16_t{1};
                if (fid == keyReference) {
                    matched = &key;
                    break;
                }
            }
            const pkcs15::PinInfo* pinInfo = findUserPin(profile);
            if (matched == nullptr || pinInfo == nullptr) {
                r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
                return r;
            }

            // PKCS15Card::sign takes both a DigestInfo and the raw data; for the
            // RsaSha256Pkcs1 scheme the winning attempt on a hash-on-card SSCD
            // is {algo 0x28, rawData} (the card hashes). Pass the raw message in
            // both slots, mirroring the EVP-verified in-process path
            // (Pkcs15Slot::signData). pin.view() references `pin`, alive here.
            std::vector<std::uint8_t> dataVec(data.begin(), data.end());
            auto sig = card.sign(*matched, pin.view(), *pinInfo, dataVec, dataVec, pkcs15::SignScheme::RsaSha256Pkcs1);
            if (sig.empty()) {
                r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
                return r;
            }
            r.signature = std::move(sig);
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::Ok;
            return r;
        } catch (...) {
            // PKCS15Card::sign throws a generic runtime_error on wrong PIN /
            // exhausted attempts. LIMITATION (constrained by the no-ABI-bump
            // rule — SignResultOutcome has no AuthFailed variant and the throw
            // is untyped): a wrong eSign PIN folds to PluginError here, which the
            // agent maps to CardError -> CKR_DEVICE_ERROR, NOT CKR_PIN_INCORRECT.
            // Counter-safety is preserved per op: the agent does a SINGLE attempt
            // (no retry on PluginError; the DigestInfo fallback fires only on
            // NotImplemented), so the card's PIN counter is touched at most once,
            // and the HW test's g_pinFailed latch blocks further attempts. A host
            // must NOT auto-retry on CKR_DEVICE_ERROR (it is not a PIN-retry hint).
            r.outcome = LibreSCRS::Plugin::SignResultOutcome::PluginError;
            return r;
        }
    }

    LibreSCRS::Plugin::PINResult verifyPIN(LibreSCRS::SmartCard::CardSession& session,
                                           const LibreSCRS::Secure::String& pin) const override
    {
        LibreSCRS::Plugin::PINResult out;
        auto holderResult = acquireChannel(session, requiresPaceFor(session));
        if (!holderResult) {
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return out;
        }
        auto holder = std::move(*holderResult);
        auto* channel = LibreSCRS::SmartCard::Internal::HolderChannelAccessor::channel(holder);
        if (channel == nullptr) {
            out.outcome = LibreSCRS::Plugin::PINResultOutcome::PluginError;
            return out;
        }

        pkcs15::PKCS15Card card(*channel);
        LibreSCRS::Internal::probeTrace("PROBE-READPROFILE call=verifyPIN");
        auto profile = card.readProfile();
        auto* pinInfo = findUserPin(profile);
        if (!pinInfo)
            return {};

        auto r = card.verifyPIN(*pinInfo, pin.view());
        if (r.retriesLeft >= 0)
            out.retriesLeft = r.retriesLeft;
        out.blocked = r.blocked;
        out.outcome = LibreSCRS::Plugin::classifyPinOutcome(out, r.success);
        return out;
    }

private:
    bool requiresPaceFor(LibreSCRS::SmartCard::CardSession& session) const
    {
        std::lock_guard lock(stateMutex);
        auto it = sessions.find(makeSessionKey(session));
        return it != sessions.end() && it->second.requiresPace;
    }

    static LibreSCRS::Plugin::ReadResult mapActivationError(LibreSCRS::SecureChannel::ChannelActivationError err,
                                                            const char* what)
    {
        using LibreSCRS::Plugin::ReadResult;
        using Err = LibreSCRS::SecureChannel::ChannelActivationError;
        std::string suffix;
        switch (err) {
        case Err::Cancelled:
        case Err::UserCancelled:
            suffix = "user cancelled";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::PaceWrongSecret:
            suffix = "wrong CAN";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::CredentialsRequired:
            suffix = "CAN required";
            return ReadResult::authenticationFailed(LibreSCRS::Auth::ErrorKeys::authFailed(),
                                                    std::string{what} + ": " + suffix);
        case Err::CardRemoved:
            suffix = "card removed";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        case Err::SelectAppletFailed:
            suffix = "failed to select PKCS#15 applet";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        case Err::PaceUnsupported:
            suffix = "card does not support PACE";
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": " + suffix);
        default:
            return ReadResult::communicationError(LibreSCRS::Auth::ErrorKeys::genericComm(),
                                                  std::string{what} + ": activation failed");
        }
    }

    static const pkcs15::PinInfo* findUserPin(const pkcs15::PKCS15Profile& profile)
    {
        using LibreSCRS::Pkcs15::Internal::isUserPin;
        for (const auto& pin : profile.pins) {
            if (isUserPin(pin) && pin.local && pin.initialized)
                return &pin;
        }
        for (const auto& pin : profile.pins) {
            if (isUserPin(pin) && pin.initialized)
                return &pin;
        }
        return nullptr;
    }

    static const pkcs15::PinInfo* findPinByLabel(const pkcs15::PKCS15Profile& profile, std::string_view pinLabel)
    {
        if (pinLabel.empty())
            return nullptr;

        for (const auto& pin : profile.pins) {
            if (pin.label == pinLabel)
                return &pin;
        }

        constexpr std::string_view prefix = "pin_";
        if (pinLabel.starts_with(prefix)) {
            std::string_view suffix = pinLabel.substr(prefix.size());
            for (const auto& pin : profile.pins) {
                if (pin.label == suffix)
                    return &pin;
            }
            try {
                std::string suffixStr{suffix};
                size_t consumed = 0;
                int ref = std::stoi(suffixStr, &consumed);
                if (consumed == suffixStr.size() && ref >= 0 && ref <= 0xFF) {
                    for (const auto& pin : profile.pins) {
                        if (pin.pinReference == static_cast<uint8_t>(ref))
                            return &pin;
                    }
                }
            } catch (const std::exception&) {
                // fall through
            }
        }

        return nullptr;
    }

    mutable std::mutex stateMutex;
    mutable std::map<SessionKey, SessionContext> sessions;
};

} // namespace

LIBRESCRS_DECLARE_CARD_PLUGIN(PKCS15CardPlugin, LibreSCRS::Plugin::kCardPluginAbiVersion)
